// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/builtin/plugins/coin/coin.proto

/*
Package coin is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/go-loom/builtin/plugins/coin/coin.proto

It has these top-level messages:
	BigUInt
	Economy
	Account
	InitRequest
	TotalSupplyRequest
	TotalSupplyResponse
	BalanceOfRequest
	BalanceOfResponse
	AllowanceRequest
	AllowanceResponse
	ApproveRequest
	ApproveResponse
	TransferRequest
	TransferResponse
	TransferFromRequest
	TransferFromResponse
*/
package coin

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type BigUInt struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *BigUInt) Reset()                    { *m = BigUInt{} }
func (m *BigUInt) String() string            { return proto.CompactTextString(m) }
func (*BigUInt) ProtoMessage()               {}
func (*BigUInt) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{0} }

func (m *BigUInt) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Economy struct {
	TotalSupply *BigUInt `protobuf:"bytes,1,opt,name=total_supply,json=totalSupply" json:"total_supply,omitempty"`
}

func (m *Economy) Reset()                    { *m = Economy{} }
func (m *Economy) String() string            { return proto.CompactTextString(m) }
func (*Economy) ProtoMessage()               {}
func (*Economy) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{1} }

func (m *Economy) GetTotalSupply() *BigUInt {
	if m != nil {
		return m.TotalSupply
	}
	return nil
}

type Account struct {
	Owner   *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Balance *BigUInt       `protobuf:"bytes,2,opt,name=balance" json:"balance,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{2} }

func (m *Account) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Account) GetBalance() *BigUInt {
	if m != nil {
		return m.Balance
	}
	return nil
}

type InitRequest struct {
	Accounts []*Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{3} }

func (m *InitRequest) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// read only
type TotalSupplyRequest struct {
}

func (m *TotalSupplyRequest) Reset()                    { *m = TotalSupplyRequest{} }
func (m *TotalSupplyRequest) String() string            { return proto.CompactTextString(m) }
func (*TotalSupplyRequest) ProtoMessage()               {}
func (*TotalSupplyRequest) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{4} }

type TotalSupplyResponse struct {
	TotalSupply *BigUInt `protobuf:"bytes,1,opt,name=total_supply,json=totalSupply" json:"total_supply,omitempty"`
}

func (m *TotalSupplyResponse) Reset()                    { *m = TotalSupplyResponse{} }
func (m *TotalSupplyResponse) String() string            { return proto.CompactTextString(m) }
func (*TotalSupplyResponse) ProtoMessage()               {}
func (*TotalSupplyResponse) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{5} }

func (m *TotalSupplyResponse) GetTotalSupply() *BigUInt {
	if m != nil {
		return m.TotalSupply
	}
	return nil
}

type BalanceOfRequest struct {
	Owner *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
}

func (m *BalanceOfRequest) Reset()                    { *m = BalanceOfRequest{} }
func (m *BalanceOfRequest) String() string            { return proto.CompactTextString(m) }
func (*BalanceOfRequest) ProtoMessage()               {}
func (*BalanceOfRequest) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{6} }

func (m *BalanceOfRequest) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

type BalanceOfResponse struct {
	Balance *BigUInt `protobuf:"bytes,1,opt,name=balance" json:"balance,omitempty"`
}

func (m *BalanceOfResponse) Reset()                    { *m = BalanceOfResponse{} }
func (m *BalanceOfResponse) String() string            { return proto.CompactTextString(m) }
func (*BalanceOfResponse) ProtoMessage()               {}
func (*BalanceOfResponse) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{7} }

func (m *BalanceOfResponse) GetBalance() *BigUInt {
	if m != nil {
		return m.Balance
	}
	return nil
}

type AllowanceRequest struct {
	Owner   *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Spender *types.Address `protobuf:"bytes,2,opt,name=spender" json:"spender,omitempty"`
}

func (m *AllowanceRequest) Reset()                    { *m = AllowanceRequest{} }
func (m *AllowanceRequest) String() string            { return proto.CompactTextString(m) }
func (*AllowanceRequest) ProtoMessage()               {}
func (*AllowanceRequest) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{8} }

func (m *AllowanceRequest) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *AllowanceRequest) GetSpender() *types.Address {
	if m != nil {
		return m.Spender
	}
	return nil
}

type AllowanceResponse struct {
	Remaining *BigUInt `protobuf:"bytes,1,opt,name=remaining" json:"remaining,omitempty"`
}

func (m *AllowanceResponse) Reset()                    { *m = AllowanceResponse{} }
func (m *AllowanceResponse) String() string            { return proto.CompactTextString(m) }
func (*AllowanceResponse) ProtoMessage()               {}
func (*AllowanceResponse) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{9} }

func (m *AllowanceResponse) GetRemaining() *BigUInt {
	if m != nil {
		return m.Remaining
	}
	return nil
}

// volatile
type ApproveRequest struct {
	Spender *types.Address `protobuf:"bytes,1,opt,name=spender" json:"spender,omitempty"`
	Amount  *BigUInt       `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *ApproveRequest) Reset()                    { *m = ApproveRequest{} }
func (m *ApproveRequest) String() string            { return proto.CompactTextString(m) }
func (*ApproveRequest) ProtoMessage()               {}
func (*ApproveRequest) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{10} }

func (m *ApproveRequest) GetSpender() *types.Address {
	if m != nil {
		return m.Spender
	}
	return nil
}

func (m *ApproveRequest) GetAmount() *BigUInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

type ApproveResponse struct {
}

func (m *ApproveResponse) Reset()                    { *m = ApproveResponse{} }
func (m *ApproveResponse) String() string            { return proto.CompactTextString(m) }
func (*ApproveResponse) ProtoMessage()               {}
func (*ApproveResponse) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{11} }

type TransferRequest struct {
	To     *types.Address `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Amount *BigUInt       `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *TransferRequest) Reset()                    { *m = TransferRequest{} }
func (m *TransferRequest) String() string            { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()               {}
func (*TransferRequest) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{12} }

func (m *TransferRequest) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransferRequest) GetAmount() *BigUInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

type TransferResponse struct {
}

func (m *TransferResponse) Reset()                    { *m = TransferResponse{} }
func (m *TransferResponse) String() string            { return proto.CompactTextString(m) }
func (*TransferResponse) ProtoMessage()               {}
func (*TransferResponse) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{13} }

type TransferFromRequest struct {
	From   *types.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To     *types.Address `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Amount *BigUInt       `protobuf:"bytes,3,opt,name=amount" json:"amount,omitempty"`
}

func (m *TransferFromRequest) Reset()                    { *m = TransferFromRequest{} }
func (m *TransferFromRequest) String() string            { return proto.CompactTextString(m) }
func (*TransferFromRequest) ProtoMessage()               {}
func (*TransferFromRequest) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{14} }

func (m *TransferFromRequest) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransferFromRequest) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransferFromRequest) GetAmount() *BigUInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

type TransferFromResponse struct {
}

func (m *TransferFromResponse) Reset()                    { *m = TransferFromResponse{} }
func (m *TransferFromResponse) String() string            { return proto.CompactTextString(m) }
func (*TransferFromResponse) ProtoMessage()               {}
func (*TransferFromResponse) Descriptor() ([]byte, []int) { return fileDescriptorCoin, []int{15} }

func init() {
	proto.RegisterType((*BigUInt)(nil), "BigUInt")
	proto.RegisterType((*Economy)(nil), "Economy")
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterType((*InitRequest)(nil), "InitRequest")
	proto.RegisterType((*TotalSupplyRequest)(nil), "TotalSupplyRequest")
	proto.RegisterType((*TotalSupplyResponse)(nil), "TotalSupplyResponse")
	proto.RegisterType((*BalanceOfRequest)(nil), "BalanceOfRequest")
	proto.RegisterType((*BalanceOfResponse)(nil), "BalanceOfResponse")
	proto.RegisterType((*AllowanceRequest)(nil), "AllowanceRequest")
	proto.RegisterType((*AllowanceResponse)(nil), "AllowanceResponse")
	proto.RegisterType((*ApproveRequest)(nil), "ApproveRequest")
	proto.RegisterType((*ApproveResponse)(nil), "ApproveResponse")
	proto.RegisterType((*TransferRequest)(nil), "TransferRequest")
	proto.RegisterType((*TransferResponse)(nil), "TransferResponse")
	proto.RegisterType((*TransferFromRequest)(nil), "TransferFromRequest")
	proto.RegisterType((*TransferFromResponse)(nil), "TransferFromResponse")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/builtin/plugins/coin/coin.proto", fileDescriptorCoin)
}

var fileDescriptorCoin = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xd1, 0x6b, 0xdb, 0x30,
	0x10, 0xc6, 0x71, 0xba, 0x36, 0xdd, 0xa5, 0xac, 0x89, 0x1a, 0x46, 0x18, 0x63, 0x0b, 0x62, 0x8c,
	0xc1, 0x58, 0x3c, 0x5a, 0xd8, 0x1e, 0x06, 0x83, 0x04, 0x36, 0xe8, 0x43, 0x19, 0x78, 0x5d, 0x5f,
	0x87, 0xec, 0x28, 0x9e, 0x98, 0xac, 0xd3, 0x24, 0xb9, 0x21, 0xff, 0xfd, 0xb0, 0x65, 0x3b, 0xee,
	0x4c, 0xd6, 0xf4, 0x45, 0x70, 0xf7, 0xe9, 0xbe, 0xef, 0x77, 0x16, 0x86, 0xcf, 0xa9, 0x70, 0xbf,
	0xf2, 0x78, 0x96, 0x60, 0x16, 0x4a, 0xc4, 0x4c, 0x71, 0xb7, 0x46, 0xf3, 0x3b, 0x4c, 0xf1, 0x5d,
	0x51, 0x86, 0x71, 0x2e, 0xa4, 0x13, 0x2a, 0xd4, 0x32, 0x4f, 0x85, 0xb2, 0x61, 0x82, 0x42, 0x95,
	0xc7, 0x4c, 0x1b, 0x74, 0xf8, 0xec, 0xfd, 0x3d, 0xf3, 0x6e, 0xa3, 0xb9, 0xf5, 0xa7, 0x9f, 0xa0,
	0x2f, 0xa1, 0xbf, 0x10, 0xe9, 0x8f, 0x4b, 0xe5, 0xc8, 0x18, 0x0e, 0x6f, 0x99, 0xcc, 0xf9, 0x24,
	0x98, 0x06, 0x6f, 0x4e, 0x22, 0x5f, 0xd0, 0x0f, 0xd0, 0xff, 0x92, 0xa0, 0xc2, 0x6c, 0x43, 0xde,
	0xc2, 0x89, 0x43, 0xc7, 0xe4, 0x4f, 0x9b, 0x6b, 0x2d, 0x37, 0xe5, 0xbd, 0xc1, 0xf9, 0xf1, 0xac,
	0x32, 0x88, 0x06, 0xa5, 0xfa, 0xbd, 0x14, 0xe9, 0x15, 0xf4, 0xe7, 0x49, 0x82, 0xb9, 0x72, 0xe4,
	0x05, 0x1c, 0xe2, 0x5a, 0x71, 0xd3, 0x0c, 0xcc, 0x97, 0x4b, 0xc3, 0xad, 0x8d, 0x7c, 0x9b, 0x50,
	0xe8, 0xc7, 0x4c, 0x32, 0x95, 0xf0, 0x49, 0xef, 0x1f, 0xcb, 0x5a, 0xa0, 0x17, 0x30, 0xb8, 0x54,
	0xc2, 0x45, 0xfc, 0x4f, 0xce, 0xad, 0x23, 0xaf, 0xe0, 0x98, 0x79, 0x77, 0x3b, 0x09, 0xa6, 0x07,
	0xde, 0xd5, 0x37, 0xa2, 0x46, 0xa1, 0x63, 0x20, 0xd7, 0x5b, 0xa4, 0x6a, 0x96, 0x2e, 0xe0, 0xec,
	0x4e, 0xd7, 0x6a, 0x54, 0x96, 0x3f, 0x6c, 0xbb, 0x73, 0x18, 0x2e, 0x3c, 0xd9, 0xb7, 0x55, 0xcd,
	0x74, 0xcf, 0x9a, 0xf4, 0x23, 0x8c, 0x5a, 0x33, 0x55, 0x6a, 0x6b, 0xf7, 0x60, 0xd7, 0xee, 0x37,
	0x30, 0x9c, 0x4b, 0x89, 0xeb, 0xa2, 0xd8, 0x33, 0xac, 0xf0, 0xb5, 0x9a, 0xab, 0x25, 0x37, 0xcd,
	0x37, 0xad, 0x6f, 0xd4, 0x02, 0xfd, 0x04, 0xa3, 0x96, 0x6f, 0x05, 0xf4, 0x1a, 0x1e, 0x1b, 0x9e,
	0x31, 0xa1, 0x84, 0x4a, 0x3b, 0x48, 0x5b, 0x89, 0xde, 0xc0, 0x93, 0xb9, 0xd6, 0x06, 0x6f, 0x1b,
	0xa4, 0x56, 0x64, 0xb0, 0x23, 0x92, 0x4c, 0xe1, 0x88, 0x65, 0xc5, 0xe3, 0x74, 0x5e, 0xba, 0xea,
	0xd3, 0x11, 0x9c, 0x36, 0xbe, 0x1e, 0x89, 0x5e, 0xc1, 0xe9, 0xb5, 0x61, 0xca, 0xae, 0xb8, 0xa9,
	0xb3, 0x26, 0xd0, 0x73, 0xd8, 0x89, 0xe9, 0x39, 0xdc, 0x23, 0x81, 0xc0, 0x70, 0x6b, 0x57, 0x45,
	0x20, 0x9c, 0xd5, 0xbd, 0xaf, 0x06, 0xb3, 0x3a, 0xe6, 0x39, 0x3c, 0x5a, 0x19, 0xcc, 0x3a, 0x41,
	0x65, 0xb7, 0x82, 0xe8, 0xfd, 0x17, 0xe2, 0x60, 0x07, 0xc4, 0x53, 0x18, 0xdf, 0x0d, 0xf4, 0x20,
	0xf1, 0x51, 0xf9, 0x5b, 0x5e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x15, 0x22, 0xb5, 0x3e, 0x0a,
	0x04, 0x00, 0x00,
}
