// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/vm/vm.proto

package vm

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type VMType int32

const (
	VMType_PLUGIN VMType = 0
	VMType_EVM    VMType = 1
)

var VMType_name = map[int32]string{
	0: "PLUGIN",
	1: "EVM",
}
var VMType_value = map[string]int32{
	"PLUGIN": 0,
	"EVM":    1,
}

func (x VMType) String() string {
	return proto.EnumName(VMType_name, int32(x))
}
func (VMType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_vm_ccd72d2e1dbae237, []int{0}
}

type MessageTx struct {
	To                   *types.Address `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	From                 *types.Address `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Data                 []byte         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageTx) Reset()         { *m = MessageTx{} }
func (m *MessageTx) String() string { return proto.CompactTextString(m) }
func (*MessageTx) ProtoMessage()    {}
func (*MessageTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_ccd72d2e1dbae237, []int{0}
}
func (m *MessageTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageTx.Unmarshal(m, b)
}
func (m *MessageTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageTx.Marshal(b, m, deterministic)
}
func (dst *MessageTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageTx.Merge(dst, src)
}
func (m *MessageTx) XXX_Size() int {
	return xxx_messageInfo_MessageTx.Size(m)
}
func (m *MessageTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageTx.DiscardUnknown(m)
}

var xxx_messageInfo_MessageTx proto.InternalMessageInfo

func (m *MessageTx) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MessageTx) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *MessageTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeployTx struct {
	VmType               VMType   `protobuf:"varint,1,opt,name=vm_type,json=vmType,proto3,enum=VMType" json:"vm_type,omitempty"`
	Code                 []byte   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployTx) Reset()         { *m = DeployTx{} }
func (m *DeployTx) String() string { return proto.CompactTextString(m) }
func (*DeployTx) ProtoMessage()    {}
func (*DeployTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_ccd72d2e1dbae237, []int{1}
}
func (m *DeployTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployTx.Unmarshal(m, b)
}
func (m *DeployTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployTx.Marshal(b, m, deterministic)
}
func (dst *DeployTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployTx.Merge(dst, src)
}
func (m *DeployTx) XXX_Size() int {
	return xxx_messageInfo_DeployTx.Size(m)
}
func (m *DeployTx) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployTx.DiscardUnknown(m)
}

var xxx_messageInfo_DeployTx proto.InternalMessageInfo

func (m *DeployTx) GetVmType() VMType {
	if m != nil {
		return m.VmType
	}
	return VMType_PLUGIN
}

func (m *DeployTx) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *DeployTx) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CallTx struct {
	VmType               VMType   `protobuf:"varint,1,opt,name=vm_type,json=vmType,proto3,enum=VMType" json:"vm_type,omitempty"`
	Input                []byte   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallTx) Reset()         { *m = CallTx{} }
func (m *CallTx) String() string { return proto.CompactTextString(m) }
func (*CallTx) ProtoMessage()    {}
func (*CallTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_ccd72d2e1dbae237, []int{2}
}
func (m *CallTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallTx.Unmarshal(m, b)
}
func (m *CallTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallTx.Marshal(b, m, deterministic)
}
func (dst *CallTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallTx.Merge(dst, src)
}
func (m *CallTx) XXX_Size() int {
	return xxx_messageInfo_CallTx.Size(m)
}
func (m *CallTx) XXX_DiscardUnknown() {
	xxx_messageInfo_CallTx.DiscardUnknown(m)
}

var xxx_messageInfo_CallTx proto.InternalMessageInfo

func (m *CallTx) GetVmType() VMType {
	if m != nil {
		return m.VmType
	}
	return VMType_PLUGIN
}

func (m *CallTx) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type DeployResponse struct {
	Contract             *types.Address `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	Output               []byte         `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_ccd72d2e1dbae237, []int{3}
}
func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (dst *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(dst, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetContract() *types.Address {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *DeployResponse) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

type DeployResponseData struct {
	TxHash               []byte   `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Bytecode             []byte   `protobuf:"bytes,2,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployResponseData) Reset()         { *m = DeployResponseData{} }
func (m *DeployResponseData) String() string { return proto.CompactTextString(m) }
func (*DeployResponseData) ProtoMessage()    {}
func (*DeployResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_ccd72d2e1dbae237, []int{4}
}
func (m *DeployResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponseData.Unmarshal(m, b)
}
func (m *DeployResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponseData.Marshal(b, m, deterministic)
}
func (dst *DeployResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponseData.Merge(dst, src)
}
func (m *DeployResponseData) XXX_Size() int {
	return xxx_messageInfo_DeployResponseData.Size(m)
}
func (m *DeployResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponseData proto.InternalMessageInfo

func (m *DeployResponseData) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *DeployResponseData) GetBytecode() []byte {
	if m != nil {
		return m.Bytecode
	}
	return nil
}

type TxHashList struct {
	TxHash               [][]byte `protobuf:"bytes,1,rep,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxHashList) Reset()         { *m = TxHashList{} }
func (m *TxHashList) String() string { return proto.CompactTextString(m) }
func (*TxHashList) ProtoMessage()    {}
func (*TxHashList) Descriptor() ([]byte, []int) {
	return fileDescriptor_vm_ccd72d2e1dbae237, []int{5}
}
func (m *TxHashList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxHashList.Unmarshal(m, b)
}
func (m *TxHashList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxHashList.Marshal(b, m, deterministic)
}
func (dst *TxHashList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxHashList.Merge(dst, src)
}
func (m *TxHashList) XXX_Size() int {
	return xxx_messageInfo_TxHashList.Size(m)
}
func (m *TxHashList) XXX_DiscardUnknown() {
	xxx_messageInfo_TxHashList.DiscardUnknown(m)
}

var xxx_messageInfo_TxHashList proto.InternalMessageInfo

func (m *TxHashList) GetTxHash() [][]byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageTx)(nil), "MessageTx")
	proto.RegisterType((*DeployTx)(nil), "DeployTx")
	proto.RegisterType((*CallTx)(nil), "CallTx")
	proto.RegisterType((*DeployResponse)(nil), "DeployResponse")
	proto.RegisterType((*DeployResponseData)(nil), "DeployResponseData")
	proto.RegisterType((*TxHashList)(nil), "TxHashList")
	proto.RegisterEnum("VMType", VMType_name, VMType_value)
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/vm/vm.proto", fileDescriptor_vm_ccd72d2e1dbae237)
}

var fileDescriptor_vm_ccd72d2e1dbae237 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x71, 0x6b, 0xe2, 0x40,
	0x10, 0xc5, 0x2f, 0xea, 0x25, 0x71, 0x4e, 0x44, 0x96, 0xe3, 0x2e, 0xc8, 0x1d, 0x48, 0xb8, 0x03,
	0x11, 0x1a, 0x8b, 0xfd, 0x02, 0x2d, 0xb5, 0xb4, 0x82, 0x4a, 0x09, 0xa9, 0xfd, 0x53, 0xd6, 0x64,
	0x6b, 0xa4, 0x49, 0x26, 0x64, 0x47, 0x9b, 0x7c, 0xfb, 0x92, 0x8d, 0x68, 0x6d, 0xff, 0x68, 0x21,
	0x64, 0xdf, 0x9b, 0x99, 0xfd, 0xed, 0x3e, 0x16, 0x06, 0xeb, 0x0d, 0x85, 0xdb, 0x95, 0xe3, 0x63,
	0x3c, 0x8c, 0x10, 0xe3, 0x44, 0xd0, 0x0b, 0x66, 0xcf, 0xc3, 0x35, 0x9e, 0x95, 0x76, 0xb8, 0x2b,
	0x3f, 0x27, 0xcd, 0x90, 0xb0, 0x7b, 0xfe, 0xc9, 0x2c, 0x15, 0xa9, 0x90, 0xd5, 0xbf, 0xda, 0x61,
	0x3f, 0x42, 0x73, 0x26, 0xa4, 0xe4, 0x6b, 0xe1, 0xe5, 0xcc, 0x82, 0x1a, 0xa1, 0xa5, 0xf5, 0xb4,
	0xfe, 0x8f, 0x91, 0xe9, 0x5c, 0x05, 0x41, 0x26, 0xa4, 0x74, 0x6b, 0x84, 0xec, 0x0f, 0x34, 0x9e,
	0x32, 0x8c, 0xad, 0xda, 0xbb, 0x9e, 0xaa, 0x32, 0x06, 0x8d, 0x80, 0x13, 0xb7, 0xea, 0x3d, 0xad,
	0xdf, 0x72, 0x95, 0xb6, 0x3d, 0x30, 0xc7, 0x22, 0x8d, 0xb0, 0xf0, 0x72, 0xd6, 0x03, 0x63, 0x17,
	0x2f, 0xcb, 0x63, 0x15, 0xbc, 0x3d, 0x32, 0x9c, 0xc5, 0xcc, 0x2b, 0x52, 0xe1, 0xea, 0xbb, 0xb8,
	0x5c, 0x4b, 0x82, 0x8f, 0x81, 0x50, 0xfc, 0x96, 0xab, 0x74, 0x59, 0x4b, 0x78, 0x2c, 0x14, 0xb5,
	0xe9, 0x2a, 0x6d, 0x5f, 0x82, 0x7e, 0xcd, 0xa3, 0xe8, 0x4b, 0xcc, 0x9f, 0xf0, 0x7d, 0x93, 0xa4,
	0x5b, 0xda, 0x43, 0x2b, 0x63, 0xcf, 0xa1, 0x5d, 0xdd, 0xcb, 0x15, 0x32, 0xc5, 0x44, 0x0a, 0xf6,
	0x0f, 0x4c, 0x1f, 0x13, 0xca, 0xb8, 0x4f, 0x1f, 0xb2, 0x1f, 0x3a, 0xec, 0x17, 0xe8, 0xb8, 0xa5,
	0x23, 0x6e, 0xef, 0xec, 0x09, 0xb0, 0x53, 0xde, 0x98, 0x13, 0x67, 0xbf, 0xc1, 0xa0, 0x7c, 0x19,
	0x72, 0x19, 0x2a, 0x64, 0xcb, 0xd5, 0x29, 0xbf, 0xe3, 0x32, 0x64, 0x5d, 0x30, 0x57, 0x05, 0x89,
	0x37, 0x61, 0x0f, 0xde, 0xfe, 0x0f, 0xe0, 0xa9, 0xa9, 0xe9, 0x46, 0xd2, 0x29, 0xa2, 0x7e, 0x44,
	0x0c, 0xfe, 0x82, 0x5e, 0x25, 0x65, 0x00, 0xfa, 0xfd, 0xf4, 0xe1, 0x76, 0x32, 0xef, 0x7c, 0x63,
	0x06, 0xd4, 0x6f, 0x16, 0xb3, 0x8e, 0xb6, 0xd2, 0xd5, 0xc3, 0x5e, 0xbc, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xb3, 0x9d, 0x47, 0x38, 0x02, 0x00, 0x00,
}
