// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/builtin/types/dposv2/dpos.proto

/*
Package dpos is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/go-loom/builtin/types/dposv2/dpos.proto

It has these top-level messages:
	ParamsV2
	StateV2
	VoterV2
	CandidateV2
	CandidateListV2
	VoteV2
	VoteListV2
	DPOSInitRequestV2
	DelegateRequestV2
	DelegateResponseV2
	RedelegateRequestV2
	RedelegateResponseV2
	UnbondRequestV2
	UnbondResponseV2
	RegisterCandidateRequestV2
	RegisterCandidateResponseV2
	UnregisterCandidateRequestV2
	UnregisterCandidateResponseV2
	VoteRequestV2
	VoteResponseV2
	ElectRequestV2
	ElectResponseV2
	ListValidatorsRequestV2
	ListValidatorsResponseV2
	ListCandidateRequestV2
	ListCandidateResponseV2
*/
package dpos

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ParamsV2 struct {
	ValidatorCount      uint64         `protobuf:"varint,1,opt,name=validator_count,json=validatorCount,proto3" json:"validator_count,omitempty"`
	VoteAllocation      uint64         `protobuf:"varint,2,opt,name=vote_allocation,json=voteAllocation,proto3" json:"vote_allocation,omitempty"`
	ElectionCycleLength int64          `protobuf:"varint,3,opt,name=election_cycle_length,json=electionCycleLength,proto3" json:"election_cycle_length,omitempty"`
	MinPowerFraction    uint64         `protobuf:"varint,4,opt,name=min_power_fraction,json=minPowerFraction,proto3" json:"min_power_fraction,omitempty"`
	CoinContractAddress *types.Address `protobuf:"bytes,5,opt,name=coin_contract_address,json=coinContractAddress" json:"coin_contract_address,omitempty"`
	ValidatorSalary     uint64         `protobuf:"varint,6,opt,name=validator_salary,json=validatorSalary,proto3" json:"validator_salary,omitempty"`
}

func (m *ParamsV2) Reset()                    { *m = ParamsV2{} }
func (m *ParamsV2) String() string            { return proto.CompactTextString(m) }
func (*ParamsV2) ProtoMessage()               {}
func (*ParamsV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{0} }

func (m *ParamsV2) GetValidatorCount() uint64 {
	if m != nil {
		return m.ValidatorCount
	}
	return 0
}

func (m *ParamsV2) GetVoteAllocation() uint64 {
	if m != nil {
		return m.VoteAllocation
	}
	return 0
}

func (m *ParamsV2) GetElectionCycleLength() int64 {
	if m != nil {
		return m.ElectionCycleLength
	}
	return 0
}

func (m *ParamsV2) GetMinPowerFraction() uint64 {
	if m != nil {
		return m.MinPowerFraction
	}
	return 0
}

func (m *ParamsV2) GetCoinContractAddress() *types.Address {
	if m != nil {
		return m.CoinContractAddress
	}
	return nil
}

func (m *ParamsV2) GetValidatorSalary() uint64 {
	if m != nil {
		return m.ValidatorSalary
	}
	return 0
}

type StateV2 struct {
	Params           *ParamsV2          `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	Validators       []*types.Validator `protobuf:"bytes,2,rep,name=validators" json:"validators,omitempty"`
	LastElectionTime int64              `protobuf:"varint,3,opt,name=last_election_time,json=lastElectionTime,proto3" json:"last_election_time,omitempty"`
}

func (m *StateV2) Reset()                    { *m = StateV2{} }
func (m *StateV2) String() string            { return proto.CompactTextString(m) }
func (*StateV2) ProtoMessage()               {}
func (*StateV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{1} }

func (m *StateV2) GetParams() *ParamsV2 {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *StateV2) GetValidators() []*types.Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *StateV2) GetLastElectionTime() int64 {
	if m != nil {
		return m.LastElectionTime
	}
	return 0
}

type VoterV2 struct {
	Address            *types.Address   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Balance            uint64           `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ProxyAddress       *types.Address   `protobuf:"bytes,3,opt,name=proxy_address,json=proxyAddress" json:"proxy_address,omitempty"`
	PrincipalAddresses []*types.Address `protobuf:"bytes,4,rep,name=principal_addresses,json=principalAddresses" json:"principal_addresses,omitempty"`
}

func (m *VoterV2) Reset()                    { *m = VoterV2{} }
func (m *VoterV2) String() string            { return proto.CompactTextString(m) }
func (*VoterV2) ProtoMessage()               {}
func (*VoterV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{2} }

func (m *VoterV2) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *VoterV2) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *VoterV2) GetProxyAddress() *types.Address {
	if m != nil {
		return m.ProxyAddress
	}
	return nil
}

func (m *VoterV2) GetPrincipalAddresses() []*types.Address {
	if m != nil {
		return m.PrincipalAddresses
	}
	return nil
}

type CandidateV2 struct {
	Address *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	PubKey  []byte         `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (m *CandidateV2) Reset()                    { *m = CandidateV2{} }
func (m *CandidateV2) String() string            { return proto.CompactTextString(m) }
func (*CandidateV2) ProtoMessage()               {}
func (*CandidateV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{3} }

func (m *CandidateV2) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *CandidateV2) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type CandidateListV2 struct {
	Candidates []*CandidateV2 `protobuf:"bytes,1,rep,name=candidates" json:"candidates,omitempty"`
}

func (m *CandidateListV2) Reset()                    { *m = CandidateListV2{} }
func (m *CandidateListV2) String() string            { return proto.CompactTextString(m) }
func (*CandidateListV2) ProtoMessage()               {}
func (*CandidateListV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{4} }

func (m *CandidateListV2) GetCandidates() []*CandidateV2 {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type VoteV2 struct {
	VoterAddress     *types.Address `protobuf:"bytes,1,opt,name=voter_address,json=voterAddress" json:"voter_address,omitempty"`
	CandidateAddress *types.Address `protobuf:"bytes,2,opt,name=candidate_address,json=candidateAddress" json:"candidate_address,omitempty"`
	Amount           uint64         `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *VoteV2) Reset()                    { *m = VoteV2{} }
func (m *VoteV2) String() string            { return proto.CompactTextString(m) }
func (*VoteV2) ProtoMessage()               {}
func (*VoteV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{5} }

func (m *VoteV2) GetVoterAddress() *types.Address {
	if m != nil {
		return m.VoterAddress
	}
	return nil
}

func (m *VoteV2) GetCandidateAddress() *types.Address {
	if m != nil {
		return m.CandidateAddress
	}
	return nil
}

func (m *VoteV2) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type VoteListV2 struct {
	Votes []*VoteV2 `protobuf:"bytes,1,rep,name=votes" json:"votes,omitempty"`
}

func (m *VoteListV2) Reset()                    { *m = VoteListV2{} }
func (m *VoteListV2) String() string            { return proto.CompactTextString(m) }
func (*VoteListV2) ProtoMessage()               {}
func (*VoteListV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{6} }

func (m *VoteListV2) GetVotes() []*VoteV2 {
	if m != nil {
		return m.Votes
	}
	return nil
}

type DPOSInitRequestV2 struct {
	Params     *ParamsV2          `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	Validators []*types.Validator `protobuf:"bytes,2,rep,name=validators" json:"validators,omitempty"`
}

func (m *DPOSInitRequestV2) Reset()                    { *m = DPOSInitRequestV2{} }
func (m *DPOSInitRequestV2) String() string            { return proto.CompactTextString(m) }
func (*DPOSInitRequestV2) ProtoMessage()               {}
func (*DPOSInitRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{7} }

func (m *DPOSInitRequestV2) GetParams() *ParamsV2 {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *DPOSInitRequestV2) GetValidators() []*types.Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type DelegateRequestV2 struct {
	ValidatorAddress *types.Address `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress" json:"validator_address,omitempty"`
	Amount           int64          `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *DelegateRequestV2) Reset()                    { *m = DelegateRequestV2{} }
func (m *DelegateRequestV2) String() string            { return proto.CompactTextString(m) }
func (*DelegateRequestV2) ProtoMessage()               {}
func (*DelegateRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{8} }

func (m *DelegateRequestV2) GetValidatorAddress() *types.Address {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *DelegateRequestV2) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DelegateResponseV2 struct {
}

func (m *DelegateResponseV2) Reset()                    { *m = DelegateResponseV2{} }
func (m *DelegateResponseV2) String() string            { return proto.CompactTextString(m) }
func (*DelegateResponseV2) ProtoMessage()               {}
func (*DelegateResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{9} }

type RedelegateRequestV2 struct {
	ValidatorAddress *types.Address `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress" json:"validator_address,omitempty"`
	Amount           int64          `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *RedelegateRequestV2) Reset()                    { *m = RedelegateRequestV2{} }
func (m *RedelegateRequestV2) String() string            { return proto.CompactTextString(m) }
func (*RedelegateRequestV2) ProtoMessage()               {}
func (*RedelegateRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{10} }

func (m *RedelegateRequestV2) GetValidatorAddress() *types.Address {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *RedelegateRequestV2) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RedelegateResponseV2 struct {
}

func (m *RedelegateResponseV2) Reset()                    { *m = RedelegateResponseV2{} }
func (m *RedelegateResponseV2) String() string            { return proto.CompactTextString(m) }
func (*RedelegateResponseV2) ProtoMessage()               {}
func (*RedelegateResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{11} }

type UnbondRequestV2 struct {
	ValidatorAddress *types.Address `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress" json:"validator_address,omitempty"`
	Amount           int64          `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *UnbondRequestV2) Reset()                    { *m = UnbondRequestV2{} }
func (m *UnbondRequestV2) String() string            { return proto.CompactTextString(m) }
func (*UnbondRequestV2) ProtoMessage()               {}
func (*UnbondRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{12} }

func (m *UnbondRequestV2) GetValidatorAddress() *types.Address {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *UnbondRequestV2) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UnbondResponseV2 struct {
}

func (m *UnbondResponseV2) Reset()                    { *m = UnbondResponseV2{} }
func (m *UnbondResponseV2) String() string            { return proto.CompactTextString(m) }
func (*UnbondResponseV2) ProtoMessage()               {}
func (*UnbondResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{13} }

type RegisterCandidateRequestV2 struct {
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (m *RegisterCandidateRequestV2) Reset()                    { *m = RegisterCandidateRequestV2{} }
func (m *RegisterCandidateRequestV2) String() string            { return proto.CompactTextString(m) }
func (*RegisterCandidateRequestV2) ProtoMessage()               {}
func (*RegisterCandidateRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{14} }

func (m *RegisterCandidateRequestV2) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type RegisterCandidateResponseV2 struct {
}

func (m *RegisterCandidateResponseV2) Reset()                    { *m = RegisterCandidateResponseV2{} }
func (m *RegisterCandidateResponseV2) String() string            { return proto.CompactTextString(m) }
func (*RegisterCandidateResponseV2) ProtoMessage()               {}
func (*RegisterCandidateResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{15} }

type UnregisterCandidateRequestV2 struct {
}

func (m *UnregisterCandidateRequestV2) Reset()         { *m = UnregisterCandidateRequestV2{} }
func (m *UnregisterCandidateRequestV2) String() string { return proto.CompactTextString(m) }
func (*UnregisterCandidateRequestV2) ProtoMessage()    {}
func (*UnregisterCandidateRequestV2) Descriptor() ([]byte, []int) {
	return fileDescriptorDpos, []int{16}
}

type UnregisterCandidateResponseV2 struct {
}

func (m *UnregisterCandidateResponseV2) Reset()         { *m = UnregisterCandidateResponseV2{} }
func (m *UnregisterCandidateResponseV2) String() string { return proto.CompactTextString(m) }
func (*UnregisterCandidateResponseV2) ProtoMessage()    {}
func (*UnregisterCandidateResponseV2) Descriptor() ([]byte, []int) {
	return fileDescriptorDpos, []int{17}
}

type VoteRequestV2 struct {
	CandidateAddress *types.Address `protobuf:"bytes,1,opt,name=candidate_address,json=candidateAddress" json:"candidate_address,omitempty"`
	Amount           int64          `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *VoteRequestV2) Reset()                    { *m = VoteRequestV2{} }
func (m *VoteRequestV2) String() string            { return proto.CompactTextString(m) }
func (*VoteRequestV2) ProtoMessage()               {}
func (*VoteRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{18} }

func (m *VoteRequestV2) GetCandidateAddress() *types.Address {
	if m != nil {
		return m.CandidateAddress
	}
	return nil
}

func (m *VoteRequestV2) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type VoteResponseV2 struct {
}

func (m *VoteResponseV2) Reset()                    { *m = VoteResponseV2{} }
func (m *VoteResponseV2) String() string            { return proto.CompactTextString(m) }
func (*VoteResponseV2) ProtoMessage()               {}
func (*VoteResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{19} }

type ElectRequestV2 struct {
}

func (m *ElectRequestV2) Reset()                    { *m = ElectRequestV2{} }
func (m *ElectRequestV2) String() string            { return proto.CompactTextString(m) }
func (*ElectRequestV2) ProtoMessage()               {}
func (*ElectRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{20} }

type ElectResponseV2 struct {
}

func (m *ElectResponseV2) Reset()                    { *m = ElectResponseV2{} }
func (m *ElectResponseV2) String() string            { return proto.CompactTextString(m) }
func (*ElectResponseV2) ProtoMessage()               {}
func (*ElectResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{21} }

type ListValidatorsRequestV2 struct {
}

func (m *ListValidatorsRequestV2) Reset()                    { *m = ListValidatorsRequestV2{} }
func (m *ListValidatorsRequestV2) String() string            { return proto.CompactTextString(m) }
func (*ListValidatorsRequestV2) ProtoMessage()               {}
func (*ListValidatorsRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{22} }

type ListValidatorsResponseV2 struct {
	Validators []*types.Validator `protobuf:"bytes,1,rep,name=validators" json:"validators,omitempty"`
}

func (m *ListValidatorsResponseV2) Reset()                    { *m = ListValidatorsResponseV2{} }
func (m *ListValidatorsResponseV2) String() string            { return proto.CompactTextString(m) }
func (*ListValidatorsResponseV2) ProtoMessage()               {}
func (*ListValidatorsResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{23} }

func (m *ListValidatorsResponseV2) GetValidators() []*types.Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type ListCandidateRequestV2 struct {
}

func (m *ListCandidateRequestV2) Reset()                    { *m = ListCandidateRequestV2{} }
func (m *ListCandidateRequestV2) String() string            { return proto.CompactTextString(m) }
func (*ListCandidateRequestV2) ProtoMessage()               {}
func (*ListCandidateRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{24} }

type ListCandidateResponseV2 struct {
	Candidates []*CandidateV2 `protobuf:"bytes,1,rep,name=candidates" json:"candidates,omitempty"`
}

func (m *ListCandidateResponseV2) Reset()                    { *m = ListCandidateResponseV2{} }
func (m *ListCandidateResponseV2) String() string            { return proto.CompactTextString(m) }
func (*ListCandidateResponseV2) ProtoMessage()               {}
func (*ListCandidateResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDpos, []int{25} }

func (m *ListCandidateResponseV2) GetCandidates() []*CandidateV2 {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func init() {
	proto.RegisterType((*ParamsV2)(nil), "ParamsV2")
	proto.RegisterType((*StateV2)(nil), "StateV2")
	proto.RegisterType((*VoterV2)(nil), "VoterV2")
	proto.RegisterType((*CandidateV2)(nil), "CandidateV2")
	proto.RegisterType((*CandidateListV2)(nil), "CandidateListV2")
	proto.RegisterType((*VoteV2)(nil), "VoteV2")
	proto.RegisterType((*VoteListV2)(nil), "VoteListV2")
	proto.RegisterType((*DPOSInitRequestV2)(nil), "DPOSInitRequestV2")
	proto.RegisterType((*DelegateRequestV2)(nil), "DelegateRequestV2")
	proto.RegisterType((*DelegateResponseV2)(nil), "DelegateResponseV2")
	proto.RegisterType((*RedelegateRequestV2)(nil), "RedelegateRequestV2")
	proto.RegisterType((*RedelegateResponseV2)(nil), "RedelegateResponseV2")
	proto.RegisterType((*UnbondRequestV2)(nil), "UnbondRequestV2")
	proto.RegisterType((*UnbondResponseV2)(nil), "UnbondResponseV2")
	proto.RegisterType((*RegisterCandidateRequestV2)(nil), "RegisterCandidateRequestV2")
	proto.RegisterType((*RegisterCandidateResponseV2)(nil), "RegisterCandidateResponseV2")
	proto.RegisterType((*UnregisterCandidateRequestV2)(nil), "UnregisterCandidateRequestV2")
	proto.RegisterType((*UnregisterCandidateResponseV2)(nil), "UnregisterCandidateResponseV2")
	proto.RegisterType((*VoteRequestV2)(nil), "VoteRequestV2")
	proto.RegisterType((*VoteResponseV2)(nil), "VoteResponseV2")
	proto.RegisterType((*ElectRequestV2)(nil), "ElectRequestV2")
	proto.RegisterType((*ElectResponseV2)(nil), "ElectResponseV2")
	proto.RegisterType((*ListValidatorsRequestV2)(nil), "ListValidatorsRequestV2")
	proto.RegisterType((*ListValidatorsResponseV2)(nil), "ListValidatorsResponseV2")
	proto.RegisterType((*ListCandidateRequestV2)(nil), "ListCandidateRequestV2")
	proto.RegisterType((*ListCandidateResponseV2)(nil), "ListCandidateResponseV2")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/builtin/types/dposv2/dpos.proto", fileDescriptorDpos)
}

var fileDescriptorDpos = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0x36, 0x29, 0x93, 0xb4, 0x49, 0x9c, 0x7e, 0x98, 0x42, 0x21, 0xf8, 0x42, 0x80,
	0x36, 0x41, 0x46, 0x3d, 0x20, 0x21, 0x50, 0x15, 0x28, 0x02, 0x2a, 0x51, 0xb9, 0xd4, 0x47, 0xcc,
	0xda, 0x5e, 0x52, 0xab, 0xf6, 0xae, 0xb1, 0x37, 0x2d, 0xf9, 0x03, 0xfc, 0x15, 0xce, 0xfc, 0x43,
	0xb4, 0x1b, 0xef, 0x3a, 0x4d, 0x53, 0xa0, 0x12, 0xbd, 0x24, 0xd9, 0x79, 0x33, 0xf3, 0x66, 0x9e,
	0xdf, 0x3a, 0xf0, 0x72, 0x18, 0xb2, 0x93, 0x91, 0xd7, 0xf3, 0x69, 0xdc, 0x8f, 0x28, 0x8d, 0x09,
	0x66, 0xe7, 0x34, 0x3d, 0xed, 0x0f, 0xe9, 0x0e, 0x3f, 0xf6, 0xbd, 0x51, 0x18, 0xb1, 0x90, 0xf4,
	0xd9, 0x38, 0xc1, 0x59, 0x3f, 0x48, 0x68, 0x76, 0x66, 0x89, 0xaf, 0x5e, 0x92, 0x52, 0x46, 0x37,
	0x9f, 0xfe, 0xa5, 0x7e, 0x52, 0x27, 0x3e, 0x27, 0x15, 0xe6, 0xcf, 0x12, 0x2c, 0x1d, 0xa2, 0x14,
	0xc5, 0x99, 0x63, 0xe9, 0x0f, 0xa1, 0x71, 0x86, 0xa2, 0x30, 0x40, 0x8c, 0xa6, 0xae, 0x4f, 0x47,
	0x84, 0x19, 0x5a, 0x47, 0xeb, 0x2e, 0xd8, 0x2b, 0x2a, 0x3c, 0xe0, 0x51, 0x91, 0x48, 0x19, 0x76,
	0x51, 0x14, 0x51, 0x1f, 0xb1, 0x90, 0x12, 0xa3, 0x94, 0x27, 0x52, 0x86, 0xf7, 0x54, 0x54, 0xb7,
	0x60, 0x0d, 0x47, 0xd8, 0xe7, 0xbf, 0x5d, 0x7f, 0xec, 0x47, 0xd8, 0x8d, 0x30, 0x19, 0xb2, 0x13,
	0xa3, 0xdc, 0xd1, 0xba, 0x65, 0xbb, 0x2d, 0xc1, 0x01, 0xc7, 0x0e, 0x04, 0xa4, 0x6f, 0x83, 0x1e,
	0x87, 0xc4, 0x4d, 0xe8, 0x39, 0x4e, 0xdd, 0xaf, 0x29, 0x12, 0x09, 0xc6, 0x82, 0xe8, 0xdf, 0x8c,
	0x43, 0x72, 0xc8, 0x81, 0xfd, 0x3c, 0xae, 0xbf, 0x80, 0x35, 0x9f, 0x86, 0xc4, 0xf5, 0x29, 0x61,
	0x3c, 0xe6, 0xa2, 0x20, 0x48, 0x71, 0x96, 0x19, 0x8b, 0x1d, 0xad, 0x5b, 0xb3, 0x96, 0x7a, 0x7b,
	0x93, 0xb3, 0xdd, 0xe6, 0x69, 0x83, 0x3c, 0x2b, 0x0f, 0xea, 0x8f, 0xa0, 0x59, 0x6c, 0x9c, 0xa1,
	0x08, 0xa5, 0x63, 0xa3, 0x22, 0x98, 0x0a, 0x25, 0x8e, 0x44, 0xd8, 0xfc, 0xa1, 0x41, 0xf5, 0x88,
	0x21, 0x86, 0x1d, 0x4b, 0x7f, 0x00, 0x95, 0x44, 0x88, 0x26, 0xf4, 0xa9, 0x59, 0xb7, 0x7a, 0x52,
	0x43, 0x3b, 0x07, 0xf4, 0xc7, 0x00, 0xaa, 0x43, 0x66, 0x94, 0x3a, 0xe5, 0x6e, 0xcd, 0x82, 0x9e,
	0x23, 0x43, 0xf6, 0x14, 0xca, 0x37, 0x8e, 0x50, 0xc6, 0x5c, 0x25, 0x15, 0x0b, 0x63, 0x9c, 0x4b,
	0xd4, 0xe4, 0xc8, 0x9b, 0x1c, 0xf8, 0x14, 0xc6, 0xd8, 0xfc, 0xa5, 0x41, 0xd5, 0xa1, 0x0c, 0xa7,
	0x8e, 0xa5, 0x9b, 0x50, 0x95, 0xfb, 0x6a, 0x33, 0xfb, 0x4a, 0x40, 0x37, 0xa0, 0xea, 0xa1, 0x08,
	0x11, 0x1f, 0xe7, 0x0f, 0x49, 0x1e, 0xf5, 0x1d, 0x58, 0x4e, 0x52, 0xfa, 0x7d, 0xac, 0x34, 0x2b,
	0xcf, 0xf4, 0xa8, 0x0b, 0x58, 0x8a, 0xf5, 0x1c, 0xda, 0x49, 0x1a, 0x12, 0x3f, 0x4c, 0x50, 0x24,
	0x4b, 0x70, 0x66, 0x2c, 0x88, 0xdd, 0x8a, 0x22, 0x5d, 0x25, 0xed, 0xc9, 0x1c, 0xf3, 0x3d, 0xd4,
	0x06, 0x88, 0x04, 0x7c, 0x61, 0xfc, 0x8f, 0x63, 0x6f, 0x40, 0x35, 0x19, 0x79, 0xee, 0x29, 0x1e,
	0x8b, 0xb1, 0xeb, 0x76, 0x25, 0x19, 0x79, 0x1f, 0xf0, 0xd8, 0x7c, 0x05, 0x0d, 0xd5, 0xeb, 0x20,
	0xcc, 0x98, 0x63, 0xe9, 0xdb, 0x00, 0xbe, 0x0c, 0xf1, 0x96, 0x7c, 0xa0, 0x7a, 0x6f, 0x8a, 0xd1,
	0x9e, 0xc2, 0xf9, 0x93, 0xac, 0x70, 0x01, 0x1d, 0x8b, 0x2b, 0xc0, 0x1d, 0x9b, 0xba, 0x57, 0x8d,
	0x53, 0x17, 0xb0, 0x54, 0x60, 0x17, 0x5a, 0xaa, 0x8f, 0x2a, 0x29, 0xcd, 0x94, 0x34, 0x55, 0x8a,
	0x2c, 0x5b, 0x87, 0x0a, 0x8a, 0xc5, 0x75, 0x2a, 0x8b, 0x07, 0x90, 0x9f, 0xcc, 0x27, 0x00, 0x7c,
	0x8e, 0x7c, 0x89, 0x2d, 0x58, 0xe4, 0x64, 0x72, 0xfe, 0x6a, 0x6f, 0x32, 0xa3, 0x3d, 0x89, 0x9a,
	0x1e, 0xb4, 0x5e, 0x1f, 0x7e, 0x3c, 0x7a, 0x47, 0x42, 0x66, 0xe3, 0x6f, 0x23, 0x2c, 0x6a, 0xfe,
	0xaf, 0x11, 0x05, 0x07, 0x8e, 0xf0, 0x10, 0x31, 0x5c, 0x70, 0xec, 0x42, 0xab, 0xb8, 0x23, 0x57,
	0xe9, 0x54, 0x5c, 0xa3, 0xcb, 0x4b, 0x97, 0x84, 0x91, 0xe5, 0xd2, 0xab, 0xa0, 0x17, 0x1c, 0x59,
	0x42, 0x49, 0x86, 0x1d, 0xcb, 0x0c, 0xa0, 0x6d, 0xe3, 0xe0, 0xa6, 0xb9, 0xd7, 0x61, 0x75, 0x9a,
	0x45, 0xb1, 0x7f, 0x81, 0xc6, 0x31, 0xf1, 0x28, 0x09, 0x6e, 0x8c, 0x59, 0x87, 0xa6, 0x64, 0x50,
	0xac, 0xbb, 0xb0, 0x69, 0xe3, 0x61, 0x98, 0x31, 0x9c, 0x2a, 0xab, 0x16, 0x03, 0x4c, 0xf9, 0x5f,
	0xbb, 0xe0, 0xff, 0x2d, 0xb8, 0x33, 0xa7, 0x4c, 0x75, 0xbd, 0x07, 0x77, 0x8f, 0x49, 0x7a, 0x65,
	0x5f, 0xf3, 0x3e, 0x6c, 0xcd, 0xc5, 0x55, 0x83, 0xcf, 0xb0, 0xcc, 0x9d, 0x77, 0x41, 0x8a, 0xcb,
	0xae, 0xd7, 0xae, 0xe1, 0xfa, 0x8b, 0x52, 0x34, 0x61, 0x65, 0xd2, 0x5f, 0x31, 0x36, 0x61, 0x45,
	0xbc, 0xe1, 0x8a, 0x21, 0x5b, 0xd0, 0xc8, 0x23, 0x2a, 0xe9, 0x36, 0x6c, 0x88, 0x8b, 0xa2, 0xdc,
	0x5a, 0x64, 0xef, 0x83, 0x31, 0x0b, 0xc9, 0xb2, 0x19, 0xfb, 0x6b, 0x7f, 0xb4, 0xbf, 0x01, 0xeb,
	0xbc, 0xcf, 0x1c, 0xd1, 0xde, 0x4e, 0xc8, 0xe7, 0xc8, 0x75, 0xbd, 0x77, 0x8f, 0x57, 0x11, 0x7f,
	0xbb, 0xcf, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x19, 0xb6, 0xa7, 0xea, 0x07, 0x00, 0x00,
}
