// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/builtin/types/dposv2/dposv2.proto

/*
Package dposv2 is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/go-loom/builtin/types/dposv2/dposv2.proto

It has these top-level messages:
	ParamsV2
	StateV2
	VoterV2
	CandidateV2
	CandidateListV2
	DelegationV2
	DelegationListV2
	VoteV2
	VoteListV2
	DPOSInitRequestV2
	DelegateRequestV2
	RedelegateRequestV2
	CheckDelegationRequestV2
	CheckDelegationResponseV2
	UnbondRequestV2
	RegisterCandidateRequestV2
	UnregisterCandidateRequestV2
	VoteRequestV2
	ElectRequestV2
	ListValidatorsRequestV2
	ListValidatorsResponseV2
	ListCandidateRequestV2
	ListCandidateResponseV2
*/
package dposv2

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ParamsV2 struct {
	ValidatorCount      uint64         `protobuf:"varint,1,opt,name=validator_count,json=validatorCount,proto3" json:"validator_count,omitempty"`
	VoteAllocation      uint64         `protobuf:"varint,2,opt,name=vote_allocation,json=voteAllocation,proto3" json:"vote_allocation,omitempty"`
	ElectionCycleLength int64          `protobuf:"varint,3,opt,name=election_cycle_length,json=electionCycleLength,proto3" json:"election_cycle_length,omitempty"`
	MinPowerFraction    uint64         `protobuf:"varint,4,opt,name=min_power_fraction,json=minPowerFraction,proto3" json:"min_power_fraction,omitempty"`
	CoinContractAddress *types.Address `protobuf:"bytes,5,opt,name=coin_contract_address,json=coinContractAddress" json:"coin_contract_address,omitempty"`
	ValidatorSalary     uint64         `protobuf:"varint,6,opt,name=validator_salary,json=validatorSalary,proto3" json:"validator_salary,omitempty"`
}

func (m *ParamsV2) Reset()                    { *m = ParamsV2{} }
func (m *ParamsV2) String() string            { return proto.CompactTextString(m) }
func (*ParamsV2) ProtoMessage()               {}
func (*ParamsV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{0} }

func (m *ParamsV2) GetValidatorCount() uint64 {
	if m != nil {
		return m.ValidatorCount
	}
	return 0
}

func (m *ParamsV2) GetVoteAllocation() uint64 {
	if m != nil {
		return m.VoteAllocation
	}
	return 0
}

func (m *ParamsV2) GetElectionCycleLength() int64 {
	if m != nil {
		return m.ElectionCycleLength
	}
	return 0
}

func (m *ParamsV2) GetMinPowerFraction() uint64 {
	if m != nil {
		return m.MinPowerFraction
	}
	return 0
}

func (m *ParamsV2) GetCoinContractAddress() *types.Address {
	if m != nil {
		return m.CoinContractAddress
	}
	return nil
}

func (m *ParamsV2) GetValidatorSalary() uint64 {
	if m != nil {
		return m.ValidatorSalary
	}
	return 0
}

type StateV2 struct {
	Params           *ParamsV2          `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	Validators       []*types.Validator `protobuf:"bytes,2,rep,name=validators" json:"validators,omitempty"`
	LastElectionTime int64              `protobuf:"varint,3,opt,name=last_election_time,json=lastElectionTime,proto3" json:"last_election_time,omitempty"`
}

func (m *StateV2) Reset()                    { *m = StateV2{} }
func (m *StateV2) String() string            { return proto.CompactTextString(m) }
func (*StateV2) ProtoMessage()               {}
func (*StateV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{1} }

func (m *StateV2) GetParams() *ParamsV2 {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *StateV2) GetValidators() []*types.Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *StateV2) GetLastElectionTime() int64 {
	if m != nil {
		return m.LastElectionTime
	}
	return 0
}

type VoterV2 struct {
	Address            *types.Address   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Balance            uint64           `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ProxyAddress       *types.Address   `protobuf:"bytes,3,opt,name=proxy_address,json=proxyAddress" json:"proxy_address,omitempty"`
	PrincipalAddresses []*types.Address `protobuf:"bytes,4,rep,name=principal_addresses,json=principalAddresses" json:"principal_addresses,omitempty"`
}

func (m *VoterV2) Reset()                    { *m = VoterV2{} }
func (m *VoterV2) String() string            { return proto.CompactTextString(m) }
func (*VoterV2) ProtoMessage()               {}
func (*VoterV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{2} }

func (m *VoterV2) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *VoterV2) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *VoterV2) GetProxyAddress() *types.Address {
	if m != nil {
		return m.ProxyAddress
	}
	return nil
}

func (m *VoterV2) GetPrincipalAddresses() []*types.Address {
	if m != nil {
		return m.PrincipalAddresses
	}
	return nil
}

type CandidateV2 struct {
	Address *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	PubKey  []byte         `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (m *CandidateV2) Reset()                    { *m = CandidateV2{} }
func (m *CandidateV2) String() string            { return proto.CompactTextString(m) }
func (*CandidateV2) ProtoMessage()               {}
func (*CandidateV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{3} }

func (m *CandidateV2) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *CandidateV2) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type CandidateListV2 struct {
	Candidates []*CandidateV2 `protobuf:"bytes,1,rep,name=candidates" json:"candidates,omitempty"`
}

func (m *CandidateListV2) Reset()                    { *m = CandidateListV2{} }
func (m *CandidateListV2) String() string            { return proto.CompactTextString(m) }
func (*CandidateListV2) ProtoMessage()               {}
func (*CandidateListV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{4} }

func (m *CandidateListV2) GetCandidates() []*CandidateV2 {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type DelegationV2 struct {
	Validator *types.Address `protobuf:"bytes,1,opt,name=validator" json:"validator,omitempty"`
	Delegator *types.Address `protobuf:"bytes,2,opt,name=delegator" json:"delegator,omitempty"`
	Height    uint64         `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Amount    *types.BigUInt `protobuf:"bytes,4,opt,name=amount" json:"amount,omitempty"`
}

func (m *DelegationV2) Reset()                    { *m = DelegationV2{} }
func (m *DelegationV2) String() string            { return proto.CompactTextString(m) }
func (*DelegationV2) ProtoMessage()               {}
func (*DelegationV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{5} }

func (m *DelegationV2) GetValidator() *types.Address {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *DelegationV2) GetDelegator() *types.Address {
	if m != nil {
		return m.Delegator
	}
	return nil
}

func (m *DelegationV2) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *DelegationV2) GetAmount() *types.BigUInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

type DelegationListV2 struct {
	Delegations []*DelegationV2 `protobuf:"bytes,1,rep,name=delegations" json:"delegations,omitempty"`
}

func (m *DelegationListV2) Reset()                    { *m = DelegationListV2{} }
func (m *DelegationListV2) String() string            { return proto.CompactTextString(m) }
func (*DelegationListV2) ProtoMessage()               {}
func (*DelegationListV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{6} }

func (m *DelegationListV2) GetDelegations() []*DelegationV2 {
	if m != nil {
		return m.Delegations
	}
	return nil
}

type VoteV2 struct {
	VoterAddress     *types.Address `protobuf:"bytes,1,opt,name=voter_address,json=voterAddress" json:"voter_address,omitempty"`
	CandidateAddress *types.Address `protobuf:"bytes,2,opt,name=candidate_address,json=candidateAddress" json:"candidate_address,omitempty"`
	Amount           uint64         `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *VoteV2) Reset()                    { *m = VoteV2{} }
func (m *VoteV2) String() string            { return proto.CompactTextString(m) }
func (*VoteV2) ProtoMessage()               {}
func (*VoteV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{7} }

func (m *VoteV2) GetVoterAddress() *types.Address {
	if m != nil {
		return m.VoterAddress
	}
	return nil
}

func (m *VoteV2) GetCandidateAddress() *types.Address {
	if m != nil {
		return m.CandidateAddress
	}
	return nil
}

func (m *VoteV2) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type VoteListV2 struct {
	Votes []*VoteV2 `protobuf:"bytes,1,rep,name=votes" json:"votes,omitempty"`
}

func (m *VoteListV2) Reset()                    { *m = VoteListV2{} }
func (m *VoteListV2) String() string            { return proto.CompactTextString(m) }
func (*VoteListV2) ProtoMessage()               {}
func (*VoteListV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{8} }

func (m *VoteListV2) GetVotes() []*VoteV2 {
	if m != nil {
		return m.Votes
	}
	return nil
}

type DPOSInitRequestV2 struct {
	Params     *ParamsV2          `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	Validators []*types.Validator `protobuf:"bytes,2,rep,name=validators" json:"validators,omitempty"`
}

func (m *DPOSInitRequestV2) Reset()                    { *m = DPOSInitRequestV2{} }
func (m *DPOSInitRequestV2) String() string            { return proto.CompactTextString(m) }
func (*DPOSInitRequestV2) ProtoMessage()               {}
func (*DPOSInitRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{9} }

func (m *DPOSInitRequestV2) GetParams() *ParamsV2 {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *DPOSInitRequestV2) GetValidators() []*types.Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type DelegateRequestV2 struct {
	ValidatorAddress *types.Address `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress" json:"validator_address,omitempty"`
	Amount           *types.BigUInt `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *DelegateRequestV2) Reset()                    { *m = DelegateRequestV2{} }
func (m *DelegateRequestV2) String() string            { return proto.CompactTextString(m) }
func (*DelegateRequestV2) ProtoMessage()               {}
func (*DelegateRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{10} }

func (m *DelegateRequestV2) GetValidatorAddress() *types.Address {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *DelegateRequestV2) GetAmount() *types.BigUInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

type RedelegateRequestV2 struct {
	ValidatorAddress *types.Address `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress" json:"validator_address,omitempty"`
	Amount           *types.BigUInt `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *RedelegateRequestV2) Reset()                    { *m = RedelegateRequestV2{} }
func (m *RedelegateRequestV2) String() string            { return proto.CompactTextString(m) }
func (*RedelegateRequestV2) ProtoMessage()               {}
func (*RedelegateRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{11} }

func (m *RedelegateRequestV2) GetValidatorAddress() *types.Address {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *RedelegateRequestV2) GetAmount() *types.BigUInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

type CheckDelegationRequestV2 struct {
	ValidatorAddress *types.Address `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress" json:"validator_address,omitempty"`
}

func (m *CheckDelegationRequestV2) Reset()                    { *m = CheckDelegationRequestV2{} }
func (m *CheckDelegationRequestV2) String() string            { return proto.CompactTextString(m) }
func (*CheckDelegationRequestV2) ProtoMessage()               {}
func (*CheckDelegationRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{12} }

func (m *CheckDelegationRequestV2) GetValidatorAddress() *types.Address {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

type CheckDelegationResponseV2 struct {
	Delegation *DelegationV2 `protobuf:"bytes,1,opt,name=delegation" json:"delegation,omitempty"`
}

func (m *CheckDelegationResponseV2) Reset()                    { *m = CheckDelegationResponseV2{} }
func (m *CheckDelegationResponseV2) String() string            { return proto.CompactTextString(m) }
func (*CheckDelegationResponseV2) ProtoMessage()               {}
func (*CheckDelegationResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{13} }

func (m *CheckDelegationResponseV2) GetDelegation() *DelegationV2 {
	if m != nil {
		return m.Delegation
	}
	return nil
}

type UnbondRequestV2 struct {
	ValidatorAddress *types.Address `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress" json:"validator_address,omitempty"`
	Amount           *types.BigUInt `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *UnbondRequestV2) Reset()                    { *m = UnbondRequestV2{} }
func (m *UnbondRequestV2) String() string            { return proto.CompactTextString(m) }
func (*UnbondRequestV2) ProtoMessage()               {}
func (*UnbondRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{14} }

func (m *UnbondRequestV2) GetValidatorAddress() *types.Address {
	if m != nil {
		return m.ValidatorAddress
	}
	return nil
}

func (m *UnbondRequestV2) GetAmount() *types.BigUInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

type RegisterCandidateRequestV2 struct {
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (m *RegisterCandidateRequestV2) Reset()         { *m = RegisterCandidateRequestV2{} }
func (m *RegisterCandidateRequestV2) String() string { return proto.CompactTextString(m) }
func (*RegisterCandidateRequestV2) ProtoMessage()    {}
func (*RegisterCandidateRequestV2) Descriptor() ([]byte, []int) {
	return fileDescriptorDposv2, []int{15}
}

func (m *RegisterCandidateRequestV2) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type UnregisterCandidateRequestV2 struct {
}

func (m *UnregisterCandidateRequestV2) Reset()         { *m = UnregisterCandidateRequestV2{} }
func (m *UnregisterCandidateRequestV2) String() string { return proto.CompactTextString(m) }
func (*UnregisterCandidateRequestV2) ProtoMessage()    {}
func (*UnregisterCandidateRequestV2) Descriptor() ([]byte, []int) {
	return fileDescriptorDposv2, []int{16}
}

type VoteRequestV2 struct {
	CandidateAddress *types.Address `protobuf:"bytes,1,opt,name=candidate_address,json=candidateAddress" json:"candidate_address,omitempty"`
	Amount           int64          `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *VoteRequestV2) Reset()                    { *m = VoteRequestV2{} }
func (m *VoteRequestV2) String() string            { return proto.CompactTextString(m) }
func (*VoteRequestV2) ProtoMessage()               {}
func (*VoteRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{17} }

func (m *VoteRequestV2) GetCandidateAddress() *types.Address {
	if m != nil {
		return m.CandidateAddress
	}
	return nil
}

func (m *VoteRequestV2) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ElectRequestV2 struct {
}

func (m *ElectRequestV2) Reset()                    { *m = ElectRequestV2{} }
func (m *ElectRequestV2) String() string            { return proto.CompactTextString(m) }
func (*ElectRequestV2) ProtoMessage()               {}
func (*ElectRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{18} }

type ListValidatorsRequestV2 struct {
}

func (m *ListValidatorsRequestV2) Reset()                    { *m = ListValidatorsRequestV2{} }
func (m *ListValidatorsRequestV2) String() string            { return proto.CompactTextString(m) }
func (*ListValidatorsRequestV2) ProtoMessage()               {}
func (*ListValidatorsRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{19} }

type ListValidatorsResponseV2 struct {
	Validators []*types.Validator `protobuf:"bytes,1,rep,name=validators" json:"validators,omitempty"`
}

func (m *ListValidatorsResponseV2) Reset()                    { *m = ListValidatorsResponseV2{} }
func (m *ListValidatorsResponseV2) String() string            { return proto.CompactTextString(m) }
func (*ListValidatorsResponseV2) ProtoMessage()               {}
func (*ListValidatorsResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{20} }

func (m *ListValidatorsResponseV2) GetValidators() []*types.Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type ListCandidateRequestV2 struct {
}

func (m *ListCandidateRequestV2) Reset()                    { *m = ListCandidateRequestV2{} }
func (m *ListCandidateRequestV2) String() string            { return proto.CompactTextString(m) }
func (*ListCandidateRequestV2) ProtoMessage()               {}
func (*ListCandidateRequestV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{21} }

type ListCandidateResponseV2 struct {
	Candidates []*CandidateV2 `protobuf:"bytes,1,rep,name=candidates" json:"candidates,omitempty"`
}

func (m *ListCandidateResponseV2) Reset()                    { *m = ListCandidateResponseV2{} }
func (m *ListCandidateResponseV2) String() string            { return proto.CompactTextString(m) }
func (*ListCandidateResponseV2) ProtoMessage()               {}
func (*ListCandidateResponseV2) Descriptor() ([]byte, []int) { return fileDescriptorDposv2, []int{22} }

func (m *ListCandidateResponseV2) GetCandidates() []*CandidateV2 {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func init() {
	proto.RegisterType((*ParamsV2)(nil), "ParamsV2")
	proto.RegisterType((*StateV2)(nil), "StateV2")
	proto.RegisterType((*VoterV2)(nil), "VoterV2")
	proto.RegisterType((*CandidateV2)(nil), "CandidateV2")
	proto.RegisterType((*CandidateListV2)(nil), "CandidateListV2")
	proto.RegisterType((*DelegationV2)(nil), "DelegationV2")
	proto.RegisterType((*DelegationListV2)(nil), "DelegationListV2")
	proto.RegisterType((*VoteV2)(nil), "VoteV2")
	proto.RegisterType((*VoteListV2)(nil), "VoteListV2")
	proto.RegisterType((*DPOSInitRequestV2)(nil), "DPOSInitRequestV2")
	proto.RegisterType((*DelegateRequestV2)(nil), "DelegateRequestV2")
	proto.RegisterType((*RedelegateRequestV2)(nil), "RedelegateRequestV2")
	proto.RegisterType((*CheckDelegationRequestV2)(nil), "CheckDelegationRequestV2")
	proto.RegisterType((*CheckDelegationResponseV2)(nil), "CheckDelegationResponseV2")
	proto.RegisterType((*UnbondRequestV2)(nil), "UnbondRequestV2")
	proto.RegisterType((*RegisterCandidateRequestV2)(nil), "RegisterCandidateRequestV2")
	proto.RegisterType((*UnregisterCandidateRequestV2)(nil), "UnregisterCandidateRequestV2")
	proto.RegisterType((*VoteRequestV2)(nil), "VoteRequestV2")
	proto.RegisterType((*ElectRequestV2)(nil), "ElectRequestV2")
	proto.RegisterType((*ListValidatorsRequestV2)(nil), "ListValidatorsRequestV2")
	proto.RegisterType((*ListValidatorsResponseV2)(nil), "ListValidatorsResponseV2")
	proto.RegisterType((*ListCandidateRequestV2)(nil), "ListCandidateRequestV2")
	proto.RegisterType((*ListCandidateResponseV2)(nil), "ListCandidateResponseV2")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/builtin/types/dposv2/dposv2.proto", fileDescriptorDposv2)
}

var fileDescriptorDposv2 = []byte{
	// 825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x96, 0xb3, 0x69, 0xd2, 0x9e, 0x64, 0xbb, 0xd9, 0x59, 0x75, 0xeb, 0x56, 0x80, 0x82, 0x2f,
	0x20, 0x40, 0xeb, 0x20, 0xa3, 0xbd, 0x40, 0x42, 0x82, 0x25, 0xa5, 0xa8, 0xa5, 0x12, 0x8b, 0x97,
	0xf5, 0x25, 0xd6, 0xd8, 0x1e, 0x92, 0x61, 0xed, 0x19, 0x63, 0x4f, 0x5a, 0xf2, 0x02, 0x3c, 0x03,
	0x6f, 0xc0, 0x35, 0x6f, 0x88, 0x66, 0x3c, 0x33, 0x76, 0xb2, 0x04, 0xa8, 0x40, 0xbd, 0x49, 0x32,
	0xe7, 0x3b, 0x7f, 0xdf, 0xf9, 0x53, 0xe0, 0x8b, 0x25, 0x15, 0xab, 0x75, 0xe2, 0xa7, 0xbc, 0x98,
	0xe7, 0x9c, 0x17, 0x8c, 0x88, 0x57, 0xbc, 0xba, 0x9e, 0x2f, 0xf9, 0x63, 0xf9, 0x9c, 0x27, 0x6b,
	0x9a, 0x0b, 0xca, 0xe6, 0x62, 0x53, 0x92, 0x7a, 0x9e, 0x95, 0xbc, 0x7e, 0x19, 0xe8, 0x2f, 0xbf,
	0xac, 0xb8, 0xe0, 0x0f, 0x3f, 0xfe, 0x07, 0x0f, 0x8d, 0xa5, 0xfa, 0x6c, 0x2c, 0xbc, 0xdf, 0x7b,
	0x70, 0xfb, 0x02, 0x57, 0xb8, 0xa8, 0xa3, 0x00, 0xbd, 0x0f, 0x47, 0x2f, 0x71, 0x4e, 0x33, 0x2c,
	0x78, 0x15, 0xa7, 0x7c, 0xcd, 0x84, 0xeb, 0x4c, 0x9d, 0x59, 0x3f, 0xbc, 0x6b, 0xc5, 0x0b, 0x29,
	0x55, 0x8a, 0x5c, 0x90, 0x18, 0xe7, 0x39, 0x4f, 0xb1, 0xa0, 0x9c, 0xb9, 0x3d, 0xad, 0xc8, 0x05,
	0x39, 0xb7, 0x52, 0x14, 0xc0, 0x3d, 0x92, 0x93, 0x54, 0xfe, 0x8e, 0xd3, 0x4d, 0x9a, 0x93, 0x38,
	0x27, 0x6c, 0x29, 0x56, 0xee, 0xc1, 0xd4, 0x99, 0x1d, 0x84, 0x27, 0x06, 0x5c, 0x48, 0xec, 0x85,
	0x82, 0xd0, 0x23, 0x40, 0x05, 0x65, 0x71, 0xc9, 0x5f, 0x91, 0x2a, 0xfe, 0xb1, 0xc2, 0x4a, 0xc1,
	0xed, 0x2b, 0xff, 0x93, 0x82, 0xb2, 0x0b, 0x09, 0x3c, 0xd5, 0x72, 0xf4, 0x19, 0xdc, 0x4b, 0x39,
	0x65, 0x71, 0xca, 0x99, 0x90, 0xb2, 0x18, 0x67, 0x59, 0x45, 0xea, 0xda, 0xbd, 0x35, 0x75, 0x66,
	0xa3, 0xe0, 0xb6, 0x7f, 0xde, 0xbc, 0xc3, 0x13, 0xa9, 0xb6, 0xd0, 0x5a, 0x5a, 0x88, 0x3e, 0x80,
	0x49, 0xcb, 0xb8, 0xc6, 0x39, 0xae, 0x36, 0xee, 0x40, 0x45, 0x6a, 0x2b, 0x71, 0xa9, 0xc4, 0xde,
	0xaf, 0x0e, 0x0c, 0x2f, 0x05, 0x16, 0x24, 0x0a, 0xd0, 0xbb, 0x30, 0x28, 0x55, 0xd1, 0x54, 0x7d,
	0x46, 0xc1, 0x1d, 0xdf, 0xd4, 0x30, 0xd4, 0x00, 0xfa, 0x10, 0xc0, 0x7a, 0xa8, 0xdd, 0xde, 0xf4,
	0x60, 0x36, 0x0a, 0xc0, 0x8f, 0x8c, 0x28, 0xec, 0xa0, 0x92, 0x71, 0x8e, 0x6b, 0x11, 0xdb, 0x52,
	0x09, 0x5a, 0x10, 0x5d, 0xa2, 0x89, 0x44, 0xbe, 0xd2, 0xc0, 0xf7, 0xb4, 0x20, 0xde, 0x1f, 0x0e,
	0x0c, 0x23, 0x2e, 0x48, 0x15, 0x05, 0xc8, 0x83, 0xa1, 0xe1, 0xeb, 0xec, 0xf0, 0x35, 0x00, 0x72,
	0x61, 0x98, 0xe0, 0x1c, 0xb3, 0x94, 0xe8, 0x26, 0x99, 0x27, 0x7a, 0x0c, 0x87, 0x65, 0xc5, 0x7f,
	0xd9, 0xd8, 0x9a, 0x1d, 0xec, 0xf8, 0x18, 0x2b, 0xd8, 0x14, 0xeb, 0x53, 0x38, 0x29, 0x2b, 0xca,
	0x52, 0x5a, 0xe2, 0xdc, 0x98, 0x90, 0xda, 0xed, 0x2b, 0x6e, 0xad, 0x11, 0xb2, 0x4a, 0xe7, 0x46,
	0xc7, 0x7b, 0x0e, 0xa3, 0x05, 0x66, 0x99, 0x24, 0x4c, 0xfe, 0x65, 0xda, 0xf7, 0x61, 0x58, 0xae,
	0x93, 0xf8, 0x9a, 0x6c, 0x54, 0xda, 0xe3, 0x70, 0x50, 0xae, 0x93, 0x6f, 0xc8, 0xc6, 0xfb, 0x1c,
	0x8e, 0xac, 0xaf, 0x17, 0xb4, 0x16, 0x51, 0x80, 0x1e, 0x01, 0xa4, 0x46, 0x24, 0x5d, 0xca, 0x84,
	0xc6, 0x7e, 0x27, 0x62, 0xd8, 0xc1, 0xbd, 0xdf, 0x1c, 0x18, 0x3f, 0x21, 0x39, 0x59, 0xaa, 0x19,
	0x8d, 0x02, 0xf4, 0x1e, 0xdc, 0xb1, 0xdd, 0xb8, 0x91, 0x50, 0x0b, 0x49, 0xbd, 0xac, 0xb1, 0xe3,
	0x95, 0x4a, 0x6a, 0x4b, 0xcf, 0x42, 0xe8, 0x14, 0x06, 0x2b, 0x42, 0x97, 0x2b, 0xa1, 0x0a, 0xda,
	0x0f, 0xf5, 0x0b, 0x4d, 0x61, 0x80, 0x0b, 0xb5, 0x56, 0x7d, 0x6d, 0xfc, 0x25, 0x5d, 0x5e, 0x3d,
	0x63, 0x22, 0xd4, 0x72, 0x6f, 0x01, 0x93, 0x36, 0x33, 0x4d, 0x6e, 0x0e, 0xa3, 0xcc, 0xca, 0x0c,
	0xbb, 0x43, 0xbf, 0xcb, 0x20, 0xec, 0x6a, 0xc8, 0x49, 0x1d, 0xc8, 0x01, 0x89, 0x02, 0xd9, 0x61,
	0xb9, 0x91, 0x55, 0xbc, 0xaf, 0xdc, 0x63, 0x05, 0x9b, 0x0e, 0x9f, 0xc1, 0xb1, 0xad, 0x93, 0x35,
	0xd9, 0x25, 0x3a, 0xb1, 0x2a, 0xc6, 0xec, 0xd4, 0xf2, 0xd2, 0x7c, 0x35, 0x9b, 0x8f, 0x00, 0x64,
	0x1e, 0x9a, 0xc7, 0xdb, 0x70, 0x4b, 0x06, 0x33, 0x0c, 0x86, 0x7e, 0x93, 0x63, 0xd8, 0x48, 0xbd,
	0x04, 0x8e, 0x9f, 0x5c, 0x7c, 0x7b, 0xf9, 0x8c, 0x51, 0x11, 0x92, 0x9f, 0xd7, 0x44, 0xd9, 0xfc,
	0xbf, 0x8b, 0xe6, 0xe5, 0x70, 0xac, 0xcb, 0x46, 0xda, 0x18, 0x67, 0x70, 0xdc, 0xde, 0x80, 0x7d,
	0x75, 0x6a, 0xcf, 0x84, 0x21, 0xdd, 0x36, 0xb3, 0xb7, 0xa7, 0x99, 0x0c, 0x4e, 0x42, 0x92, 0xbd,
	0xb9, 0x78, 0xdf, 0x81, 0xbb, 0x58, 0x91, 0xf4, 0xba, 0x9d, 0x8c, 0xff, 0x1a, 0xd4, 0x7b, 0x0e,
	0x0f, 0x6e, 0xb8, 0xac, 0x4b, 0xce, 0xea, 0x66, 0xb8, 0xa0, 0x1d, 0x3b, 0xed, 0x6c, 0x67, 0x2e,
	0x3b, 0x0a, 0xde, 0x4f, 0x70, 0x74, 0xc5, 0x12, 0xce, 0xb2, 0x37, 0x50, 0x8a, 0x33, 0x78, 0x18,
	0x92, 0x25, 0xad, 0x05, 0xa9, 0xec, 0x15, 0x68, 0xc3, 0x76, 0x4e, 0x8b, 0xb3, 0x75, 0x5a, 0xde,
	0x81, 0xb7, 0xae, 0x58, 0xb5, 0xd7, 0xd0, 0xfb, 0x01, 0x0e, 0xe5, 0xd0, 0x6e, 0x11, 0xb8, 0xb9,
	0x30, 0xce, 0x6b, 0x2c, 0x4c, 0x4f, 0x1d, 0x79, 0x93, 0xf6, 0x04, 0xee, 0xaa, 0x53, 0xdf, 0x46,
	0x7c, 0x00, 0xf7, 0xd5, 0xfa, 0xd8, 0x19, 0x6e, 0xa1, 0xa7, 0xe0, 0xee, 0x42, 0xb6, 0x35, 0xdb,
	0x4b, 0xe1, 0xfc, 0xed, 0x52, 0xb8, 0x70, 0x2a, 0xfd, 0xfc, 0x05, 0xdd, 0xaf, 0x9b, 0xe0, 0x1d,
	0xc4, 0x06, 0x78, 0xad, 0x8b, 0x9b, 0x0c, 0xd4, 0x9f, 0x8d, 0x4f, 0xfe, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xd5, 0x12, 0xf8, 0xa7, 0xe2, 0x08, 0x00, 0x00,
}
