// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/builtin/types/address_mapper/address_mapper.proto

package address_mapper

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Bidirectional mapping between addresses (contracts or accounts) on two different blockchains.
// One of the address fields must contain a local address (same chain ID as the contract), while the
// other must contain a foreign address.
type AddressMapperMapping struct {
	// Address on a blockchain
	From *types.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	// Corresponding address on another blockchain
	To                   *types.Address `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperMapping) Reset()         { *m = AddressMapperMapping{} }
func (m *AddressMapperMapping) String() string { return proto.CompactTextString(m) }
func (*AddressMapperMapping) ProtoMessage()    {}
func (*AddressMapperMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{0}
}
func (m *AddressMapperMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperMapping.Unmarshal(m, b)
}
func (m *AddressMapperMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperMapping.Marshal(b, m, deterministic)
}
func (dst *AddressMapperMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperMapping.Merge(dst, src)
}
func (m *AddressMapperMapping) XXX_Size() int {
	return xxx_messageInfo_AddressMapperMapping.Size(m)
}
func (m *AddressMapperMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperMapping.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperMapping proto.InternalMessageInfo

func (m *AddressMapperMapping) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *AddressMapperMapping) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

type ListAddressMapperMapping struct {
	Mappings             []*AddressMapperMapping `protobuf:"bytes,1,rep,name=mappings" json:"mappings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListAddressMapperMapping) Reset()         { *m = ListAddressMapperMapping{} }
func (m *ListAddressMapperMapping) String() string { return proto.CompactTextString(m) }
func (*ListAddressMapperMapping) ProtoMessage()    {}
func (*ListAddressMapperMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{1}
}
func (m *ListAddressMapperMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAddressMapperMapping.Unmarshal(m, b)
}
func (m *ListAddressMapperMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAddressMapperMapping.Marshal(b, m, deterministic)
}
func (dst *ListAddressMapperMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAddressMapperMapping.Merge(dst, src)
}
func (m *ListAddressMapperMapping) XXX_Size() int {
	return xxx_messageInfo_ListAddressMapperMapping.Size(m)
}
func (m *ListAddressMapperMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAddressMapperMapping.DiscardUnknown(m)
}

var xxx_messageInfo_ListAddressMapperMapping proto.InternalMessageInfo

func (m *ListAddressMapperMapping) GetMappings() []*AddressMapperMapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

type AddressMapperGetMultichainMappingRequest struct {
	From                 *types.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	ChainId              string         `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperGetMultichainMappingRequest) Reset() {
	*m = AddressMapperGetMultichainMappingRequest{}
}
func (m *AddressMapperGetMultichainMappingRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperGetMultichainMappingRequest) ProtoMessage()    {}
func (*AddressMapperGetMultichainMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{2}
}
func (m *AddressMapperGetMultichainMappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperGetMultichainMappingRequest.Unmarshal(m, b)
}
func (m *AddressMapperGetMultichainMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperGetMultichainMappingRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperGetMultichainMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperGetMultichainMappingRequest.Merge(dst, src)
}
func (m *AddressMapperGetMultichainMappingRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperGetMultichainMappingRequest.Size(m)
}
func (m *AddressMapperGetMultichainMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperGetMultichainMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperGetMultichainMappingRequest proto.InternalMessageInfo

func (m *AddressMapperGetMultichainMappingRequest) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *AddressMapperGetMultichainMappingRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type AddressMapperGetMultichainMappingResponse struct {
	Mappings             []*AddressMapperMapping `protobuf:"bytes,1,rep,name=mappings" json:"mappings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AddressMapperGetMultichainMappingResponse) Reset() {
	*m = AddressMapperGetMultichainMappingResponse{}
}
func (m *AddressMapperGetMultichainMappingResponse) String() string { return proto.CompactTextString(m) }
func (*AddressMapperGetMultichainMappingResponse) ProtoMessage()    {}
func (*AddressMapperGetMultichainMappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{3}
}
func (m *AddressMapperGetMultichainMappingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperGetMultichainMappingResponse.Unmarshal(m, b)
}
func (m *AddressMapperGetMultichainMappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperGetMultichainMappingResponse.Marshal(b, m, deterministic)
}
func (dst *AddressMapperGetMultichainMappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperGetMultichainMappingResponse.Merge(dst, src)
}
func (m *AddressMapperGetMultichainMappingResponse) XXX_Size() int {
	return xxx_messageInfo_AddressMapperGetMultichainMappingResponse.Size(m)
}
func (m *AddressMapperGetMultichainMappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperGetMultichainMappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperGetMultichainMappingResponse proto.InternalMessageInfo

func (m *AddressMapperGetMultichainMappingResponse) GetMappings() []*AddressMapperMapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

type AddressMapperSetNonceRequest struct {
	Address              *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperSetNonceRequest) Reset()         { *m = AddressMapperSetNonceRequest{} }
func (m *AddressMapperSetNonceRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperSetNonceRequest) ProtoMessage()    {}
func (*AddressMapperSetNonceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{4}
}
func (m *AddressMapperSetNonceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperSetNonceRequest.Unmarshal(m, b)
}
func (m *AddressMapperSetNonceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperSetNonceRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperSetNonceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperSetNonceRequest.Merge(dst, src)
}
func (m *AddressMapperSetNonceRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperSetNonceRequest.Size(m)
}
func (m *AddressMapperSetNonceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperSetNonceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperSetNonceRequest proto.InternalMessageInfo

func (m *AddressMapperSetNonceRequest) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type AddressMapperGetNonceRequest struct {
	Address              *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperGetNonceRequest) Reset()         { *m = AddressMapperGetNonceRequest{} }
func (m *AddressMapperGetNonceRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperGetNonceRequest) ProtoMessage()    {}
func (*AddressMapperGetNonceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{5}
}
func (m *AddressMapperGetNonceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperGetNonceRequest.Unmarshal(m, b)
}
func (m *AddressMapperGetNonceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperGetNonceRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperGetNonceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperGetNonceRequest.Merge(dst, src)
}
func (m *AddressMapperGetNonceRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperGetNonceRequest.Size(m)
}
func (m *AddressMapperGetNonceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperGetNonceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperGetNonceRequest proto.InternalMessageInfo

func (m *AddressMapperGetNonceRequest) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type AddressMapperGetNonceResponse struct {
	Address              *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Nonce                uint64         `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperGetNonceResponse) Reset()         { *m = AddressMapperGetNonceResponse{} }
func (m *AddressMapperGetNonceResponse) String() string { return proto.CompactTextString(m) }
func (*AddressMapperGetNonceResponse) ProtoMessage()    {}
func (*AddressMapperGetNonceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{6}
}
func (m *AddressMapperGetNonceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperGetNonceResponse.Unmarshal(m, b)
}
func (m *AddressMapperGetNonceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperGetNonceResponse.Marshal(b, m, deterministic)
}
func (dst *AddressMapperGetNonceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperGetNonceResponse.Merge(dst, src)
}
func (m *AddressMapperGetNonceResponse) XXX_Size() int {
	return xxx_messageInfo_AddressMapperGetNonceResponse.Size(m)
}
func (m *AddressMapperGetNonceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperGetNonceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperGetNonceResponse proto.InternalMessageInfo

func (m *AddressMapperGetNonceResponse) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *AddressMapperGetNonceResponse) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type AddressMapperNonce struct {
	Address              *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Nonce                uint64         `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperNonce) Reset()         { *m = AddressMapperNonce{} }
func (m *AddressMapperNonce) String() string { return proto.CompactTextString(m) }
func (*AddressMapperNonce) ProtoMessage()    {}
func (*AddressMapperNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{7}
}
func (m *AddressMapperNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperNonce.Unmarshal(m, b)
}
func (m *AddressMapperNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperNonce.Marshal(b, m, deterministic)
}
func (dst *AddressMapperNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperNonce.Merge(dst, src)
}
func (m *AddressMapperNonce) XXX_Size() int {
	return xxx_messageInfo_AddressMapperNonce.Size(m)
}
func (m *AddressMapperNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperNonce.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperNonce proto.InternalMessageInfo

func (m *AddressMapperNonce) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *AddressMapperNonce) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type AddressMapperInitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressMapperInitRequest) Reset()         { *m = AddressMapperInitRequest{} }
func (m *AddressMapperInitRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperInitRequest) ProtoMessage()    {}
func (*AddressMapperInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{8}
}
func (m *AddressMapperInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperInitRequest.Unmarshal(m, b)
}
func (m *AddressMapperInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperInitRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperInitRequest.Merge(dst, src)
}
func (m *AddressMapperInitRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperInitRequest.Size(m)
}
func (m *AddressMapperInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperInitRequest proto.InternalMessageInfo

type AddressMapperAddIdentityMappingRequest struct {
	// Address on a blockchain
	From *types.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	// Corresponding address on another blockchain
	To *types.Address `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	// Signature of a hash of the two addresses signed with the key that corresponds to the foreign address
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressMapperAddIdentityMappingRequest) Reset() {
	*m = AddressMapperAddIdentityMappingRequest{}
}
func (m *AddressMapperAddIdentityMappingRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperAddIdentityMappingRequest) ProtoMessage()    {}
func (*AddressMapperAddIdentityMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{9}
}
func (m *AddressMapperAddIdentityMappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperAddIdentityMappingRequest.Unmarshal(m, b)
}
func (m *AddressMapperAddIdentityMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperAddIdentityMappingRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperAddIdentityMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperAddIdentityMappingRequest.Merge(dst, src)
}
func (m *AddressMapperAddIdentityMappingRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperAddIdentityMappingRequest.Size(m)
}
func (m *AddressMapperAddIdentityMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperAddIdentityMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperAddIdentityMappingRequest proto.InternalMessageInfo

func (m *AddressMapperAddIdentityMappingRequest) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *AddressMapperAddIdentityMappingRequest) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *AddressMapperAddIdentityMappingRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type AddressMapperRemoveMappingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressMapperRemoveMappingRequest) Reset()         { *m = AddressMapperRemoveMappingRequest{} }
func (m *AddressMapperRemoveMappingRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperRemoveMappingRequest) ProtoMessage()    {}
func (*AddressMapperRemoveMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{10}
}
func (m *AddressMapperRemoveMappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperRemoveMappingRequest.Unmarshal(m, b)
}
func (m *AddressMapperRemoveMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperRemoveMappingRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperRemoveMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperRemoveMappingRequest.Merge(dst, src)
}
func (m *AddressMapperRemoveMappingRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperRemoveMappingRequest.Size(m)
}
func (m *AddressMapperRemoveMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperRemoveMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperRemoveMappingRequest proto.InternalMessageInfo

type AddressMapperGetMappingRequest struct {
	From                 *types.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperGetMappingRequest) Reset()         { *m = AddressMapperGetMappingRequest{} }
func (m *AddressMapperGetMappingRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperGetMappingRequest) ProtoMessage()    {}
func (*AddressMapperGetMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{11}
}
func (m *AddressMapperGetMappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperGetMappingRequest.Unmarshal(m, b)
}
func (m *AddressMapperGetMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperGetMappingRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperGetMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperGetMappingRequest.Merge(dst, src)
}
func (m *AddressMapperGetMappingRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperGetMappingRequest.Size(m)
}
func (m *AddressMapperGetMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperGetMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperGetMappingRequest proto.InternalMessageInfo

func (m *AddressMapperGetMappingRequest) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

type AddressMapperGetMappingResponse struct {
	From                 *types.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To                   *types.Address `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperGetMappingResponse) Reset()         { *m = AddressMapperGetMappingResponse{} }
func (m *AddressMapperGetMappingResponse) String() string { return proto.CompactTextString(m) }
func (*AddressMapperGetMappingResponse) ProtoMessage()    {}
func (*AddressMapperGetMappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{12}
}
func (m *AddressMapperGetMappingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperGetMappingResponse.Unmarshal(m, b)
}
func (m *AddressMapperGetMappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperGetMappingResponse.Marshal(b, m, deterministic)
}
func (dst *AddressMapperGetMappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperGetMappingResponse.Merge(dst, src)
}
func (m *AddressMapperGetMappingResponse) XXX_Size() int {
	return xxx_messageInfo_AddressMapperGetMappingResponse.Size(m)
}
func (m *AddressMapperGetMappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperGetMappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperGetMappingResponse proto.InternalMessageInfo

func (m *AddressMapperGetMappingResponse) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *AddressMapperGetMappingResponse) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

type AddressMapperListMappingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressMapperListMappingRequest) Reset()         { *m = AddressMapperListMappingRequest{} }
func (m *AddressMapperListMappingRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperListMappingRequest) ProtoMessage()    {}
func (*AddressMapperListMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{13}
}
func (m *AddressMapperListMappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperListMappingRequest.Unmarshal(m, b)
}
func (m *AddressMapperListMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperListMappingRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperListMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperListMappingRequest.Merge(dst, src)
}
func (m *AddressMapperListMappingRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperListMappingRequest.Size(m)
}
func (m *AddressMapperListMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperListMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperListMappingRequest proto.InternalMessageInfo

type AddressMapperListMappingResponse struct {
	Mappings             []*AddressMapperMapping `protobuf:"bytes,1,rep,name=mappings" json:"mappings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AddressMapperListMappingResponse) Reset()         { *m = AddressMapperListMappingResponse{} }
func (m *AddressMapperListMappingResponse) String() string { return proto.CompactTextString(m) }
func (*AddressMapperListMappingResponse) ProtoMessage()    {}
func (*AddressMapperListMappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{14}
}
func (m *AddressMapperListMappingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperListMappingResponse.Unmarshal(m, b)
}
func (m *AddressMapperListMappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperListMappingResponse.Marshal(b, m, deterministic)
}
func (dst *AddressMapperListMappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperListMappingResponse.Merge(dst, src)
}
func (m *AddressMapperListMappingResponse) XXX_Size() int {
	return xxx_messageInfo_AddressMapperListMappingResponse.Size(m)
}
func (m *AddressMapperListMappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperListMappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperListMappingResponse proto.InternalMessageInfo

func (m *AddressMapperListMappingResponse) GetMappings() []*AddressMapperMapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

type AddressMapperHasMappingRequest struct {
	From                 *types.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressMapperHasMappingRequest) Reset()         { *m = AddressMapperHasMappingRequest{} }
func (m *AddressMapperHasMappingRequest) String() string { return proto.CompactTextString(m) }
func (*AddressMapperHasMappingRequest) ProtoMessage()    {}
func (*AddressMapperHasMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{15}
}
func (m *AddressMapperHasMappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperHasMappingRequest.Unmarshal(m, b)
}
func (m *AddressMapperHasMappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperHasMappingRequest.Marshal(b, m, deterministic)
}
func (dst *AddressMapperHasMappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperHasMappingRequest.Merge(dst, src)
}
func (m *AddressMapperHasMappingRequest) XXX_Size() int {
	return xxx_messageInfo_AddressMapperHasMappingRequest.Size(m)
}
func (m *AddressMapperHasMappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperHasMappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperHasMappingRequest proto.InternalMessageInfo

func (m *AddressMapperHasMappingRequest) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

type AddressMapperHasMappingResponse struct {
	HasMapping           bool     `protobuf:"varint,1,opt,name=has_mapping,json=hasMapping,proto3" json:"has_mapping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressMapperHasMappingResponse) Reset()         { *m = AddressMapperHasMappingResponse{} }
func (m *AddressMapperHasMappingResponse) String() string { return proto.CompactTextString(m) }
func (*AddressMapperHasMappingResponse) ProtoMessage()    {}
func (*AddressMapperHasMappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_mapper_a116edb8efde1905, []int{16}
}
func (m *AddressMapperHasMappingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMapperHasMappingResponse.Unmarshal(m, b)
}
func (m *AddressMapperHasMappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMapperHasMappingResponse.Marshal(b, m, deterministic)
}
func (dst *AddressMapperHasMappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMapperHasMappingResponse.Merge(dst, src)
}
func (m *AddressMapperHasMappingResponse) XXX_Size() int {
	return xxx_messageInfo_AddressMapperHasMappingResponse.Size(m)
}
func (m *AddressMapperHasMappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMapperHasMappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMapperHasMappingResponse proto.InternalMessageInfo

func (m *AddressMapperHasMappingResponse) GetHasMapping() bool {
	if m != nil {
		return m.HasMapping
	}
	return false
}

func init() {
	proto.RegisterType((*AddressMapperMapping)(nil), "AddressMapperMapping")
	proto.RegisterType((*ListAddressMapperMapping)(nil), "ListAddressMapperMapping")
	proto.RegisterType((*AddressMapperGetMultichainMappingRequest)(nil), "AddressMapperGetMultichainMappingRequest")
	proto.RegisterType((*AddressMapperGetMultichainMappingResponse)(nil), "AddressMapperGetMultichainMappingResponse")
	proto.RegisterType((*AddressMapperSetNonceRequest)(nil), "AddressMapperSetNonceRequest")
	proto.RegisterType((*AddressMapperGetNonceRequest)(nil), "AddressMapperGetNonceRequest")
	proto.RegisterType((*AddressMapperGetNonceResponse)(nil), "AddressMapperGetNonceResponse")
	proto.RegisterType((*AddressMapperNonce)(nil), "AddressMapperNonce")
	proto.RegisterType((*AddressMapperInitRequest)(nil), "AddressMapperInitRequest")
	proto.RegisterType((*AddressMapperAddIdentityMappingRequest)(nil), "AddressMapperAddIdentityMappingRequest")
	proto.RegisterType((*AddressMapperRemoveMappingRequest)(nil), "AddressMapperRemoveMappingRequest")
	proto.RegisterType((*AddressMapperGetMappingRequest)(nil), "AddressMapperGetMappingRequest")
	proto.RegisterType((*AddressMapperGetMappingResponse)(nil), "AddressMapperGetMappingResponse")
	proto.RegisterType((*AddressMapperListMappingRequest)(nil), "AddressMapperListMappingRequest")
	proto.RegisterType((*AddressMapperListMappingResponse)(nil), "AddressMapperListMappingResponse")
	proto.RegisterType((*AddressMapperHasMappingRequest)(nil), "AddressMapperHasMappingRequest")
	proto.RegisterType((*AddressMapperHasMappingResponse)(nil), "AddressMapperHasMappingResponse")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/builtin/types/address_mapper/address_mapper.proto", fileDescriptor_address_mapper_a116edb8efde1905)
}

var fileDescriptor_address_mapper_a116edb8efde1905 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x8f, 0x93, 0x40,
	0x14, 0xc6, 0x43, 0x77, 0x75, 0xbb, 0xaf, 0x9e, 0xc8, 0x9a, 0x90, 0x4d, 0xb5, 0x74, 0x4c, 0x0c,
	0x1e, 0x04, 0xad, 0x77, 0x93, 0xf6, 0x52, 0x9b, 0xd8, 0xc6, 0x60, 0x3c, 0xf4, 0xa2, 0x81, 0x32,
	0xc2, 0xc4, 0x32, 0x83, 0xcc, 0x43, 0xd3, 0x8b, 0x7f, 0xbb, 0x61, 0x80, 0x2a, 0xb4, 0xa4, 0x2d,
	0x7b, 0x21, 0xbc, 0x99, 0xef, 0xfd, 0xe6, 0x9b, 0x99, 0xf7, 0x06, 0x3e, 0x85, 0x0c, 0xa3, 0xcc,
	0xb7, 0x37, 0x22, 0x76, 0xb6, 0x42, 0xc4, 0x9c, 0xe2, 0x6f, 0x91, 0xfe, 0x70, 0x42, 0xf1, 0x3a,
	0x0f, 0x1d, 0x3f, 0x63, 0x5b, 0x64, 0xdc, 0xc1, 0x5d, 0x42, 0xa5, 0xe3, 0x05, 0x41, 0x4a, 0xa5,
	0xfc, 0x16, 0x7b, 0x49, 0x42, 0xd3, 0x46, 0x68, 0x27, 0xa9, 0x40, 0x71, 0xff, 0xe6, 0x04, 0xb1,
	0x20, 0xa9, 0x6f, 0x91, 0x41, 0x56, 0x70, 0x37, 0x2d, 0x48, 0x4b, 0x05, 0xca, 0xbf, 0x8c, 0x87,
	0xfa, 0x10, 0xae, 0xbf, 0xa7, 0x22, 0x36, 0x34, 0x53, 0xb3, 0x06, 0x93, 0xbe, 0x5d, 0x8a, 0x5c,
	0x35, 0xaa, 0x1b, 0xd0, 0x43, 0x61, 0xf4, 0x1a, 0x73, 0x3d, 0x14, 0x64, 0x09, 0xc6, 0x47, 0x26,
	0xf1, 0x28, 0xf3, 0x2d, 0xf4, 0xe3, 0xe2, 0x57, 0x1a, 0x9a, 0x79, 0x65, 0x0d, 0x26, 0x4f, 0xed,
	0x63, 0x42, 0x77, 0x2f, 0x23, 0x3e, 0x58, 0x35, 0xc5, 0x9c, 0xe2, 0x32, 0xdb, 0x22, 0xdb, 0x44,
	0x1e, 0xe3, 0x95, 0x9c, 0xfe, 0xcc, 0xa8, 0xc4, 0x93, 0x96, 0x6f, 0x54, 0xd2, 0x22, 0x50, 0xbe,
	0x6f, 0xdd, 0x2a, 0x24, 0x5f, 0xe1, 0xd5, 0x19, 0x6b, 0xc8, 0x44, 0x70, 0x49, 0xbb, 0xec, 0x61,
	0x06, 0xc3, 0x9a, 0xe2, 0x33, 0xc5, 0x95, 0xe0, 0x1b, 0x5a, 0xf9, 0x26, 0x70, 0x53, 0x5e, 0xe6,
	0x81, 0xf5, 0x6a, 0xe2, 0x80, 0x31, 0xef, 0xc0, 0x58, 0xc3, 0xb3, 0x16, 0x46, 0xb9, 0xb7, 0x33,
	0x20, 0xfa, 0x1d, 0x3c, 0xe2, 0x79, 0x92, 0x3a, 0xc4, 0x6b, 0xb7, 0x08, 0xc8, 0x0a, 0xf4, 0x1a,
	0x5a, 0x71, 0x1f, 0xc0, 0xbb, 0x07, 0xa3, 0xc6, 0x5b, 0x70, 0x86, 0xe5, 0x56, 0xc9, 0x1f, 0x78,
	0x59, 0x9b, 0x9b, 0x06, 0xc1, 0x22, 0xa0, 0x1c, 0x19, 0xee, 0x2e, 0x2c, 0x88, 0x96, 0x1a, 0xd6,
	0x87, 0x70, 0x2b, 0x59, 0xc8, 0x3d, 0xcc, 0x52, 0x6a, 0x5c, 0x99, 0x9a, 0xf5, 0xc4, 0xfd, 0x37,
	0x40, 0x5e, 0xc0, 0xb8, 0xb6, 0xbe, 0x4b, 0x63, 0xf1, 0x8b, 0xd6, 0x97, 0x26, 0xef, 0xe1, 0xf9,
	0x41, 0x4d, 0x5d, 0x60, 0x8e, 0xac, 0x61, 0xd4, 0x9a, 0x5f, 0xde, 0x56, 0xd7, 0x0e, 0x1d, 0x37,
	0xd0, 0x79, 0xbb, 0x36, 0xdc, 0x7f, 0x01, 0xb3, 0x5d, 0xd2, 0xbd, 0x11, 0x9a, 0x87, 0xf2, 0xc1,
	0x93, 0x17, 0x1d, 0xca, 0xac, 0xe1, 0xfc, 0xff, 0xfc, 0xd2, 0xd5, 0x08, 0x06, 0x91, 0x57, 0x3c,
	0x8a, 0x8c, 0x87, 0x8a, 0xd3, 0x77, 0x21, 0xda, 0x0b, 0xfd, 0xc7, 0xea, 0xd9, 0x7b, 0xf7, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x05, 0xd7, 0x38, 0xeb, 0x7c, 0x05, 0x00, 0x00,
}
