// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/builtin/types/transfer_gateway/transfer_gateway.proto

/*
Package transfer_gateway is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/go-loom/builtin/types/transfer_gateway/transfer_gateway.proto

It has these top-level messages:
	TransferGatewayState
	TransferGatewayOracleState
	TransferGatewayWithdrawalReceipt
	TransferGatewayPendingWithdrawalSummary
	TransferGatewayAccount
	TransferGatewayTokenDeposited
	TransferGatewayTokenWithdrawn
	TransferGatewayMainnetEvent
	TransferGatewayPendingContractMapping
	TransferGatewayContractAddressMapping
	TransferGatewayUnverifiedContractCreator
	TransferGatewayVerifiedContractCreator
	TransferGatewayContractMappingConfirmed
	TransferGatewayTokenWithdrawalSigned
	TransferGatewayInitRequest
	TransferGatewayAddOracleRequest
	TransferGatewayRemoveOracleRequest
	TransferGatewayGetOraclesRequest
	TransferGatewayGetOraclesResponse
	TransferGatewayAddContractMappingRequest
	TransferGatewayUnverifiedContractCreatorsRequest
	TransferGatewayUnverifiedContractCreatorsResponse
	TransferGatewayVerifyContractCreatorsRequest
	TransferGatewayProcessEventBatchRequest
	TransferGatewayStateRequest
	TransferGatewayStateResponse
	TransferGatewayWithdrawERC721Request
	TransferGatewayWithdrawalReceiptRequest
	TransferGatewayWithdrawalReceiptResponse
	TransferGatewayConfirmWithdrawalReceiptRequest
	TransferGatewayPendingWithdrawalsRequest
	TransferGatewayPendingWithdrawalsResponse
*/
package transfer_gateway

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TransferGatewayTokenKind int32

const (
	TransferGatewayTokenKind_ETH    TransferGatewayTokenKind = 0
	TransferGatewayTokenKind_ERC20  TransferGatewayTokenKind = 1
	TransferGatewayTokenKind_ERC721 TransferGatewayTokenKind = 2
)

var TransferGatewayTokenKind_name = map[int32]string{
	0: "ETH",
	1: "ERC20",
	2: "ERC721",
}
var TransferGatewayTokenKind_value = map[string]int32{
	"ETH":    0,
	"ERC20":  1,
	"ERC721": 2,
}

func (x TransferGatewayTokenKind) String() string {
	return proto.EnumName(TransferGatewayTokenKind_name, int32(x))
}
func (TransferGatewayTokenKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{0}
}

type TransferGatewayState struct {
	Owner *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	// Last Mainnet block processed by the Transfer Gateway contract
	LastMainnetBlockNum uint64 `protobuf:"varint,2,opt,name=last_mainnet_block_num,json=lastMainnetBlockNum,proto3" json:"last_mainnet_block_num,omitempty"`
	// ID that should be used for the next pending contract mapping
	NextContractMappingID uint64 `protobuf:"varint,3,opt,name=next_contract_mapping_id,json=nextContractMappingId,proto3" json:"next_contract_mapping_id,omitempty"`
	// Token owners that have initiated (but have not as yet completed) a withdrawal to Mainnet.
	TokenWithdrawers []*types.Address `protobuf:"bytes,4,rep,name=token_withdrawers,json=tokenWithdrawers" json:"token_withdrawers,omitempty"`
}

func (m *TransferGatewayState) Reset()         { *m = TransferGatewayState{} }
func (m *TransferGatewayState) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayState) ProtoMessage()    {}
func (*TransferGatewayState) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{0}
}

func (m *TransferGatewayState) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *TransferGatewayState) GetLastMainnetBlockNum() uint64 {
	if m != nil {
		return m.LastMainnetBlockNum
	}
	return 0
}

func (m *TransferGatewayState) GetNextContractMappingID() uint64 {
	if m != nil {
		return m.NextContractMappingID
	}
	return 0
}

func (m *TransferGatewayState) GetTokenWithdrawers() []*types.Address {
	if m != nil {
		return m.TokenWithdrawers
	}
	return nil
}

type TransferGatewayOracleState struct {
	// DAppChain address of the Oracle
	Address *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *TransferGatewayOracleState) Reset()         { *m = TransferGatewayOracleState{} }
func (m *TransferGatewayOracleState) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayOracleState) ProtoMessage()    {}
func (*TransferGatewayOracleState) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{1}
}

func (m *TransferGatewayOracleState) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type TransferGatewayWithdrawalReceipt struct {
	// Mainnet address of token owner
	TokenOwner *types.Address `protobuf:"bytes,1,opt,name=token_owner,json=tokenOwner" json:"token_owner,omitempty"`
	// Mainnet address of token contract
	TokenContract *types.Address           `protobuf:"bytes,2,opt,name=token_contract,json=tokenContract" json:"token_contract,omitempty"`
	TokenKind     TransferGatewayTokenKind `protobuf:"varint,3,opt,name=token_kind,json=tokenKind,proto3,enum=TransferGatewayTokenKind" json:"token_kind,omitempty"`
	// // ERC721 token ID, or amount of ERC20/ETH
	Value           *types.BigUInt `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	WithdrawalNonce uint64         `protobuf:"varint,5,opt,name=withdrawal_nonce,json=withdrawalNonce,proto3" json:"withdrawal_nonce,omitempty"`
	// Signature generated by the Oracle that confirmed the withdrawal
	OracleSignature []byte `protobuf:"bytes,6,opt,name=oracle_signature,json=oracleSignature,proto3" json:"oracle_signature,omitempty"`
}

func (m *TransferGatewayWithdrawalReceipt) Reset()         { *m = TransferGatewayWithdrawalReceipt{} }
func (m *TransferGatewayWithdrawalReceipt) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayWithdrawalReceipt) ProtoMessage()    {}
func (*TransferGatewayWithdrawalReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{2}
}

func (m *TransferGatewayWithdrawalReceipt) GetTokenOwner() *types.Address {
	if m != nil {
		return m.TokenOwner
	}
	return nil
}

func (m *TransferGatewayWithdrawalReceipt) GetTokenContract() *types.Address {
	if m != nil {
		return m.TokenContract
	}
	return nil
}

func (m *TransferGatewayWithdrawalReceipt) GetTokenKind() TransferGatewayTokenKind {
	if m != nil {
		return m.TokenKind
	}
	return TransferGatewayTokenKind_ETH
}

func (m *TransferGatewayWithdrawalReceipt) GetValue() *types.BigUInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransferGatewayWithdrawalReceipt) GetWithdrawalNonce() uint64 {
	if m != nil {
		return m.WithdrawalNonce
	}
	return 0
}

func (m *TransferGatewayWithdrawalReceipt) GetOracleSignature() []byte {
	if m != nil {
		return m.OracleSignature
	}
	return nil
}

type TransferGatewayPendingWithdrawalSummary struct {
	// DAppChain address of token owner
	TokenOwner *types.Address `protobuf:"bytes,1,opt,name=token_owner,json=tokenOwner" json:"token_owner,omitempty"`
	// Hash of the unsigned withdrawal receipt
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *TransferGatewayPendingWithdrawalSummary) Reset() {
	*m = TransferGatewayPendingWithdrawalSummary{}
}
func (m *TransferGatewayPendingWithdrawalSummary) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayPendingWithdrawalSummary) ProtoMessage()    {}
func (*TransferGatewayPendingWithdrawalSummary) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{3}
}

func (m *TransferGatewayPendingWithdrawalSummary) GetTokenOwner() *types.Address {
	if m != nil {
		return m.TokenOwner
	}
	return nil
}

func (m *TransferGatewayPendingWithdrawalSummary) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type TransferGatewayAccount struct {
	Owner             *types.Address                    `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	WithdrawalNonce   uint64                            `protobuf:"varint,2,opt,name=withdrawal_nonce,json=withdrawalNonce,proto3" json:"withdrawal_nonce,omitempty"`
	WithdrawalReceipt *TransferGatewayWithdrawalReceipt `protobuf:"bytes,3,opt,name=withdrawal_receipt,json=withdrawalReceipt" json:"withdrawal_receipt,omitempty"`
}

func (m *TransferGatewayAccount) Reset()         { *m = TransferGatewayAccount{} }
func (m *TransferGatewayAccount) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayAccount) ProtoMessage()    {}
func (*TransferGatewayAccount) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{4}
}

func (m *TransferGatewayAccount) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *TransferGatewayAccount) GetWithdrawalNonce() uint64 {
	if m != nil {
		return m.WithdrawalNonce
	}
	return 0
}

func (m *TransferGatewayAccount) GetWithdrawalReceipt() *TransferGatewayWithdrawalReceipt {
	if m != nil {
		return m.WithdrawalReceipt
	}
	return nil
}

// Token Deposit (ETH/ERC20/ERC721) made into the Mainnet Gateway
type TransferGatewayTokenDeposited struct {
	// Mainnet address of token owner
	TokenOwner *types.Address `protobuf:"bytes,1,opt,name=token_owner,json=tokenOwner" json:"token_owner,omitempty"`
	// Mainnet address of token contract, blank if ETH was deposited
	TokenContract *types.Address           `protobuf:"bytes,2,opt,name=token_contract,json=tokenContract" json:"token_contract,omitempty"`
	TokenKind     TransferGatewayTokenKind `protobuf:"varint,3,opt,name=token_kind,json=tokenKind,proto3,enum=TransferGatewayTokenKind" json:"token_kind,omitempty"`
	// ERC721 token ID, or amount of ERC20/ETH
	Value *types.BigUInt `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *TransferGatewayTokenDeposited) Reset()         { *m = TransferGatewayTokenDeposited{} }
func (m *TransferGatewayTokenDeposited) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayTokenDeposited) ProtoMessage()    {}
func (*TransferGatewayTokenDeposited) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{5}
}

func (m *TransferGatewayTokenDeposited) GetTokenOwner() *types.Address {
	if m != nil {
		return m.TokenOwner
	}
	return nil
}

func (m *TransferGatewayTokenDeposited) GetTokenContract() *types.Address {
	if m != nil {
		return m.TokenContract
	}
	return nil
}

func (m *TransferGatewayTokenDeposited) GetTokenKind() TransferGatewayTokenKind {
	if m != nil {
		return m.TokenKind
	}
	return TransferGatewayTokenKind_ETH
}

func (m *TransferGatewayTokenDeposited) GetValue() *types.BigUInt {
	if m != nil {
		return m.Value
	}
	return nil
}

// Withdrawal from Mainnet Transfer Gateway
type TransferGatewayTokenWithdrawn struct {
	// Mainnet address of token owner
	TokenOwner *types.Address `protobuf:"bytes,1,opt,name=token_owner,json=tokenOwner" json:"token_owner,omitempty"`
	// Mainnet address of token contract, blank if ETH was withdrawn
	TokenContract *types.Address           `protobuf:"bytes,2,opt,name=token_contract,json=tokenContract" json:"token_contract,omitempty"`
	TokenKind     TransferGatewayTokenKind `protobuf:"varint,3,opt,name=token_kind,json=tokenKind,proto3,enum=TransferGatewayTokenKind" json:"token_kind,omitempty"`
	// ERC721 token ID, or amount of ERC20/ETH
	Value *types.BigUInt `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *TransferGatewayTokenWithdrawn) Reset()         { *m = TransferGatewayTokenWithdrawn{} }
func (m *TransferGatewayTokenWithdrawn) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayTokenWithdrawn) ProtoMessage()    {}
func (*TransferGatewayTokenWithdrawn) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{6}
}

func (m *TransferGatewayTokenWithdrawn) GetTokenOwner() *types.Address {
	if m != nil {
		return m.TokenOwner
	}
	return nil
}

func (m *TransferGatewayTokenWithdrawn) GetTokenContract() *types.Address {
	if m != nil {
		return m.TokenContract
	}
	return nil
}

func (m *TransferGatewayTokenWithdrawn) GetTokenKind() TransferGatewayTokenKind {
	if m != nil {
		return m.TokenKind
	}
	return TransferGatewayTokenKind_ETH
}

func (m *TransferGatewayTokenWithdrawn) GetValue() *types.BigUInt {
	if m != nil {
		return m.Value
	}
	return nil
}

type TransferGatewayMainnetEvent struct {
	EthBlock uint64 `protobuf:"varint,1,opt,name=eth_block,json=ethBlock,proto3" json:"eth_block,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*TransferGatewayMainnetEvent_Deposit
	//	*TransferGatewayMainnetEvent_Withdrawal
	Payload isTransferGatewayMainnetEvent_Payload `protobuf_oneof:"payload"`
}

func (m *TransferGatewayMainnetEvent) Reset()         { *m = TransferGatewayMainnetEvent{} }
func (m *TransferGatewayMainnetEvent) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayMainnetEvent) ProtoMessage()    {}
func (*TransferGatewayMainnetEvent) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{7}
}

type isTransferGatewayMainnetEvent_Payload interface {
	isTransferGatewayMainnetEvent_Payload()
}

type TransferGatewayMainnetEvent_Deposit struct {
	Deposit *TransferGatewayTokenDeposited `protobuf:"bytes,2,opt,name=deposit,oneof"`
}
type TransferGatewayMainnetEvent_Withdrawal struct {
	Withdrawal *TransferGatewayTokenWithdrawn `protobuf:"bytes,3,opt,name=withdrawal,oneof"`
}

func (*TransferGatewayMainnetEvent_Deposit) isTransferGatewayMainnetEvent_Payload()    {}
func (*TransferGatewayMainnetEvent_Withdrawal) isTransferGatewayMainnetEvent_Payload() {}

func (m *TransferGatewayMainnetEvent) GetPayload() isTransferGatewayMainnetEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TransferGatewayMainnetEvent) GetEthBlock() uint64 {
	if m != nil {
		return m.EthBlock
	}
	return 0
}

func (m *TransferGatewayMainnetEvent) GetDeposit() *TransferGatewayTokenDeposited {
	if x, ok := m.GetPayload().(*TransferGatewayMainnetEvent_Deposit); ok {
		return x.Deposit
	}
	return nil
}

func (m *TransferGatewayMainnetEvent) GetWithdrawal() *TransferGatewayTokenWithdrawn {
	if x, ok := m.GetPayload().(*TransferGatewayMainnetEvent_Withdrawal); ok {
		return x.Withdrawal
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TransferGatewayMainnetEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TransferGatewayMainnetEvent_OneofMarshaler, _TransferGatewayMainnetEvent_OneofUnmarshaler, _TransferGatewayMainnetEvent_OneofSizer, []interface{}{
		(*TransferGatewayMainnetEvent_Deposit)(nil),
		(*TransferGatewayMainnetEvent_Withdrawal)(nil),
	}
}

func _TransferGatewayMainnetEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TransferGatewayMainnetEvent)
	// payload
	switch x := m.Payload.(type) {
	case *TransferGatewayMainnetEvent_Deposit:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Deposit); err != nil {
			return err
		}
	case *TransferGatewayMainnetEvent_Withdrawal:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Withdrawal); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TransferGatewayMainnetEvent.Payload has unexpected type %T", x)
	}
	return nil
}

func _TransferGatewayMainnetEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TransferGatewayMainnetEvent)
	switch tag {
	case 2: // payload.deposit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TransferGatewayTokenDeposited)
		err := b.DecodeMessage(msg)
		m.Payload = &TransferGatewayMainnetEvent_Deposit{msg}
		return true, err
	case 3: // payload.withdrawal
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TransferGatewayTokenWithdrawn)
		err := b.DecodeMessage(msg)
		m.Payload = &TransferGatewayMainnetEvent_Withdrawal{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TransferGatewayMainnetEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TransferGatewayMainnetEvent)
	// payload
	switch x := m.Payload.(type) {
	case *TransferGatewayMainnetEvent_Deposit:
		s := proto.Size(x.Deposit)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TransferGatewayMainnetEvent_Withdrawal:
		s := proto.Size(x.Withdrawal)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TransferGatewayPendingContractMapping struct {
	ID uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Address on foreign blockchain
	ForeignContract *types.Address `protobuf:"bytes,2,opt,name=foreign_contract,json=foreignContract" json:"foreign_contract,omitempty"`
	// Corresponding address on local blockchain
	LocalContract *types.Address `protobuf:"bytes,3,opt,name=local_contract,json=localContract" json:"local_contract,omitempty"`
	// Foreign address of the creator of the foreign contract
	ForeignContractCreator *types.Address `protobuf:"bytes,4,opt,name=foreign_contract_creator,json=foreignContractCreator" json:"foreign_contract_creator,omitempty"`
	// Hash of the transaction which created the foreign contract
	ForeignContractTxHash []byte `protobuf:"bytes,5,opt,name=foreign_contract_tx_hash,json=foreignContractTxHash,proto3" json:"foreign_contract_tx_hash,omitempty"`
}

func (m *TransferGatewayPendingContractMapping) Reset()         { *m = TransferGatewayPendingContractMapping{} }
func (m *TransferGatewayPendingContractMapping) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayPendingContractMapping) ProtoMessage()    {}
func (*TransferGatewayPendingContractMapping) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{8}
}

func (m *TransferGatewayPendingContractMapping) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TransferGatewayPendingContractMapping) GetForeignContract() *types.Address {
	if m != nil {
		return m.ForeignContract
	}
	return nil
}

func (m *TransferGatewayPendingContractMapping) GetLocalContract() *types.Address {
	if m != nil {
		return m.LocalContract
	}
	return nil
}

func (m *TransferGatewayPendingContractMapping) GetForeignContractCreator() *types.Address {
	if m != nil {
		return m.ForeignContractCreator
	}
	return nil
}

func (m *TransferGatewayPendingContractMapping) GetForeignContractTxHash() []byte {
	if m != nil {
		return m.ForeignContractTxHash
	}
	return nil
}

type TransferGatewayContractAddressMapping struct {
	// Address on a blockchain
	From *types.Address `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	// Corresponding address on another blockchain
	To *types.Address `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
}

func (m *TransferGatewayContractAddressMapping) Reset()         { *m = TransferGatewayContractAddressMapping{} }
func (m *TransferGatewayContractAddressMapping) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayContractAddressMapping) ProtoMessage()    {}
func (*TransferGatewayContractAddressMapping) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{9}
}

func (m *TransferGatewayContractAddressMapping) GetFrom() *types.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransferGatewayContractAddressMapping) GetTo() *types.Address {
	if m != nil {
		return m.To
	}
	return nil
}

type TransferGatewayUnverifiedContractCreator struct {
	ContractMappingID uint64 `protobuf:"varint,1,opt,name=contract_mapping_id,json=contractMappingId,proto3" json:"contract_mapping_id,omitempty"`
	// Hash of tx that created a contract, an Oracle will use this to lookup the creator & contract
	ContractTxHash []byte `protobuf:"bytes,2,opt,name=contract_tx_hash,json=contractTxHash,proto3" json:"contract_tx_hash,omitempty"`
}

func (m *TransferGatewayUnverifiedContractCreator) Reset() {
	*m = TransferGatewayUnverifiedContractCreator{}
}
func (m *TransferGatewayUnverifiedContractCreator) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayUnverifiedContractCreator) ProtoMessage()    {}
func (*TransferGatewayUnverifiedContractCreator) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{10}
}

func (m *TransferGatewayUnverifiedContractCreator) GetContractMappingID() uint64 {
	if m != nil {
		return m.ContractMappingID
	}
	return 0
}

func (m *TransferGatewayUnverifiedContractCreator) GetContractTxHash() []byte {
	if m != nil {
		return m.ContractTxHash
	}
	return nil
}

type TransferGatewayVerifiedContractCreator struct {
	ContractMappingID uint64         `protobuf:"varint,1,opt,name=contract_mapping_id,json=contractMappingId,proto3" json:"contract_mapping_id,omitempty"`
	Creator           *types.Address `protobuf:"bytes,2,opt,name=creator" json:"creator,omitempty"`
	Contract          *types.Address `protobuf:"bytes,3,opt,name=contract" json:"contract,omitempty"`
}

func (m *TransferGatewayVerifiedContractCreator) Reset() {
	*m = TransferGatewayVerifiedContractCreator{}
}
func (m *TransferGatewayVerifiedContractCreator) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayVerifiedContractCreator) ProtoMessage()    {}
func (*TransferGatewayVerifiedContractCreator) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{11}
}

func (m *TransferGatewayVerifiedContractCreator) GetContractMappingID() uint64 {
	if m != nil {
		return m.ContractMappingID
	}
	return 0
}

func (m *TransferGatewayVerifiedContractCreator) GetCreator() *types.Address {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *TransferGatewayVerifiedContractCreator) GetContract() *types.Address {
	if m != nil {
		return m.Contract
	}
	return nil
}

type TransferGatewayContractMappingConfirmed struct {
	// Address of a contract on a foreign blockchain
	ForeignContract *types.Address `protobuf:"bytes,1,opt,name=foreign_contract,json=foreignContract" json:"foreign_contract,omitempty"`
	// Address of corresponding contract on the local blockchain
	LocalContract *types.Address `protobuf:"bytes,2,opt,name=local_contract,json=localContract" json:"local_contract,omitempty"`
}

func (m *TransferGatewayContractMappingConfirmed) Reset() {
	*m = TransferGatewayContractMappingConfirmed{}
}
func (m *TransferGatewayContractMappingConfirmed) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayContractMappingConfirmed) ProtoMessage()    {}
func (*TransferGatewayContractMappingConfirmed) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{12}
}

func (m *TransferGatewayContractMappingConfirmed) GetForeignContract() *types.Address {
	if m != nil {
		return m.ForeignContract
	}
	return nil
}

func (m *TransferGatewayContractMappingConfirmed) GetLocalContract() *types.Address {
	if m != nil {
		return m.LocalContract
	}
	return nil
}

// Emitted when a withdrawal to the Mainnet Gateway has been signed.
// This event contains all the required data to complete a toke withdrawal via the Mainnet Gateway.
type TransferGatewayTokenWithdrawalSigned struct {
	// Mainnet address of token owner
	TokenOwner *types.Address `protobuf:"bytes,1,opt,name=token_owner,json=tokenOwner" json:"token_owner,omitempty"`
	// Mainnet address of token contract, blank if ETH
	TokenContract *types.Address           `protobuf:"bytes,2,opt,name=token_contract,json=tokenContract" json:"token_contract,omitempty"`
	TokenKind     TransferGatewayTokenKind `protobuf:"varint,3,opt,name=token_kind,json=tokenKind,proto3,enum=TransferGatewayTokenKind" json:"token_kind,omitempty"`
	// ERC721 token ID, or amount of ERC20/ETH
	Value *types.BigUInt `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	// Oracle signature
	Sig []byte `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *TransferGatewayTokenWithdrawalSigned) Reset()         { *m = TransferGatewayTokenWithdrawalSigned{} }
func (m *TransferGatewayTokenWithdrawalSigned) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayTokenWithdrawalSigned) ProtoMessage()    {}
func (*TransferGatewayTokenWithdrawalSigned) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{13}
}

func (m *TransferGatewayTokenWithdrawalSigned) GetTokenOwner() *types.Address {
	if m != nil {
		return m.TokenOwner
	}
	return nil
}

func (m *TransferGatewayTokenWithdrawalSigned) GetTokenContract() *types.Address {
	if m != nil {
		return m.TokenContract
	}
	return nil
}

func (m *TransferGatewayTokenWithdrawalSigned) GetTokenKind() TransferGatewayTokenKind {
	if m != nil {
		return m.TokenKind
	}
	return TransferGatewayTokenKind_ETH
}

func (m *TransferGatewayTokenWithdrawalSigned) GetValue() *types.BigUInt {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransferGatewayTokenWithdrawalSigned) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type TransferGatewayInitRequest struct {
	// Only the owner will be allowed to add/remove oracles
	Owner *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	// List of oracles that the Gateway should accept data from
	Oracles []*types.Address `protobuf:"bytes,2,rep,name=oracles" json:"oracles,omitempty"`
	// Initial value for TransferGatewayState.last_mainnet_block_num,
	// Oracles will start looking for relevant Mainnet events from this block onwards.
	// Should be set to the Mainnet block number that immediately preceeded the block containing
	// the tx that deployed the Mainnet Gateway contract.
	FirstMainnetBlockNum uint64 `protobuf:"varint,3,opt,name=first_mainnet_block_num,json=firstMainnetBlockNum,proto3" json:"first_mainnet_block_num,omitempty"`
}

func (m *TransferGatewayInitRequest) Reset()         { *m = TransferGatewayInitRequest{} }
func (m *TransferGatewayInitRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayInitRequest) ProtoMessage()    {}
func (*TransferGatewayInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{14}
}

func (m *TransferGatewayInitRequest) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *TransferGatewayInitRequest) GetOracles() []*types.Address {
	if m != nil {
		return m.Oracles
	}
	return nil
}

func (m *TransferGatewayInitRequest) GetFirstMainnetBlockNum() uint64 {
	if m != nil {
		return m.FirstMainnetBlockNum
	}
	return 0
}

type TransferGatewayAddOracleRequest struct {
	Oracle *types.Address `protobuf:"bytes,1,opt,name=oracle" json:"oracle,omitempty"`
}

func (m *TransferGatewayAddOracleRequest) Reset()         { *m = TransferGatewayAddOracleRequest{} }
func (m *TransferGatewayAddOracleRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayAddOracleRequest) ProtoMessage()    {}
func (*TransferGatewayAddOracleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{15}
}

func (m *TransferGatewayAddOracleRequest) GetOracle() *types.Address {
	if m != nil {
		return m.Oracle
	}
	return nil
}

type TransferGatewayRemoveOracleRequest struct {
	Oracle *types.Address `protobuf:"bytes,1,opt,name=oracle" json:"oracle,omitempty"`
}

func (m *TransferGatewayRemoveOracleRequest) Reset()         { *m = TransferGatewayRemoveOracleRequest{} }
func (m *TransferGatewayRemoveOracleRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayRemoveOracleRequest) ProtoMessage()    {}
func (*TransferGatewayRemoveOracleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{16}
}

func (m *TransferGatewayRemoveOracleRequest) GetOracle() *types.Address {
	if m != nil {
		return m.Oracle
	}
	return nil
}

type TransferGatewayGetOraclesRequest struct {
}

func (m *TransferGatewayGetOraclesRequest) Reset()         { *m = TransferGatewayGetOraclesRequest{} }
func (m *TransferGatewayGetOraclesRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayGetOraclesRequest) ProtoMessage()    {}
func (*TransferGatewayGetOraclesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{17}
}

type TransferGatewayGetOraclesResponse struct {
	Oracles []*TransferGatewayOracleState `protobuf:"bytes,1,rep,name=oracles" json:"oracles,omitempty"`
}

func (m *TransferGatewayGetOraclesResponse) Reset()         { *m = TransferGatewayGetOraclesResponse{} }
func (m *TransferGatewayGetOraclesResponse) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayGetOraclesResponse) ProtoMessage()    {}
func (*TransferGatewayGetOraclesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{18}
}

func (m *TransferGatewayGetOraclesResponse) GetOracles() []*TransferGatewayOracleState {
	if m != nil {
		return m.Oracles
	}
	return nil
}

type TransferGatewayAddContractMappingRequest struct {
	// Address on foreign blockchain
	ForeignContract *types.Address `protobuf:"bytes,1,opt,name=foreign_contract,json=foreignContract" json:"foreign_contract,omitempty"`
	// Corresponding address on local blockchain
	LocalContract *types.Address `protobuf:"bytes,2,opt,name=local_contract,json=localContract" json:"local_contract,omitempty"`
	// Signature of the creator of the foreign contract
	ForeignContractCreatorSig []byte `protobuf:"bytes,3,opt,name=foreign_contract_creator_sig,json=foreignContractCreatorSig,proto3" json:"foreign_contract_creator_sig,omitempty"`
	// Hash of the transaction which created the foreign contract
	ForeignContractTxHash []byte `protobuf:"bytes,4,opt,name=foreign_contract_tx_hash,json=foreignContractTxHash,proto3" json:"foreign_contract_tx_hash,omitempty"`
}

func (m *TransferGatewayAddContractMappingRequest) Reset() {
	*m = TransferGatewayAddContractMappingRequest{}
}
func (m *TransferGatewayAddContractMappingRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayAddContractMappingRequest) ProtoMessage()    {}
func (*TransferGatewayAddContractMappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{19}
}

func (m *TransferGatewayAddContractMappingRequest) GetForeignContract() *types.Address {
	if m != nil {
		return m.ForeignContract
	}
	return nil
}

func (m *TransferGatewayAddContractMappingRequest) GetLocalContract() *types.Address {
	if m != nil {
		return m.LocalContract
	}
	return nil
}

func (m *TransferGatewayAddContractMappingRequest) GetForeignContractCreatorSig() []byte {
	if m != nil {
		return m.ForeignContractCreatorSig
	}
	return nil
}

func (m *TransferGatewayAddContractMappingRequest) GetForeignContractTxHash() []byte {
	if m != nil {
		return m.ForeignContractTxHash
	}
	return nil
}

type TransferGatewayUnverifiedContractCreatorsRequest struct {
}

func (m *TransferGatewayUnverifiedContractCreatorsRequest) Reset() {
	*m = TransferGatewayUnverifiedContractCreatorsRequest{}
}
func (m *TransferGatewayUnverifiedContractCreatorsRequest) String() string {
	return proto.CompactTextString(m)
}
func (*TransferGatewayUnverifiedContractCreatorsRequest) ProtoMessage() {}
func (*TransferGatewayUnverifiedContractCreatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{20}
}

type TransferGatewayUnverifiedContractCreatorsResponse struct {
	Creators []*TransferGatewayUnverifiedContractCreator `protobuf:"bytes,1,rep,name=creators" json:"creators,omitempty"`
}

func (m *TransferGatewayUnverifiedContractCreatorsResponse) Reset() {
	*m = TransferGatewayUnverifiedContractCreatorsResponse{}
}
func (m *TransferGatewayUnverifiedContractCreatorsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*TransferGatewayUnverifiedContractCreatorsResponse) ProtoMessage() {}
func (*TransferGatewayUnverifiedContractCreatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{21}
}

func (m *TransferGatewayUnverifiedContractCreatorsResponse) GetCreators() []*TransferGatewayUnverifiedContractCreator {
	if m != nil {
		return m.Creators
	}
	return nil
}

type TransferGatewayVerifyContractCreatorsRequest struct {
	Creators []*TransferGatewayVerifiedContractCreator `protobuf:"bytes,1,rep,name=creators" json:"creators,omitempty"`
}

func (m *TransferGatewayVerifyContractCreatorsRequest) Reset() {
	*m = TransferGatewayVerifyContractCreatorsRequest{}
}
func (m *TransferGatewayVerifyContractCreatorsRequest) String() string {
	return proto.CompactTextString(m)
}
func (*TransferGatewayVerifyContractCreatorsRequest) ProtoMessage() {}
func (*TransferGatewayVerifyContractCreatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{22}
}

func (m *TransferGatewayVerifyContractCreatorsRequest) GetCreators() []*TransferGatewayVerifiedContractCreator {
	if m != nil {
		return m.Creators
	}
	return nil
}

// Batch of events from the Gateway on Ethereum mainnet
type TransferGatewayProcessEventBatchRequest struct {
	Events []*TransferGatewayMainnetEvent `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *TransferGatewayProcessEventBatchRequest) Reset() {
	*m = TransferGatewayProcessEventBatchRequest{}
}
func (m *TransferGatewayProcessEventBatchRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayProcessEventBatchRequest) ProtoMessage()    {}
func (*TransferGatewayProcessEventBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{23}
}

func (m *TransferGatewayProcessEventBatchRequest) GetEvents() []*TransferGatewayMainnetEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type TransferGatewayStateRequest struct {
}

func (m *TransferGatewayStateRequest) Reset()         { *m = TransferGatewayStateRequest{} }
func (m *TransferGatewayStateRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayStateRequest) ProtoMessage()    {}
func (*TransferGatewayStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{24}
}

type TransferGatewayStateResponse struct {
	State *TransferGatewayState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
}

func (m *TransferGatewayStateResponse) Reset()         { *m = TransferGatewayStateResponse{} }
func (m *TransferGatewayStateResponse) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayStateResponse) ProtoMessage()    {}
func (*TransferGatewayStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{25}
}

func (m *TransferGatewayStateResponse) GetState() *TransferGatewayState {
	if m != nil {
		return m.State
	}
	return nil
}

type TransferGatewayWithdrawERC721Request struct {
	// ID of ERC721 token
	TokenId *types.BigUInt `protobuf:"bytes,1,opt,name=token_id,json=tokenId" json:"token_id,omitempty"`
	// DAppChain address of ERC721 contract token belongs to
	TokenContract *types.Address `protobuf:"bytes,2,opt,name=token_contract,json=tokenContract" json:"token_contract,omitempty"`
}

func (m *TransferGatewayWithdrawERC721Request) Reset()         { *m = TransferGatewayWithdrawERC721Request{} }
func (m *TransferGatewayWithdrawERC721Request) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayWithdrawERC721Request) ProtoMessage()    {}
func (*TransferGatewayWithdrawERC721Request) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{26}
}

func (m *TransferGatewayWithdrawERC721Request) GetTokenId() *types.BigUInt {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *TransferGatewayWithdrawERC721Request) GetTokenContract() *types.Address {
	if m != nil {
		return m.TokenContract
	}
	return nil
}

type TransferGatewayWithdrawalReceiptRequest struct {
	Owner *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
}

func (m *TransferGatewayWithdrawalReceiptRequest) Reset() {
	*m = TransferGatewayWithdrawalReceiptRequest{}
}
func (m *TransferGatewayWithdrawalReceiptRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayWithdrawalReceiptRequest) ProtoMessage()    {}
func (*TransferGatewayWithdrawalReceiptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{27}
}

func (m *TransferGatewayWithdrawalReceiptRequest) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

type TransferGatewayWithdrawalReceiptResponse struct {
	Receipt *TransferGatewayWithdrawalReceipt `protobuf:"bytes,1,opt,name=receipt" json:"receipt,omitempty"`
}

func (m *TransferGatewayWithdrawalReceiptResponse) Reset() {
	*m = TransferGatewayWithdrawalReceiptResponse{}
}
func (m *TransferGatewayWithdrawalReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayWithdrawalReceiptResponse) ProtoMessage()    {}
func (*TransferGatewayWithdrawalReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{28}
}

func (m *TransferGatewayWithdrawalReceiptResponse) GetReceipt() *TransferGatewayWithdrawalReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type TransferGatewayConfirmWithdrawalReceiptRequest struct {
	// DAppChain address of the entity attempting to make the withdrawal
	TokenOwner *types.Address `protobuf:"bytes,1,opt,name=token_owner,json=tokenOwner" json:"token_owner,omitempty"`
	// 66-byte hash of the withdrawal hash
	OracleSignature []byte `protobuf:"bytes,2,opt,name=oracle_signature,json=oracleSignature,proto3" json:"oracle_signature,omitempty"`
	// 32-byte hash of the withdrawal details
	WithdrawalHash []byte `protobuf:"bytes,3,opt,name=withdrawal_hash,json=withdrawalHash,proto3" json:"withdrawal_hash,omitempty"`
}

func (m *TransferGatewayConfirmWithdrawalReceiptRequest) Reset() {
	*m = TransferGatewayConfirmWithdrawalReceiptRequest{}
}
func (m *TransferGatewayConfirmWithdrawalReceiptRequest) String() string {
	return proto.CompactTextString(m)
}
func (*TransferGatewayConfirmWithdrawalReceiptRequest) ProtoMessage() {}
func (*TransferGatewayConfirmWithdrawalReceiptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{29}
}

func (m *TransferGatewayConfirmWithdrawalReceiptRequest) GetTokenOwner() *types.Address {
	if m != nil {
		return m.TokenOwner
	}
	return nil
}

func (m *TransferGatewayConfirmWithdrawalReceiptRequest) GetOracleSignature() []byte {
	if m != nil {
		return m.OracleSignature
	}
	return nil
}

func (m *TransferGatewayConfirmWithdrawalReceiptRequest) GetWithdrawalHash() []byte {
	if m != nil {
		return m.WithdrawalHash
	}
	return nil
}

type TransferGatewayPendingWithdrawalsRequest struct {
}

func (m *TransferGatewayPendingWithdrawalsRequest) Reset() {
	*m = TransferGatewayPendingWithdrawalsRequest{}
}
func (m *TransferGatewayPendingWithdrawalsRequest) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayPendingWithdrawalsRequest) ProtoMessage()    {}
func (*TransferGatewayPendingWithdrawalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{30}
}

type TransferGatewayPendingWithdrawalsResponse struct {
	Withdrawals []*TransferGatewayPendingWithdrawalSummary `protobuf:"bytes,1,rep,name=withdrawals" json:"withdrawals,omitempty"`
}

func (m *TransferGatewayPendingWithdrawalsResponse) Reset() {
	*m = TransferGatewayPendingWithdrawalsResponse{}
}
func (m *TransferGatewayPendingWithdrawalsResponse) String() string { return proto.CompactTextString(m) }
func (*TransferGatewayPendingWithdrawalsResponse) ProtoMessage()    {}
func (*TransferGatewayPendingWithdrawalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTransferGateway, []int{31}
}

func (m *TransferGatewayPendingWithdrawalsResponse) GetWithdrawals() []*TransferGatewayPendingWithdrawalSummary {
	if m != nil {
		return m.Withdrawals
	}
	return nil
}

func init() {
	proto.RegisterType((*TransferGatewayState)(nil), "TransferGatewayState")
	proto.RegisterType((*TransferGatewayOracleState)(nil), "TransferGatewayOracleState")
	proto.RegisterType((*TransferGatewayWithdrawalReceipt)(nil), "TransferGatewayWithdrawalReceipt")
	proto.RegisterType((*TransferGatewayPendingWithdrawalSummary)(nil), "TransferGatewayPendingWithdrawalSummary")
	proto.RegisterType((*TransferGatewayAccount)(nil), "TransferGatewayAccount")
	proto.RegisterType((*TransferGatewayTokenDeposited)(nil), "TransferGatewayTokenDeposited")
	proto.RegisterType((*TransferGatewayTokenWithdrawn)(nil), "TransferGatewayTokenWithdrawn")
	proto.RegisterType((*TransferGatewayMainnetEvent)(nil), "TransferGatewayMainnetEvent")
	proto.RegisterType((*TransferGatewayPendingContractMapping)(nil), "TransferGatewayPendingContractMapping")
	proto.RegisterType((*TransferGatewayContractAddressMapping)(nil), "TransferGatewayContractAddressMapping")
	proto.RegisterType((*TransferGatewayUnverifiedContractCreator)(nil), "TransferGatewayUnverifiedContractCreator")
	proto.RegisterType((*TransferGatewayVerifiedContractCreator)(nil), "TransferGatewayVerifiedContractCreator")
	proto.RegisterType((*TransferGatewayContractMappingConfirmed)(nil), "TransferGatewayContractMappingConfirmed")
	proto.RegisterType((*TransferGatewayTokenWithdrawalSigned)(nil), "TransferGatewayTokenWithdrawalSigned")
	proto.RegisterType((*TransferGatewayInitRequest)(nil), "TransferGatewayInitRequest")
	proto.RegisterType((*TransferGatewayAddOracleRequest)(nil), "TransferGatewayAddOracleRequest")
	proto.RegisterType((*TransferGatewayRemoveOracleRequest)(nil), "TransferGatewayRemoveOracleRequest")
	proto.RegisterType((*TransferGatewayGetOraclesRequest)(nil), "TransferGatewayGetOraclesRequest")
	proto.RegisterType((*TransferGatewayGetOraclesResponse)(nil), "TransferGatewayGetOraclesResponse")
	proto.RegisterType((*TransferGatewayAddContractMappingRequest)(nil), "TransferGatewayAddContractMappingRequest")
	proto.RegisterType((*TransferGatewayUnverifiedContractCreatorsRequest)(nil), "TransferGatewayUnverifiedContractCreatorsRequest")
	proto.RegisterType((*TransferGatewayUnverifiedContractCreatorsResponse)(nil), "TransferGatewayUnverifiedContractCreatorsResponse")
	proto.RegisterType((*TransferGatewayVerifyContractCreatorsRequest)(nil), "TransferGatewayVerifyContractCreatorsRequest")
	proto.RegisterType((*TransferGatewayProcessEventBatchRequest)(nil), "TransferGatewayProcessEventBatchRequest")
	proto.RegisterType((*TransferGatewayStateRequest)(nil), "TransferGatewayStateRequest")
	proto.RegisterType((*TransferGatewayStateResponse)(nil), "TransferGatewayStateResponse")
	proto.RegisterType((*TransferGatewayWithdrawERC721Request)(nil), "TransferGatewayWithdrawERC721Request")
	proto.RegisterType((*TransferGatewayWithdrawalReceiptRequest)(nil), "TransferGatewayWithdrawalReceiptRequest")
	proto.RegisterType((*TransferGatewayWithdrawalReceiptResponse)(nil), "TransferGatewayWithdrawalReceiptResponse")
	proto.RegisterType((*TransferGatewayConfirmWithdrawalReceiptRequest)(nil), "TransferGatewayConfirmWithdrawalReceiptRequest")
	proto.RegisterType((*TransferGatewayPendingWithdrawalsRequest)(nil), "TransferGatewayPendingWithdrawalsRequest")
	proto.RegisterType((*TransferGatewayPendingWithdrawalsResponse)(nil), "TransferGatewayPendingWithdrawalsResponse")
	proto.RegisterEnum("TransferGatewayTokenKind", TransferGatewayTokenKind_name, TransferGatewayTokenKind_value)
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/builtin/types/transfer_gateway/transfer_gateway.proto", fileDescriptorTransferGateway)
}

var fileDescriptorTransferGateway = []byte{
	// 1314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcf, 0x73, 0xdb, 0xc4,
	0x17, 0xaf, 0x14, 0x27, 0x4e, 0x5e, 0xfa, 0x4d, 0x9d, 0x6d, 0x93, 0xaf, 0xda, 0xa6, 0x4d, 0xba,
	0x14, 0x9a, 0x14, 0x2a, 0xb7, 0x29, 0x9d, 0x32, 0xe5, 0x40, 0x6b, 0x37, 0x34, 0xa1, 0xd3, 0x1f,
	0xa3, 0xa4, 0x30, 0xc3, 0x45, 0xa3, 0x48, 0x6b, 0x79, 0x27, 0xf6, 0xae, 0x91, 0xd6, 0x71, 0xc2,
	0xf0, 0x17, 0x70, 0xe1, 0xc8, 0x81, 0x1b, 0x7f, 0x00, 0x9c, 0x38, 0x70, 0xe6, 0x6f, 0xe0, 0xda,
	0x43, 0xff, 0x00, 0x8e, 0x9c, 0x19, 0xed, 0x6a, 0x6d, 0x57, 0x92, 0x1d, 0xe7, 0x00, 0x33, 0xbd,
	0x64, 0xe4, 0xf7, 0x63, 0xdf, 0xbe, 0xcf, 0x7b, 0xfb, 0xd9, 0xb7, 0x81, 0xbd, 0x90, 0x8a, 0x66,
	0x77, 0xdf, 0xf6, 0x79, 0xbb, 0xda, 0xe2, 0xbc, 0xcd, 0x88, 0xe8, 0xf1, 0xe8, 0xa0, 0x1a, 0xf2,
	0x5b, 0xc9, 0xcf, 0xea, 0x7e, 0x97, 0xb6, 0x04, 0x65, 0x55, 0x71, 0xdc, 0x21, 0x71, 0x55, 0x44,
	0x1e, 0x8b, 0x1b, 0x24, 0x72, 0x43, 0x4f, 0x90, 0x9e, 0x77, 0x9c, 0x13, 0xd8, 0x9d, 0x88, 0x0b,
	0x7e, 0xe9, 0xd6, 0xd0, 0xaa, 0x21, 0x0f, 0x79, 0x55, 0x8a, 0xf7, 0xbb, 0x0d, 0xf9, 0x4b, 0xfe,
	0x90, 0x5f, 0xa9, 0xf9, 0xed, 0x13, 0x36, 0x91, 0x06, 0x4f, 0xfe, 0x2a, 0x0f, 0xfc, 0xb7, 0x01,
	0x17, 0xf6, 0xd2, 0xd8, 0x4f, 0x54, 0xe8, 0x5d, 0xe1, 0x09, 0x82, 0xae, 0xc2, 0x34, 0xef, 0x31,
	0x12, 0x59, 0xc6, 0x9a, 0xb1, 0x3e, 0xbf, 0x39, 0x6b, 0x3f, 0x0a, 0x82, 0x88, 0xc4, 0xb1, 0xa3,
	0xc4, 0xe8, 0x2e, 0x2c, 0xb7, 0xbc, 0x58, 0xb8, 0x6d, 0x8f, 0x32, 0x46, 0x84, 0xbb, 0xdf, 0xe2,
	0xfe, 0x81, 0xcb, 0xba, 0x6d, 0xcb, 0x5c, 0x33, 0xd6, 0x4b, 0xce, 0xf9, 0x44, 0xfb, 0x4c, 0x29,
	0x6b, 0x89, 0xee, 0x79, 0xb7, 0x8d, 0x1c, 0xb0, 0x18, 0x39, 0x12, 0xae, 0xcf, 0x99, 0x88, 0x3c,
	0x3f, 0xf1, 0xee, 0x74, 0x28, 0x0b, 0x5d, 0x1a, 0x58, 0x53, 0x89, 0x5b, 0xed, 0xe2, 0x9b, 0xd7,
	0xab, 0x4b, 0xcf, 0xc9, 0x91, 0xa8, 0xa7, 0x26, 0xcf, 0x94, 0xc5, 0xce, 0x63, 0x67, 0x89, 0x15,
	0x88, 0x03, 0x74, 0x0f, 0x16, 0x05, 0x3f, 0x20, 0xcc, 0xed, 0x51, 0xd1, 0x0c, 0x22, 0xaf, 0x47,
	0xa2, 0xd8, 0x2a, 0xad, 0x4d, 0xbd, 0xb5, 0xe9, 0x8a, 0x34, 0xf9, 0x6a, 0x60, 0x81, 0x1f, 0xc2,
	0xa5, 0x4c, 0xde, 0x2f, 0x22, 0xcf, 0x6f, 0x11, 0x95, 0x3d, 0x86, 0xb2, 0xa7, 0x5c, 0x73, 0xf9,
	0x6b, 0x05, 0xfe, 0xc5, 0x84, 0xb5, 0xcc, 0x12, 0x3a, 0x80, 0xd7, 0x72, 0x88, 0x4f, 0x68, 0x47,
	0xa0, 0x0d, 0x98, 0x57, 0xbb, 0x2b, 0x06, 0x13, 0xa4, 0xf2, 0x85, 0x44, 0xb4, 0x0a, 0x0b, 0xca,
	0x54, 0xa3, 0x23, 0x91, 0x1c, 0xb6, 0xfe, 0x9f, 0xd4, 0x6b, 0x08, 0xd0, 0x27, 0xa0, 0xdc, 0xdd,
	0x03, 0xca, 0x14, 0x7e, 0x0b, 0x9b, 0x17, 0xed, 0xcc, 0x96, 0xf6, 0x12, 0x8b, 0xa7, 0x94, 0x05,
	0xce, 0x9c, 0xd0, 0x9f, 0x49, 0x71, 0x0f, 0xbd, 0x56, 0x97, 0x58, 0xa5, 0x34, 0x42, 0x8d, 0x86,
	0xaf, 0x76, 0x98, 0x70, 0x94, 0x18, 0x6d, 0x40, 0xa5, 0xd7, 0x4f, 0xc5, 0x65, 0x9c, 0xf9, 0xc4,
	0x9a, 0x96, 0x65, 0x3d, 0x37, 0x90, 0x3f, 0x4f, 0xc4, 0x89, 0x29, 0x97, 0xc0, 0xb9, 0x31, 0x0d,
	0x99, 0x27, 0xba, 0x11, 0xb1, 0x66, 0xd6, 0x8c, 0xf5, 0xb3, 0xce, 0x39, 0x25, 0xdf, 0xd5, 0x62,
	0xdc, 0x84, 0x1b, 0x99, 0xcd, 0xbd, 0x24, 0x2c, 0xa0, 0x2c, 0x1c, 0xc0, 0xb6, 0xdb, 0x6d, 0xb7,
	0xbd, 0xe8, 0xf8, 0x34, 0xb0, 0x21, 0x28, 0x35, 0xbd, 0xb8, 0x29, 0xc1, 0x3a, 0xeb, 0xc8, 0x6f,
	0xfc, 0x9b, 0x01, 0xcb, 0x99, 0x50, 0x8f, 0x7c, 0x9f, 0x77, 0x99, 0x38, 0xb1, 0xaf, 0x8b, 0x52,
	0x37, 0x8b, 0x53, 0x7f, 0x09, 0x68, 0xc8, 0x34, 0x52, 0x15, 0x97, 0x75, 0x98, 0xdf, 0xbc, 0x66,
	0x9f, 0xd4, 0x1a, 0xce, 0x62, 0x2f, 0x2b, 0xc2, 0x7f, 0x1a, 0x70, 0xa5, 0xa8, 0x7e, 0x8f, 0x49,
	0x87, 0xc7, 0x54, 0x90, 0xe0, 0xdd, 0xec, 0xa7, 0x91, 0x79, 0x69, 0x50, 0xd8, 0x3b, 0x9a, 0xd7,
	0x1f, 0x06, 0x5c, 0xce, 0xac, 0x93, 0x52, 0xde, 0xd6, 0x21, 0x61, 0x02, 0x5d, 0x86, 0x39, 0x22,
	0x9a, 0x8a, 0x1b, 0x65, 0x4e, 0x25, 0x67, 0x96, 0x88, 0xa6, 0xe4, 0x43, 0xf4, 0x00, 0xca, 0x81,
	0xaa, 0x6b, 0x9a, 0xc0, 0x55, 0x7b, 0x6c, 0xed, 0xb7, 0xcf, 0x38, 0xda, 0x01, 0x3d, 0x04, 0x18,
	0x74, 0x4f, 0xda, 0x72, 0xc5, 0xee, 0x7d, 0x88, 0xb7, 0xcf, 0x38, 0x43, 0x3e, 0xb5, 0x39, 0x28,
	0x77, 0xbc, 0xe3, 0x16, 0xf7, 0x02, 0xfc, 0xb3, 0x09, 0xef, 0x17, 0x1f, 0xcc, 0x0c, 0xdb, 0xa2,
	0x65, 0x30, 0x69, 0xa0, 0x12, 0xa9, 0xcd, 0xbc, 0x79, 0xbd, 0x6a, 0xee, 0x3c, 0x76, 0x4c, 0x1a,
	0xa0, 0xbb, 0x50, 0x69, 0xf0, 0x88, 0xd0, 0x70, 0x4c, 0x51, 0xce, 0xa5, 0x16, 0xfd, 0xb2, 0x54,
	0x61, 0xa1, 0xc5, 0x7d, 0xaf, 0x35, 0x70, 0x99, 0xca, 0xd6, 0x51, 0xea, 0xfb, 0x0e, 0x35, 0xb0,
	0xb2, 0x51, 0x5c, 0x3f, 0x22, 0x9e, 0xe0, 0x51, 0xbf, 0x40, 0xda, 0x75, 0x39, 0x13, 0xad, 0xae,
	0xec, 0xd0, 0xfd, 0x82, 0x35, 0xc4, 0x91, 0x2b, 0x19, 0x64, 0x5a, 0x32, 0xc8, 0x52, 0xc6, 0x73,
	0xef, 0x68, 0x3b, 0xa1, 0x14, 0x37, 0x87, 0x91, 0x36, 0x48, 0x43, 0x6a, 0x8c, 0x56, 0xa0, 0xd4,
	0x88, 0x78, 0x3b, 0xd7, 0xc2, 0x52, 0x8a, 0x2c, 0x30, 0x05, 0xcf, 0x61, 0x63, 0x0a, 0x8e, 0x7f,
	0x32, 0x60, 0x3d, 0x13, 0xe1, 0x15, 0x3b, 0x24, 0x11, 0x6d, 0x50, 0x12, 0x64, 0xd3, 0xd8, 0x82,
	0xf3, 0x45, 0x77, 0xa8, 0xaa, 0xcc, 0xd2, 0x9b, 0xd7, 0xab, 0x8b, 0xf9, 0xfb, 0x73, 0xd1, 0xcf,
	0xdd, 0x9d, 0xeb, 0x50, 0xc9, 0xa1, 0xa0, 0x78, 0x74, 0xc1, 0x7f, 0x3b, 0xfd, 0xdf, 0x0d, 0xf8,
	0x20, 0xb3, 0xbb, 0x2f, 0xff, 0xdd, 0xbd, 0x61, 0x28, 0xeb, 0xe2, 0x66, 0xe1, 0xd2, 0x0a, 0x74,
	0x1d, 0x66, 0x47, 0x36, 0x4f, 0x5f, 0x83, 0x7f, 0x30, 0x72, 0x17, 0x4f, 0x66, 0x07, 0x75, 0xce,
	0x1a, 0x34, 0x6a, 0x93, 0xe2, 0x4e, 0x36, 0x4e, 0xdf, 0xc9, 0xe6, 0xd8, 0x4e, 0xc6, 0x7f, 0x19,
	0x70, 0x7d, 0xdc, 0x61, 0xf5, 0x5a, 0xc9, 0xad, 0xf9, 0xae, 0xd2, 0x3d, 0xaa, 0xc0, 0x54, 0x4c,
	0xc3, 0xf4, 0x3c, 0x25, 0x9f, 0xf8, 0x47, 0x23, 0x37, 0x6e, 0xed, 0x30, 0x2a, 0x1c, 0xf2, 0x4d,
	0x97, 0xc4, 0x27, 0x5f, 0xca, 0x18, 0xca, 0x6a, 0x98, 0x88, 0x2d, 0x33, 0x33, 0xd9, 0x69, 0x05,
	0xba, 0x07, 0xff, 0x6f, 0xd0, 0xa8, 0x70, 0x22, 0x95, 0xa3, 0xa5, 0x73, 0x41, 0xaa, 0x33, 0x23,
	0x29, 0xae, 0xc3, 0x6a, 0x76, 0x52, 0x08, 0x02, 0x35, 0x0a, 0xea, 0xdd, 0xad, 0xc1, 0x8c, 0x0a,
	0x92, 0xdb, 0x5e, 0x2a, 0xc7, 0x9f, 0x03, 0xce, 0x2c, 0xe2, 0x90, 0x36, 0x3f, 0x24, 0xa7, 0x5d,
	0x07, 0xe7, 0x26, 0xca, 0x27, 0x44, 0xa8, 0x45, 0xe2, 0x74, 0x15, 0xfc, 0x35, 0x5c, 0x1b, 0x63,
	0x13, 0x77, 0x38, 0x8b, 0x09, 0xba, 0x37, 0x00, 0xcc, 0x90, 0x80, 0x5d, 0xb6, 0x47, 0x4f, 0xbb,
	0x7d, 0x0c, 0xf1, 0xf7, 0x66, 0x8e, 0x83, 0x1e, 0x05, 0x41, 0xe6, 0xb0, 0xe8, 0x74, 0xfe, 0x93,
	0xa3, 0x82, 0x3e, 0x83, 0x95, 0x51, 0xa4, 0x9f, 0x4c, 0x9c, 0xb2, 0xb6, 0x67, 0x9d, 0x8b, 0xc5,
	0x74, 0xbf, 0x4b, 0xc3, 0xb1, 0x8c, 0x5f, 0x1a, 0xc7, 0xf8, 0x9b, 0x70, 0x7b, 0x52, 0x3e, 0xee,
	0x17, 0xe7, 0x5b, 0xb8, 0x73, 0x0a, 0x9f, 0xb4, 0x58, 0x5b, 0x30, 0x9b, 0x66, 0xa4, 0xab, 0xb5,
	0x61, 0x4f, 0xba, 0x8a, 0xd3, 0x77, 0xc5, 0x31, 0x7c, 0x54, 0xc4, 0xd0, 0xc7, 0x23, 0xf6, 0x8a,
	0xea, 0xb9, 0xb0, 0x37, 0xec, 0xc9, 0x28, 0x7e, 0x28, 0xa8, 0x9b, 0x9f, 0xe9, 0x23, 0xee, 0x93,
	0x38, 0x96, 0x03, 0x50, 0xcd, 0x13, 0x7e, 0x53, 0xc7, 0xfb, 0x18, 0x66, 0x48, 0x22, 0xd4, 0xd1,
	0x56, 0xec, 0x31, 0xa3, 0x93, 0x93, 0xda, 0xe2, 0x2b, 0xb9, 0x09, 0x4b, 0xf5, 0x6c, 0x0a, 0xf8,
	0x53, 0x58, 0x29, 0x56, 0xa7, 0xd8, 0x7e, 0x08, 0xd3, 0x71, 0x22, 0x48, 0x3b, 0x73, 0xc9, 0x2e,
	0xb4, 0x56, 0x36, 0xf8, 0xbb, 0x1c, 0x2b, 0x6b, 0x42, 0xde, 0x72, 0xea, 0xf7, 0x37, 0xef, 0xe8,
	0x4c, 0xde, 0x83, 0x59, 0xc5, 0x9c, 0xe9, 0xb5, 0x36, 0x4c, 0x81, 0x65, 0xa9, 0xd9, 0x09, 0x4e,
	0xcd, 0xc7, 0x78, 0x27, 0x07, 0x65, 0xfe, 0xcd, 0x30, 0x19, 0x5f, 0xe2, 0x30, 0x77, 0x8c, 0x0b,
	0x96, 0x4a, 0x11, 0xfa, 0x14, 0xca, 0xfa, 0xe9, 0x62, 0x4c, 0xfa, 0x74, 0xd1, 0x1e, 0xf8, 0x57,
	0x03, 0xec, 0xfc, 0xd5, 0x9a, 0xdc, 0xa5, 0x23, 0xf7, 0x7e, 0x8a, 0x2b, 0xad, 0xe8, 0x6d, 0x69,
	0x16, 0xbe, 0x2d, 0xd1, 0x0d, 0x18, 0x7a, 0x9e, 0xa9, 0xc3, 0xad, 0x98, 0x61, 0x61, 0x20, 0x96,
	0xa7, 0xfa, 0x66, 0x0e, 0x9a, 0xdc, 0x23, 0xb4, 0x7f, 0x9a, 0x7b, 0xb0, 0x31, 0x81, 0x6d, 0x8a,
	0xe3, 0x17, 0x30, 0x3f, 0x08, 0xa5, 0x7b, 0x7c, 0xdd, 0x9e, 0xf0, 0xc5, 0xeb, 0x0c, 0x3b, 0xdf,
	0x7c, 0x00, 0xd6, 0xa8, 0x7b, 0x18, 0x95, 0x61, 0x6a, 0x6b, 0x6f, 0xbb, 0x72, 0x06, 0xcd, 0xc1,
	0xf4, 0x96, 0x53, 0xdf, 0xbc, 0x5d, 0x31, 0x10, 0xc0, 0x8c, 0xea, 0xd0, 0x8a, 0xb9, 0x3f, 0x23,
	0xff, 0xb1, 0x73, 0xf7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0xa2, 0x62, 0x37, 0x91, 0x12,
	0x00, 0x00,
}
