// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/builtin/types/user_deployer_whitelist/user_deployer_whitelist.proto

package user_deployer_whitelist

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TierID int32

const (
	TierID_DEFAULT TierID = 0
)

var TierID_name = map[int32]string{
	0: "DEFAULT",
}
var TierID_value = map[string]int32{
	"DEFAULT": 0,
}

func (x TierID) String() string {
	return proto.EnumName(TierID_name, int32(x))
}
func (TierID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{0}
}

type Tier struct {
	TierID               TierID         `protobuf:"varint,1,opt,name=id,proto3,enum=user_deployer_whitelist.TierID" json:"id,omitempty"`
	Fee                  *types.BigUInt `protobuf:"bytes,2,opt,name=fee" json:"fee,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Tier) Reset()         { *m = Tier{} }
func (m *Tier) String() string { return proto.CompactTextString(m) }
func (*Tier) ProtoMessage()    {}
func (*Tier) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{0}
}
func (m *Tier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tier.Unmarshal(m, b)
}
func (m *Tier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tier.Marshal(b, m, deterministic)
}
func (dst *Tier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tier.Merge(dst, src)
}
func (m *Tier) XXX_Size() int {
	return xxx_messageInfo_Tier.Size(m)
}
func (m *Tier) XXX_DiscardUnknown() {
	xxx_messageInfo_Tier.DiscardUnknown(m)
}

var xxx_messageInfo_Tier proto.InternalMessageInfo

func (m *Tier) GetTierID() TierID {
	if m != nil {
		return m.TierID
	}
	return TierID_DEFAULT
}

func (m *Tier) GetFee() *types.BigUInt {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *Tier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TierInfo struct {
	TierID               TierID   `protobuf:"varint,1,opt,name=id,proto3,enum=user_deployer_whitelist.TierID" json:"id,omitempty"`
	Fee                  uint64   `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TierInfo) Reset()         { *m = TierInfo{} }
func (m *TierInfo) String() string { return proto.CompactTextString(m) }
func (*TierInfo) ProtoMessage()    {}
func (*TierInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{1}
}
func (m *TierInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TierInfo.Unmarshal(m, b)
}
func (m *TierInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TierInfo.Marshal(b, m, deterministic)
}
func (dst *TierInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TierInfo.Merge(dst, src)
}
func (m *TierInfo) XXX_Size() int {
	return xxx_messageInfo_TierInfo.Size(m)
}
func (m *TierInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TierInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TierInfo proto.InternalMessageInfo

func (m *TierInfo) GetTierID() TierID {
	if m != nil {
		return m.TierID
	}
	return TierID_DEFAULT
}

func (m *TierInfo) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *TierInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InitRequest struct {
	Owner                *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	TierInfo             []*TierInfo    `protobuf:"bytes,2,rep,name=tier_info,json=tierInfo" json:"tier_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{2}
}
func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (dst *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(dst, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *InitRequest) GetTierInfo() []*TierInfo {
	if m != nil {
		return m.TierInfo
	}
	return nil
}

type DeployerContract struct {
	ContractAddress      *types.Address `protobuf:"bytes,1,opt,name=contractAddress" json:"contractAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeployerContract) Reset()         { *m = DeployerContract{} }
func (m *DeployerContract) String() string { return proto.CompactTextString(m) }
func (*DeployerContract) ProtoMessage()    {}
func (*DeployerContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{3}
}
func (m *DeployerContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployerContract.Unmarshal(m, b)
}
func (m *DeployerContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployerContract.Marshal(b, m, deterministic)
}
func (dst *DeployerContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployerContract.Merge(dst, src)
}
func (m *DeployerContract) XXX_Size() int {
	return xxx_messageInfo_DeployerContract.Size(m)
}
func (m *DeployerContract) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployerContract.DiscardUnknown(m)
}

var xxx_messageInfo_DeployerContract proto.InternalMessageInfo

func (m *DeployerContract) GetContractAddress() *types.Address {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

type WhitelistUserDeployerRequest struct {
	DeployerAddr         *types.Address `protobuf:"bytes,1,opt,name=deployerAddr" json:"deployerAddr,omitempty"`
	TierID               TierID         `protobuf:"varint,2,opt,name=tier_id,json=tierId,proto3,enum=user_deployer_whitelist.TierID" json:"tier_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WhitelistUserDeployerRequest) Reset()         { *m = WhitelistUserDeployerRequest{} }
func (m *WhitelistUserDeployerRequest) String() string { return proto.CompactTextString(m) }
func (*WhitelistUserDeployerRequest) ProtoMessage()    {}
func (*WhitelistUserDeployerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{4}
}
func (m *WhitelistUserDeployerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhitelistUserDeployerRequest.Unmarshal(m, b)
}
func (m *WhitelistUserDeployerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhitelistUserDeployerRequest.Marshal(b, m, deterministic)
}
func (dst *WhitelistUserDeployerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistUserDeployerRequest.Merge(dst, src)
}
func (m *WhitelistUserDeployerRequest) XXX_Size() int {
	return xxx_messageInfo_WhitelistUserDeployerRequest.Size(m)
}
func (m *WhitelistUserDeployerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistUserDeployerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistUserDeployerRequest proto.InternalMessageInfo

func (m *WhitelistUserDeployerRequest) GetDeployerAddr() *types.Address {
	if m != nil {
		return m.DeployerAddr
	}
	return nil
}

func (m *WhitelistUserDeployerRequest) GetTierID() TierID {
	if m != nil {
		return m.TierID
	}
	return TierID_DEFAULT
}

type UserState struct {
	UserAddr             *types.Address   `protobuf:"bytes,1,opt,name=userAddr" json:"userAddr,omitempty"`
	Deployers            []*types.Address `protobuf:"bytes,2,rep,name=deployers" json:"deployers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserState) Reset()         { *m = UserState{} }
func (m *UserState) String() string { return proto.CompactTextString(m) }
func (*UserState) ProtoMessage()    {}
func (*UserState) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{5}
}
func (m *UserState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserState.Unmarshal(m, b)
}
func (m *UserState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserState.Marshal(b, m, deterministic)
}
func (dst *UserState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserState.Merge(dst, src)
}
func (m *UserState) XXX_Size() int {
	return xxx_messageInfo_UserState.Size(m)
}
func (m *UserState) XXX_DiscardUnknown() {
	xxx_messageInfo_UserState.DiscardUnknown(m)
}

var xxx_messageInfo_UserState proto.InternalMessageInfo

func (m *UserState) GetUserAddr() *types.Address {
	if m != nil {
		return m.UserAddr
	}
	return nil
}

func (m *UserState) GetDeployers() []*types.Address {
	if m != nil {
		return m.Deployers
	}
	return nil
}

type UserDeployerState struct {
	Address              *types.Address      `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Contracts            []*DeployerContract `protobuf:"bytes,2,rep,name=contracts" json:"contracts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserDeployerState) Reset()         { *m = UserDeployerState{} }
func (m *UserDeployerState) String() string { return proto.CompactTextString(m) }
func (*UserDeployerState) ProtoMessage()    {}
func (*UserDeployerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{6}
}
func (m *UserDeployerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeployerState.Unmarshal(m, b)
}
func (m *UserDeployerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeployerState.Marshal(b, m, deterministic)
}
func (dst *UserDeployerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeployerState.Merge(dst, src)
}
func (m *UserDeployerState) XXX_Size() int {
	return xxx_messageInfo_UserDeployerState.Size(m)
}
func (m *UserDeployerState) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeployerState.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeployerState proto.InternalMessageInfo

func (m *UserDeployerState) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UserDeployerState) GetContracts() []*DeployerContract {
	if m != nil {
		return m.Contracts
	}
	return nil
}

type GetUserDeployersRequest struct {
	UserAddr             *types.Address `protobuf:"bytes,1,opt,name=userAddr" json:"userAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetUserDeployersRequest) Reset()         { *m = GetUserDeployersRequest{} }
func (m *GetUserDeployersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserDeployersRequest) ProtoMessage()    {}
func (*GetUserDeployersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{7}
}
func (m *GetUserDeployersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDeployersRequest.Unmarshal(m, b)
}
func (m *GetUserDeployersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDeployersRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserDeployersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDeployersRequest.Merge(dst, src)
}
func (m *GetUserDeployersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserDeployersRequest.Size(m)
}
func (m *GetUserDeployersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDeployersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDeployersRequest proto.InternalMessageInfo

func (m *GetUserDeployersRequest) GetUserAddr() *types.Address {
	if m != nil {
		return m.UserAddr
	}
	return nil
}

type GetUserDeployersResponse struct {
	Deployers            []*types.Address `protobuf:"bytes,1,rep,name=deployers" json:"deployers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetUserDeployersResponse) Reset()         { *m = GetUserDeployersResponse{} }
func (m *GetUserDeployersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserDeployersResponse) ProtoMessage()    {}
func (*GetUserDeployersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{8}
}
func (m *GetUserDeployersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDeployersResponse.Unmarshal(m, b)
}
func (m *GetUserDeployersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDeployersResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserDeployersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDeployersResponse.Merge(dst, src)
}
func (m *GetUserDeployersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserDeployersResponse.Size(m)
}
func (m *GetUserDeployersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDeployersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDeployersResponse proto.InternalMessageInfo

func (m *GetUserDeployersResponse) GetDeployers() []*types.Address {
	if m != nil {
		return m.Deployers
	}
	return nil
}

type GetDeployedContractsRequest struct {
	DeployerAddr         *types.Address `protobuf:"bytes,1,opt,name=deployerAddr" json:"deployerAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetDeployedContractsRequest) Reset()         { *m = GetDeployedContractsRequest{} }
func (m *GetDeployedContractsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeployedContractsRequest) ProtoMessage()    {}
func (*GetDeployedContractsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{9}
}
func (m *GetDeployedContractsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeployedContractsRequest.Unmarshal(m, b)
}
func (m *GetDeployedContractsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeployedContractsRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeployedContractsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeployedContractsRequest.Merge(dst, src)
}
func (m *GetDeployedContractsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeployedContractsRequest.Size(m)
}
func (m *GetDeployedContractsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeployedContractsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeployedContractsRequest proto.InternalMessageInfo

func (m *GetDeployedContractsRequest) GetDeployerAddr() *types.Address {
	if m != nil {
		return m.DeployerAddr
	}
	return nil
}

type GetDeployedContractsResponse struct {
	ContractAddresses    []*DeployerContract `protobuf:"bytes,1,rep,name=contractAddresses" json:"contractAddresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetDeployedContractsResponse) Reset()         { *m = GetDeployedContractsResponse{} }
func (m *GetDeployedContractsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeployedContractsResponse) ProtoMessage()    {}
func (*GetDeployedContractsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20, []int{10}
}
func (m *GetDeployedContractsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeployedContractsResponse.Unmarshal(m, b)
}
func (m *GetDeployedContractsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeployedContractsResponse.Marshal(b, m, deterministic)
}
func (dst *GetDeployedContractsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeployedContractsResponse.Merge(dst, src)
}
func (m *GetDeployedContractsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeployedContractsResponse.Size(m)
}
func (m *GetDeployedContractsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeployedContractsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeployedContractsResponse proto.InternalMessageInfo

func (m *GetDeployedContractsResponse) GetContractAddresses() []*DeployerContract {
	if m != nil {
		return m.ContractAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*Tier)(nil), "user_deployer_whitelist.Tier")
	proto.RegisterType((*TierInfo)(nil), "user_deployer_whitelist.TierInfo")
	proto.RegisterType((*InitRequest)(nil), "user_deployer_whitelist.InitRequest")
	proto.RegisterType((*DeployerContract)(nil), "user_deployer_whitelist.DeployerContract")
	proto.RegisterType((*WhitelistUserDeployerRequest)(nil), "user_deployer_whitelist.WhitelistUserDeployerRequest")
	proto.RegisterType((*UserState)(nil), "user_deployer_whitelist.UserState")
	proto.RegisterType((*UserDeployerState)(nil), "user_deployer_whitelist.UserDeployerState")
	proto.RegisterType((*GetUserDeployersRequest)(nil), "user_deployer_whitelist.GetUserDeployersRequest")
	proto.RegisterType((*GetUserDeployersResponse)(nil), "user_deployer_whitelist.GetUserDeployersResponse")
	proto.RegisterType((*GetDeployedContractsRequest)(nil), "user_deployer_whitelist.GetDeployedContractsRequest")
	proto.RegisterType((*GetDeployedContractsResponse)(nil), "user_deployer_whitelist.GetDeployedContractsResponse")
	proto.RegisterEnum("user_deployer_whitelist.TierID", TierID_name, TierID_value)
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/builtin/types/user_deployer_whitelist/user_deployer_whitelist.proto", fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20)
}

var fileDescriptor_user_deployer_whitelist_f39c72ffed19ec20 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6f, 0x12, 0x41,
	0x14, 0x75, 0x01, 0xf9, 0xb8, 0x18, 0xa5, 0x93, 0x98, 0x12, 0x6c, 0x2c, 0x4e, 0x8c, 0x41, 0x63,
	0x59, 0x83, 0x8f, 0x26, 0x9a, 0x22, 0x96, 0x10, 0x7d, 0x5a, 0x4b, 0x1a, 0x9f, 0x08, 0xcb, 0xde,
	0xdd, 0x4e, 0x84, 0x19, 0x9c, 0x99, 0x0d, 0xe9, 0x9b, 0xbf, 0xc1, 0x1f, 0xe8, 0x83, 0xbf, 0xc4,
	0xec, 0xec, 0x8e, 0x14, 0xe8, 0x56, 0x6b, 0x5f, 0x36, 0x77, 0xee, 0xc7, 0x39, 0xe7, 0x9e, 0x99,
	0x2c, 0xf8, 0x11, 0xd3, 0xe7, 0xb1, 0xdf, 0x9d, 0x89, 0x85, 0x3b, 0x17, 0x62, 0xc1, 0x51, 0xaf,
	0x84, 0xfc, 0xea, 0x46, 0xe2, 0x28, 0x39, 0xba, 0x7e, 0xcc, 0xe6, 0x9a, 0x71, 0x57, 0x5f, 0x2c,
	0x51, 0xb9, 0xb1, 0x42, 0x39, 0x09, 0x70, 0x39, 0x17, 0x17, 0x28, 0x27, 0xab, 0x73, 0xa6, 0x71,
	0xce, 0x94, 0xce, 0xcb, 0x77, 0x97, 0x52, 0x68, 0x41, 0xf6, 0x73, 0xca, 0xad, 0xa3, 0x4b, 0xe4,
	0x91, 0x88, 0x84, 0x6b, 0xfa, 0xfd, 0x38, 0x34, 0x27, 0x73, 0x30, 0x51, 0x8a, 0xd3, 0x7a, 0xf5,
	0x17, 0xad, 0xa9, 0x46, 0xf3, 0x4d, 0x27, 0xa8, 0x82, 0xd2, 0x29, 0x43, 0x49, 0xde, 0x40, 0x81,
	0x05, 0x4d, 0xa7, 0xed, 0x74, 0xee, 0xf7, 0x0e, 0xbb, 0x79, 0x6a, 0x93, 0xd6, 0xd1, 0xa0, 0x0f,
	0xbf, 0x7e, 0x1e, 0x96, 0xd3, 0xd8, 0x2b, 0xb0, 0x80, 0xb4, 0xa0, 0x18, 0x22, 0x36, 0x0b, 0x6d,
	0xa7, 0x53, 0xef, 0x55, 0xbb, 0x7d, 0x16, 0x8d, 0x47, 0x5c, 0x7b, 0x49, 0x92, 0x10, 0x28, 0xf1,
	0xe9, 0x02, 0x9b, 0xc5, 0xb6, 0xd3, 0xa9, 0x79, 0x26, 0xa6, 0x0b, 0xa8, 0x9a, 0x69, 0x1e, 0x8a,
	0xdb, 0x11, 0x37, 0xd6, 0xc4, 0xa5, 0xeb, 0xe8, 0xea, 0x23, 0xce, 0xb4, 0x87, 0xdf, 0x62, 0x54,
	0x9a, 0x3c, 0x86, 0xbb, 0x62, 0xc5, 0x51, 0x1a, 0xd2, 0x44, 0xef, 0x71, 0x10, 0x48, 0x54, 0xca,
	0x4b, 0xd3, 0xe4, 0x2d, 0xd4, 0x34, 0x43, 0x39, 0x61, 0x3c, 0x14, 0xcd, 0x42, 0xbb, 0xd8, 0xa9,
	0xf7, 0x9e, 0x5c, 0x2f, 0x8c, 0x87, 0xc2, 0xab, 0xea, 0x2c, 0xa2, 0x27, 0xd0, 0x18, 0x64, 0x8d,
	0xef, 0x05, 0xd7, 0x72, 0x3a, 0xd3, 0xa4, 0x07, 0x0f, 0x66, 0x59, 0x9c, 0xb1, 0xed, 0xb0, 0x6f,
	0x37, 0xd0, 0x1f, 0x0e, 0x1c, 0x9c, 0x59, 0xa2, 0xb1, 0x42, 0x69, 0x51, 0xed, 0x22, 0x2f, 0xe1,
	0x9e, 0x55, 0x94, 0xcc, 0xec, 0x20, 0x6e, 0x54, 0xc9, 0x00, 0x2a, 0xe9, 0x5a, 0x81, 0xf1, 0xeb,
	0x86, 0x6e, 0x97, 0xcd, 0x7a, 0x01, 0xfd, 0x02, 0xb5, 0x44, 0xca, 0x67, 0x3d, 0xd5, 0x48, 0x9e,
	0x42, 0x35, 0x81, 0xb8, 0x92, 0xfc, 0x4f, 0x85, 0x3c, 0x83, 0x9a, 0xe5, 0x50, 0x99, 0x9f, 0xeb,
	0xb6, 0x75, 0x89, 0x7e, 0x77, 0x60, 0xef, 0xf2, 0x9a, 0x29, 0x07, 0x85, 0xca, 0x34, 0xc7, 0x31,
	0x5b, 0x20, 0x43, 0xa8, 0x59, 0xf3, 0x2c, 0xc3, 0xf3, 0xdc, 0xe5, 0xb6, 0xef, 0xc6, 0x5b, 0xcf,
	0xd2, 0x77, 0xb0, 0x3f, 0xc4, 0x0d, 0xaf, 0x95, 0x35, 0xfb, 0x9f, 0x76, 0xa5, 0x7d, 0x68, 0xee,
	0x02, 0xa8, 0xa5, 0xe0, 0x0a, 0x37, 0x7d, 0x70, 0xf2, 0x7d, 0xf8, 0x08, 0x8f, 0x86, 0xa8, 0xb3,
	0xf9, 0xc0, 0xca, 0x54, 0xff, 0x75, 0xeb, 0x74, 0x05, 0x07, 0x57, 0x83, 0x65, 0xa2, 0xce, 0x60,
	0x6f, 0xeb, 0xdd, 0xa1, 0x15, 0x77, 0x03, 0x0b, 0x77, 0x31, 0x5e, 0x3c, 0x84, 0xec, 0xe9, 0x90,
	0x3a, 0x54, 0x06, 0x1f, 0x4e, 0x8e, 0xc7, 0x9f, 0x4e, 0x1b, 0x77, 0xfc, 0xb2, 0xf9, 0xed, 0xbc,
	0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x47, 0xa4, 0x85, 0xc7, 0x56, 0x05, 0x00, 0x00,
}
