// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/builtin/types/chainconfig/chainconfig.proto

package chainconfig

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Feature_FeatureStatus int32

const (
	Feature_PENDING  Feature_FeatureStatus = 0
	Feature_WAITING  Feature_FeatureStatus = 1
	Feature_ENABLED  Feature_FeatureStatus = 2
	Feature_DISABLED Feature_FeatureStatus = 3
)

var Feature_FeatureStatus_name = map[int32]string{
	0: "PENDING",
	1: "WAITING",
	2: "ENABLED",
	3: "DISABLED",
}
var Feature_FeatureStatus_value = map[string]int32{
	"PENDING":  0,
	"WAITING":  1,
	"ENABLED":  2,
	"DISABLED": 3,
}

func (x Feature_FeatureStatus) String() string {
	return proto.EnumName(Feature_FeatureStatus_name, int32(x))
}
func (Feature_FeatureStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{5, 0}
}

type InitRequest struct {
	Owner                *types.Address `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Params               *Params        `protobuf:"bytes,2,opt,name=params" json:"params,omitempty"`
	Features             []*Feature     `protobuf:"bytes,3,rep,name=features" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{0}
}
func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (dst *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(dst, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *InitRequest) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *InitRequest) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type GetFeatureRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeatureRequest) Reset()         { *m = GetFeatureRequest{} }
func (m *GetFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeatureRequest) ProtoMessage()    {}
func (*GetFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{1}
}
func (m *GetFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeatureRequest.Unmarshal(m, b)
}
func (m *GetFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeatureRequest.Marshal(b, m, deterministic)
}
func (dst *GetFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeatureRequest.Merge(dst, src)
}
func (m *GetFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeatureRequest.Size(m)
}
func (m *GetFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeatureRequest proto.InternalMessageInfo

func (m *GetFeatureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddFeatureRequest struct {
	Names                []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	BuildNumber          uint64   `protobuf:"varint,2,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	AutoEnable           bool     `protobuf:"varint,3,opt,name=auto_enable,json=autoEnable,proto3" json:"auto_enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFeatureRequest) Reset()         { *m = AddFeatureRequest{} }
func (m *AddFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*AddFeatureRequest) ProtoMessage()    {}
func (*AddFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{2}
}
func (m *AddFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeatureRequest.Unmarshal(m, b)
}
func (m *AddFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeatureRequest.Marshal(b, m, deterministic)
}
func (dst *AddFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeatureRequest.Merge(dst, src)
}
func (m *AddFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_AddFeatureRequest.Size(m)
}
func (m *AddFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeatureRequest proto.InternalMessageInfo

func (m *AddFeatureRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *AddFeatureRequest) GetBuildNumber() uint64 {
	if m != nil {
		return m.BuildNumber
	}
	return 0
}

func (m *AddFeatureRequest) GetAutoEnable() bool {
	if m != nil {
		return m.AutoEnable
	}
	return false
}

type AddFeatureResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFeatureResponse) Reset()         { *m = AddFeatureResponse{} }
func (m *AddFeatureResponse) String() string { return proto.CompactTextString(m) }
func (*AddFeatureResponse) ProtoMessage()    {}
func (*AddFeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{3}
}
func (m *AddFeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeatureResponse.Unmarshal(m, b)
}
func (m *AddFeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeatureResponse.Marshal(b, m, deterministic)
}
func (dst *AddFeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeatureResponse.Merge(dst, src)
}
func (m *AddFeatureResponse) XXX_Size() int {
	return xxx_messageInfo_AddFeatureResponse.Size(m)
}
func (m *AddFeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeatureResponse proto.InternalMessageInfo

type GetFeatureResponse struct {
	Feature              *Feature `protobuf:"bytes,1,opt,name=feature" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeatureResponse) Reset()         { *m = GetFeatureResponse{} }
func (m *GetFeatureResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeatureResponse) ProtoMessage()    {}
func (*GetFeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{4}
}
func (m *GetFeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeatureResponse.Unmarshal(m, b)
}
func (m *GetFeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeatureResponse.Marshal(b, m, deterministic)
}
func (dst *GetFeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeatureResponse.Merge(dst, src)
}
func (m *GetFeatureResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeatureResponse.Size(m)
}
func (m *GetFeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeatureResponse proto.InternalMessageInfo

func (m *GetFeatureResponse) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type Feature struct {
	Name       string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status     Feature_FeatureStatus `protobuf:"varint,2,opt,name=status,proto3,enum=chainconfig.Feature_FeatureStatus" json:"status,omitempty"`
	Validators []*types.Address      `protobuf:"bytes,3,rep,name=validators" json:"validators,omitempty"`
	// Percentage of feature enabled validators exceeds vote_threshold at this block_height
	BlockHeight uint64 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Feature changes status from `pending` to `waiting` with at this percentage
	Percentage uint64 `protobuf:"varint,5,opt,name=percentage,proto3" json:"percentage,omitempty"`
	// Minimum build number that supports this feature
	BuildNumber uint64 `protobuf:"varint,6,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	// Pending feature is automatically enabled if it is supported in current build
	AutoEnable           bool     `protobuf:"varint,7,opt,name=auto_enable,json=autoEnable,proto3" json:"auto_enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{5}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetStatus() Feature_FeatureStatus {
	if m != nil {
		return m.Status
	}
	return Feature_PENDING
}

func (m *Feature) GetValidators() []*types.Address {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *Feature) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Feature) GetPercentage() uint64 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Feature) GetBuildNumber() uint64 {
	if m != nil {
		return m.BuildNumber
	}
	return 0
}

func (m *Feature) GetAutoEnable() bool {
	if m != nil {
		return m.AutoEnable
	}
	return false
}

type ValidatorInfo struct {
	Address              *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	BuildNumber          uint64         `protobuf:"varint,2,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	UpdatedAt            uint64         `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ValidatorInfo) Reset()         { *m = ValidatorInfo{} }
func (m *ValidatorInfo) String() string { return proto.CompactTextString(m) }
func (*ValidatorInfo) ProtoMessage()    {}
func (*ValidatorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{6}
}
func (m *ValidatorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorInfo.Unmarshal(m, b)
}
func (m *ValidatorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorInfo.Marshal(b, m, deterministic)
}
func (dst *ValidatorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorInfo.Merge(dst, src)
}
func (m *ValidatorInfo) XXX_Size() int {
	return xxx_messageInfo_ValidatorInfo.Size(m)
}
func (m *ValidatorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorInfo proto.InternalMessageInfo

func (m *ValidatorInfo) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ValidatorInfo) GetBuildNumber() uint64 {
	if m != nil {
		return m.BuildNumber
	}
	return 0
}

func (m *ValidatorInfo) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Params struct {
	VoteThreshold         uint64   `protobuf:"varint,1,opt,name=vote_threshold,json=voteThreshold,proto3" json:"vote_threshold,omitempty"`
	NumBlockConfirmations uint64   `protobuf:"varint,2,opt,name=num_block_confirmations,json=numBlockConfirmations,proto3" json:"num_block_confirmations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{7}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (dst *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(dst, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetVoteThreshold() uint64 {
	if m != nil {
		return m.VoteThreshold
	}
	return 0
}

func (m *Params) GetNumBlockConfirmations() uint64 {
	if m != nil {
		return m.NumBlockConfirmations
	}
	return 0
}

type SetParamsRequest struct {
	Params               *Params  `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetParamsRequest) Reset()         { *m = SetParamsRequest{} }
func (m *SetParamsRequest) String() string { return proto.CompactTextString(m) }
func (*SetParamsRequest) ProtoMessage()    {}
func (*SetParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{8}
}
func (m *SetParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetParamsRequest.Unmarshal(m, b)
}
func (m *SetParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetParamsRequest.Marshal(b, m, deterministic)
}
func (dst *SetParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetParamsRequest.Merge(dst, src)
}
func (m *SetParamsRequest) XXX_Size() int {
	return xxx_messageInfo_SetParamsRequest.Size(m)
}
func (m *SetParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetParamsRequest proto.InternalMessageInfo

func (m *SetParamsRequest) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type GetParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParamsRequest) Reset()         { *m = GetParamsRequest{} }
func (m *GetParamsRequest) String() string { return proto.CompactTextString(m) }
func (*GetParamsRequest) ProtoMessage()    {}
func (*GetParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{9}
}
func (m *GetParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParamsRequest.Unmarshal(m, b)
}
func (m *GetParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParamsRequest.Marshal(b, m, deterministic)
}
func (dst *GetParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParamsRequest.Merge(dst, src)
}
func (m *GetParamsRequest) XXX_Size() int {
	return xxx_messageInfo_GetParamsRequest.Size(m)
}
func (m *GetParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetParamsRequest proto.InternalMessageInfo

type GetParamsResponse struct {
	Params               *Params  `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParamsResponse) Reset()         { *m = GetParamsResponse{} }
func (m *GetParamsResponse) String() string { return proto.CompactTextString(m) }
func (*GetParamsResponse) ProtoMessage()    {}
func (*GetParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{10}
}
func (m *GetParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParamsResponse.Unmarshal(m, b)
}
func (m *GetParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParamsResponse.Marshal(b, m, deterministic)
}
func (dst *GetParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParamsResponse.Merge(dst, src)
}
func (m *GetParamsResponse) XXX_Size() int {
	return xxx_messageInfo_GetParamsResponse.Size(m)
}
func (m *GetParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetParamsResponse proto.InternalMessageInfo

func (m *GetParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type ListFeaturesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFeaturesRequest) Reset()         { *m = ListFeaturesRequest{} }
func (m *ListFeaturesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFeaturesRequest) ProtoMessage()    {}
func (*ListFeaturesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{11}
}
func (m *ListFeaturesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeaturesRequest.Unmarshal(m, b)
}
func (m *ListFeaturesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeaturesRequest.Marshal(b, m, deterministic)
}
func (dst *ListFeaturesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeaturesRequest.Merge(dst, src)
}
func (m *ListFeaturesRequest) XXX_Size() int {
	return xxx_messageInfo_ListFeaturesRequest.Size(m)
}
func (m *ListFeaturesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeaturesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeaturesRequest proto.InternalMessageInfo

type ListFeaturesResponse struct {
	Features             []*Feature `protobuf:"bytes,1,rep,name=features" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListFeaturesResponse) Reset()         { *m = ListFeaturesResponse{} }
func (m *ListFeaturesResponse) String() string { return proto.CompactTextString(m) }
func (*ListFeaturesResponse) ProtoMessage()    {}
func (*ListFeaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{12}
}
func (m *ListFeaturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFeaturesResponse.Unmarshal(m, b)
}
func (m *ListFeaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFeaturesResponse.Marshal(b, m, deterministic)
}
func (dst *ListFeaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFeaturesResponse.Merge(dst, src)
}
func (m *ListFeaturesResponse) XXX_Size() int {
	return xxx_messageInfo_ListFeaturesResponse.Size(m)
}
func (m *ListFeaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFeaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFeaturesResponse proto.InternalMessageInfo

func (m *ListFeaturesResponse) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

type EnableFeatureRequest struct {
	Names                []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableFeatureRequest) Reset()         { *m = EnableFeatureRequest{} }
func (m *EnableFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*EnableFeatureRequest) ProtoMessage()    {}
func (*EnableFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{13}
}
func (m *EnableFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableFeatureRequest.Unmarshal(m, b)
}
func (m *EnableFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableFeatureRequest.Marshal(b, m, deterministic)
}
func (dst *EnableFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableFeatureRequest.Merge(dst, src)
}
func (m *EnableFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_EnableFeatureRequest.Size(m)
}
func (m *EnableFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableFeatureRequest proto.InternalMessageInfo

func (m *EnableFeatureRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type EnableFeatureResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableFeatureResponse) Reset()         { *m = EnableFeatureResponse{} }
func (m *EnableFeatureResponse) String() string { return proto.CompactTextString(m) }
func (*EnableFeatureResponse) ProtoMessage()    {}
func (*EnableFeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{14}
}
func (m *EnableFeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableFeatureResponse.Unmarshal(m, b)
}
func (m *EnableFeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableFeatureResponse.Marshal(b, m, deterministic)
}
func (dst *EnableFeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableFeatureResponse.Merge(dst, src)
}
func (m *EnableFeatureResponse) XXX_Size() int {
	return xxx_messageInfo_EnableFeatureResponse.Size(m)
}
func (m *EnableFeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableFeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableFeatureResponse proto.InternalMessageInfo

type RemoveFeatureRequest struct {
	Names                []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFeatureRequest) Reset()         { *m = RemoveFeatureRequest{} }
func (m *RemoveFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFeatureRequest) ProtoMessage()    {}
func (*RemoveFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{15}
}
func (m *RemoveFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFeatureRequest.Unmarshal(m, b)
}
func (m *RemoveFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFeatureRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFeatureRequest.Merge(dst, src)
}
func (m *RemoveFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFeatureRequest.Size(m)
}
func (m *RemoveFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFeatureRequest proto.InternalMessageInfo

func (m *RemoveFeatureRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

// An action represents a pending change to the on-chain config.
type Action struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	BuildNumber          uint64   `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{16}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Action) GetBuildNumber() uint64 {
	if m != nil {
		return m.BuildNumber
	}
	return 0
}

type AppStoreConfig struct {
	NumEvmKeysToPrune    uint64   `protobuf:"varint,1,opt,name=num_evm_keys_to_prune,json=numEvmKeysToPrune,proto3" json:"num_evm_keys_to_prune"`
	IAVLFlushInterval    uint64   `protobuf:"varint,2,opt,name=iavl_flush_interval,json=iavlFlushInterval,proto3" json:"iavl_flush_interval"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppStoreConfig) Reset()         { *m = AppStoreConfig{} }
func (m *AppStoreConfig) String() string { return proto.CompactTextString(m) }
func (*AppStoreConfig) ProtoMessage()    {}
func (*AppStoreConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{17}
}
func (m *AppStoreConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppStoreConfig.Unmarshal(m, b)
}
func (m *AppStoreConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppStoreConfig.Marshal(b, m, deterministic)
}
func (dst *AppStoreConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppStoreConfig.Merge(dst, src)
}
func (m *AppStoreConfig) XXX_Size() int {
	return xxx_messageInfo_AppStoreConfig.Size(m)
}
func (m *AppStoreConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppStoreConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppStoreConfig proto.InternalMessageInfo

func (m *AppStoreConfig) GetNumEvmKeysToPrune() uint64 {
	if m != nil {
		return m.NumEvmKeysToPrune
	}
	return 0
}

func (m *AppStoreConfig) GetIAVLFlushInterval() uint64 {
	if m != nil {
		return m.IAVLFlushInterval
	}
	return 0
}

type EvmConfig struct {
	GasLimit             uint64   `protobuf:"varint,1,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmConfig) Reset()         { *m = EvmConfig{} }
func (m *EvmConfig) String() string { return proto.CompactTextString(m) }
func (*EvmConfig) ProtoMessage()    {}
func (*EvmConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{18}
}
func (m *EvmConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmConfig.Unmarshal(m, b)
}
func (m *EvmConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmConfig.Marshal(b, m, deterministic)
}
func (dst *EvmConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmConfig.Merge(dst, src)
}
func (m *EvmConfig) XXX_Size() int {
	return xxx_messageInfo_EvmConfig.Size(m)
}
func (m *EvmConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EvmConfig proto.InternalMessageInfo

func (m *EvmConfig) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

type NonceHandlerConfig struct {
	IncNonceOnFailedTx   bool     `protobuf:"varint,1,opt,name=inc_nonce_on_failed_tx,json=incNonceOnFailedTx,proto3" json:"inc_nonce_on_failed_tx"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceHandlerConfig) Reset()         { *m = NonceHandlerConfig{} }
func (m *NonceHandlerConfig) String() string { return proto.CompactTextString(m) }
func (*NonceHandlerConfig) ProtoMessage()    {}
func (*NonceHandlerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{19}
}
func (m *NonceHandlerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceHandlerConfig.Unmarshal(m, b)
}
func (m *NonceHandlerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceHandlerConfig.Marshal(b, m, deterministic)
}
func (dst *NonceHandlerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceHandlerConfig.Merge(dst, src)
}
func (m *NonceHandlerConfig) XXX_Size() int {
	return xxx_messageInfo_NonceHandlerConfig.Size(m)
}
func (m *NonceHandlerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceHandlerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NonceHandlerConfig proto.InternalMessageInfo

func (m *NonceHandlerConfig) GetIncNonceOnFailedTx() bool {
	if m != nil {
		return m.IncNonceOnFailedTx
	}
	return false
}

type Config struct {
	Evm                  *EvmConfig          `protobuf:"bytes,1,opt,name=evm" json:"evm,omitempty"`
	AppStore             *AppStoreConfig     `protobuf:"bytes,2,opt,name=app_store,json=appStore" json:"app_store,omitempty"`
	NonceHandler         *NonceHandlerConfig `protobuf:"bytes,3,opt,name=nonce_handler,json=nonceHandler" json:"nonce_handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{20}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetEvm() *EvmConfig {
	if m != nil {
		return m.Evm
	}
	return nil
}

func (m *Config) GetAppStore() *AppStoreConfig {
	if m != nil {
		return m.AppStore
	}
	return nil
}

func (m *Config) GetNonceHandler() *NonceHandlerConfig {
	if m != nil {
		return m.NonceHandler
	}
	return nil
}

type SetSettingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	BuildNumber          uint64   `protobuf:"varint,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSettingRequest) Reset()         { *m = SetSettingRequest{} }
func (m *SetSettingRequest) String() string { return proto.CompactTextString(m) }
func (*SetSettingRequest) ProtoMessage()    {}
func (*SetSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{21}
}
func (m *SetSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSettingRequest.Unmarshal(m, b)
}
func (m *SetSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSettingRequest.Marshal(b, m, deterministic)
}
func (dst *SetSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSettingRequest.Merge(dst, src)
}
func (m *SetSettingRequest) XXX_Size() int {
	return xxx_messageInfo_SetSettingRequest.Size(m)
}
func (m *SetSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSettingRequest proto.InternalMessageInfo

func (m *SetSettingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetSettingRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetSettingRequest) GetBuildNumber() uint64 {
	if m != nil {
		return m.BuildNumber
	}
	return 0
}

type ListPendingActionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPendingActionsRequest) Reset()         { *m = ListPendingActionsRequest{} }
func (m *ListPendingActionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPendingActionsRequest) ProtoMessage()    {}
func (*ListPendingActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{22}
}
func (m *ListPendingActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPendingActionsRequest.Unmarshal(m, b)
}
func (m *ListPendingActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPendingActionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPendingActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPendingActionsRequest.Merge(dst, src)
}
func (m *ListPendingActionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPendingActionsRequest.Size(m)
}
func (m *ListPendingActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPendingActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPendingActionsRequest proto.InternalMessageInfo

type ListPendingActionsResponse struct {
	Actions              []*Action `protobuf:"bytes,1,rep,name=actions" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListPendingActionsResponse) Reset()         { *m = ListPendingActionsResponse{} }
func (m *ListPendingActionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPendingActionsResponse) ProtoMessage()    {}
func (*ListPendingActionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{23}
}
func (m *ListPendingActionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPendingActionsResponse.Unmarshal(m, b)
}
func (m *ListPendingActionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPendingActionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPendingActionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPendingActionsResponse.Merge(dst, src)
}
func (m *ListPendingActionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPendingActionsResponse.Size(m)
}
func (m *ListPendingActionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPendingActionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPendingActionsResponse proto.InternalMessageInfo

func (m *ListPendingActionsResponse) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type ChainConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainConfigRequest) Reset()         { *m = ChainConfigRequest{} }
func (m *ChainConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ChainConfigRequest) ProtoMessage()    {}
func (*ChainConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{24}
}
func (m *ChainConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainConfigRequest.Unmarshal(m, b)
}
func (m *ChainConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainConfigRequest.Marshal(b, m, deterministic)
}
func (dst *ChainConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainConfigRequest.Merge(dst, src)
}
func (m *ChainConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ChainConfigRequest.Size(m)
}
func (m *ChainConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChainConfigRequest proto.InternalMessageInfo

type ChainConfigResponse struct {
	Config               *Config  `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainConfigResponse) Reset()         { *m = ChainConfigResponse{} }
func (m *ChainConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ChainConfigResponse) ProtoMessage()    {}
func (*ChainConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{25}
}
func (m *ChainConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainConfigResponse.Unmarshal(m, b)
}
func (m *ChainConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ChainConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainConfigResponse.Merge(dst, src)
}
func (m *ChainConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ChainConfigResponse.Size(m)
}
func (m *ChainConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChainConfigResponse proto.InternalMessageInfo

func (m *ChainConfigResponse) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetValidatorInfoRequest struct {
	BuildNumber          uint64   `protobuf:"varint,1,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValidatorInfoRequest) Reset()         { *m = SetValidatorInfoRequest{} }
func (m *SetValidatorInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SetValidatorInfoRequest) ProtoMessage()    {}
func (*SetValidatorInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{26}
}
func (m *SetValidatorInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValidatorInfoRequest.Unmarshal(m, b)
}
func (m *SetValidatorInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValidatorInfoRequest.Marshal(b, m, deterministic)
}
func (dst *SetValidatorInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValidatorInfoRequest.Merge(dst, src)
}
func (m *SetValidatorInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SetValidatorInfoRequest.Size(m)
}
func (m *SetValidatorInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValidatorInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetValidatorInfoRequest proto.InternalMessageInfo

func (m *SetValidatorInfoRequest) GetBuildNumber() uint64 {
	if m != nil {
		return m.BuildNumber
	}
	return 0
}

type GetValidatorInfoRequest struct {
	Address              *types.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetValidatorInfoRequest) Reset()         { *m = GetValidatorInfoRequest{} }
func (m *GetValidatorInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetValidatorInfoRequest) ProtoMessage()    {}
func (*GetValidatorInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{27}
}
func (m *GetValidatorInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorInfoRequest.Unmarshal(m, b)
}
func (m *GetValidatorInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetValidatorInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorInfoRequest.Merge(dst, src)
}
func (m *GetValidatorInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetValidatorInfoRequest.Size(m)
}
func (m *GetValidatorInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorInfoRequest proto.InternalMessageInfo

func (m *GetValidatorInfoRequest) GetAddress() *types.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type GetValidatorInfoResponse struct {
	Validator            *ValidatorInfo `protobuf:"bytes,1,opt,name=validator" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetValidatorInfoResponse) Reset()         { *m = GetValidatorInfoResponse{} }
func (m *GetValidatorInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetValidatorInfoResponse) ProtoMessage()    {}
func (*GetValidatorInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{28}
}
func (m *GetValidatorInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValidatorInfoResponse.Unmarshal(m, b)
}
func (m *GetValidatorInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValidatorInfoResponse.Marshal(b, m, deterministic)
}
func (dst *GetValidatorInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValidatorInfoResponse.Merge(dst, src)
}
func (m *GetValidatorInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetValidatorInfoResponse.Size(m)
}
func (m *GetValidatorInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValidatorInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValidatorInfoResponse proto.InternalMessageInfo

func (m *GetValidatorInfoResponse) GetValidator() *ValidatorInfo {
	if m != nil {
		return m.Validator
	}
	return nil
}

type ListValidatorsInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListValidatorsInfoRequest) Reset()         { *m = ListValidatorsInfoRequest{} }
func (m *ListValidatorsInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ListValidatorsInfoRequest) ProtoMessage()    {}
func (*ListValidatorsInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{29}
}
func (m *ListValidatorsInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValidatorsInfoRequest.Unmarshal(m, b)
}
func (m *ListValidatorsInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValidatorsInfoRequest.Marshal(b, m, deterministic)
}
func (dst *ListValidatorsInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValidatorsInfoRequest.Merge(dst, src)
}
func (m *ListValidatorsInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ListValidatorsInfoRequest.Size(m)
}
func (m *ListValidatorsInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValidatorsInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListValidatorsInfoRequest proto.InternalMessageInfo

type ListValidatorsInfoResponse struct {
	Validators           []*ValidatorInfo `protobuf:"bytes,1,rep,name=validators" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListValidatorsInfoResponse) Reset()         { *m = ListValidatorsInfoResponse{} }
func (m *ListValidatorsInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ListValidatorsInfoResponse) ProtoMessage()    {}
func (*ListValidatorsInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chainconfig_a44f98daefff2162, []int{30}
}
func (m *ListValidatorsInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValidatorsInfoResponse.Unmarshal(m, b)
}
func (m *ListValidatorsInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValidatorsInfoResponse.Marshal(b, m, deterministic)
}
func (dst *ListValidatorsInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValidatorsInfoResponse.Merge(dst, src)
}
func (m *ListValidatorsInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ListValidatorsInfoResponse.Size(m)
}
func (m *ListValidatorsInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValidatorsInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListValidatorsInfoResponse proto.InternalMessageInfo

func (m *ListValidatorsInfoResponse) GetValidators() []*ValidatorInfo {
	if m != nil {
		return m.Validators
	}
	return nil
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "chainconfig.InitRequest")
	proto.RegisterType((*GetFeatureRequest)(nil), "chainconfig.GetFeatureRequest")
	proto.RegisterType((*AddFeatureRequest)(nil), "chainconfig.AddFeatureRequest")
	proto.RegisterType((*AddFeatureResponse)(nil), "chainconfig.AddFeatureResponse")
	proto.RegisterType((*GetFeatureResponse)(nil), "chainconfig.GetFeatureResponse")
	proto.RegisterType((*Feature)(nil), "chainconfig.Feature")
	proto.RegisterType((*ValidatorInfo)(nil), "chainconfig.ValidatorInfo")
	proto.RegisterType((*Params)(nil), "chainconfig.Params")
	proto.RegisterType((*SetParamsRequest)(nil), "chainconfig.SetParamsRequest")
	proto.RegisterType((*GetParamsRequest)(nil), "chainconfig.GetParamsRequest")
	proto.RegisterType((*GetParamsResponse)(nil), "chainconfig.GetParamsResponse")
	proto.RegisterType((*ListFeaturesRequest)(nil), "chainconfig.ListFeaturesRequest")
	proto.RegisterType((*ListFeaturesResponse)(nil), "chainconfig.ListFeaturesResponse")
	proto.RegisterType((*EnableFeatureRequest)(nil), "chainconfig.EnableFeatureRequest")
	proto.RegisterType((*EnableFeatureResponse)(nil), "chainconfig.EnableFeatureResponse")
	proto.RegisterType((*RemoveFeatureRequest)(nil), "chainconfig.RemoveFeatureRequest")
	proto.RegisterType((*Action)(nil), "chainconfig.Action")
	proto.RegisterType((*AppStoreConfig)(nil), "chainconfig.AppStoreConfig")
	proto.RegisterType((*EvmConfig)(nil), "chainconfig.EvmConfig")
	proto.RegisterType((*NonceHandlerConfig)(nil), "chainconfig.NonceHandlerConfig")
	proto.RegisterType((*Config)(nil), "chainconfig.Config")
	proto.RegisterType((*SetSettingRequest)(nil), "chainconfig.SetSettingRequest")
	proto.RegisterType((*ListPendingActionsRequest)(nil), "chainconfig.ListPendingActionsRequest")
	proto.RegisterType((*ListPendingActionsResponse)(nil), "chainconfig.ListPendingActionsResponse")
	proto.RegisterType((*ChainConfigRequest)(nil), "chainconfig.ChainConfigRequest")
	proto.RegisterType((*ChainConfigResponse)(nil), "chainconfig.ChainConfigResponse")
	proto.RegisterType((*SetValidatorInfoRequest)(nil), "chainconfig.SetValidatorInfoRequest")
	proto.RegisterType((*GetValidatorInfoRequest)(nil), "chainconfig.GetValidatorInfoRequest")
	proto.RegisterType((*GetValidatorInfoResponse)(nil), "chainconfig.GetValidatorInfoResponse")
	proto.RegisterType((*ListValidatorsInfoRequest)(nil), "chainconfig.ListValidatorsInfoRequest")
	proto.RegisterType((*ListValidatorsInfoResponse)(nil), "chainconfig.ListValidatorsInfoResponse")
	proto.RegisterEnum("chainconfig.Feature_FeatureStatus", Feature_FeatureStatus_name, Feature_FeatureStatus_value)
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/builtin/types/chainconfig/chainconfig.proto", fileDescriptor_chainconfig_a44f98daefff2162)
}

var fileDescriptor_chainconfig_a44f98daefff2162 = []byte{
	// 1080 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0x6e, 0x48, 0xc8, 0xcf, 0x09, 0x20, 0x32, 0x84, 0x25, 0xcb, 0xaa, 0x1b, 0x6a, 0xa9, 0x6a,
	0xd4, 0x02, 0x59, 0x51, 0xa9, 0x5d, 0xad, 0x5a, 0xb5, 0xc9, 0x26, 0x40, 0x0a, 0x4a, 0x91, 0x43,
	0xb7, 0xbd, 0xa8, 0xe4, 0x4e, 0xe2, 0x89, 0x63, 0x61, 0xcf, 0xa4, 0xf6, 0x38, 0xbb, 0xbc, 0x43,
	0x9f, 0xa6, 0xb7, 0x7d, 0x89, 0x3e, 0x01, 0x17, 0xbd, 0xe4, 0x29, 0xaa, 0xf9, 0x71, 0xb0, 0x49,
	0x76, 0xa1, 0xbd, 0x01, 0x9f, 0xef, 0x7c, 0xe7, 0xcc, 0xf9, 0x9d, 0x09, 0xfc, 0xe0, 0xb8, 0x7c,
	0x12, 0x0d, 0x0f, 0x47, 0xcc, 0x6f, 0x7a, 0x8c, 0xf9, 0x94, 0xf0, 0xb7, 0x2c, 0xb8, 0x6a, 0x3a,
	0xec, 0x40, 0x88, 0xcd, 0x61, 0xe4, 0x7a, 0xdc, 0xa5, 0x4d, 0x7e, 0x3d, 0x25, 0x61, 0x73, 0x34,
	0xc1, 0x2e, 0x1d, 0x31, 0x3a, 0x76, 0x9d, 0xe4, 0xf7, 0xe1, 0x34, 0x60, 0x9c, 0xa1, 0x72, 0x02,
	0xda, 0x7d, 0xf1, 0x80, 0x63, 0xe5, 0x50, 0xfe, 0x55, 0xe6, 0xbb, 0x07, 0x09, 0x0b, 0x87, 0x39,
	0xac, 0x29, 0xe1, 0x61, 0x34, 0x96, 0x92, 0x14, 0xe4, 0x97, 0xa2, 0x1b, 0x7f, 0x64, 0xa0, 0xdc,
	0xa3, 0x2e, 0x37, 0xc9, 0xef, 0x11, 0x09, 0x39, 0x7a, 0x0e, 0xab, 0xec, 0x2d, 0x25, 0x41, 0x2d,
	0xb3, 0x97, 0x69, 0x94, 0x8f, 0x8a, 0x87, 0x2d, 0xdb, 0x0e, 0x48, 0x18, 0x9a, 0x0a, 0x46, 0x5f,
	0x40, 0x7e, 0x8a, 0x03, 0xec, 0x87, 0xb5, 0x15, 0x49, 0xd8, 0x3a, 0x4c, 0x66, 0x70, 0x21, 0x55,
	0xa6, 0xa6, 0xa0, 0x17, 0x50, 0x1c, 0x13, 0xcc, 0xa3, 0x80, 0x84, 0xb5, 0xec, 0x5e, 0xb6, 0x51,
	0x3e, 0xaa, 0xa6, 0xe8, 0xc7, 0x4a, 0x69, 0xce, 0x59, 0xc6, 0x67, 0x50, 0x39, 0x21, 0x3c, 0xc6,
	0x75, 0x4c, 0x08, 0x72, 0x14, 0xfb, 0x44, 0x86, 0x54, 0x32, 0xe5, 0xb7, 0xe1, 0x43, 0xa5, 0x65,
	0xdb, 0xf7, 0x88, 0x55, 0x58, 0x15, 0xca, 0xb0, 0x96, 0xd9, 0xcb, 0x36, 0x4a, 0xa6, 0x12, 0xd0,
	0x27, 0xb0, 0x26, 0xea, 0x6f, 0x5b, 0x34, 0xf2, 0x87, 0x24, 0x90, 0x81, 0xe7, 0xcc, 0xb2, 0xc4,
	0xfa, 0x12, 0x42, 0x75, 0x28, 0xe3, 0x88, 0x33, 0x8b, 0x50, 0x3c, 0xf4, 0x48, 0x2d, 0xbb, 0x97,
	0x69, 0x14, 0x4d, 0x10, 0x50, 0x57, 0x22, 0x46, 0x15, 0x50, 0xf2, 0xb8, 0x70, 0xca, 0x68, 0x48,
	0x8c, 0x0e, 0xa0, 0x64, 0xb4, 0x0a, 0x45, 0x87, 0x50, 0xd0, 0xf9, 0xe8, 0x22, 0x2e, 0x4f, 0x3a,
	0x26, 0x19, 0x7f, 0xaf, 0x40, 0x41, 0x83, 0xcb, 0x52, 0x45, 0xaf, 0x20, 0x1f, 0x72, 0xcc, 0x23,
	0x55, 0xf2, 0x8d, 0x23, 0x63, 0x99, 0xbb, 0xf8, 0xff, 0x40, 0x32, 0x4d, 0x6d, 0x81, 0x1a, 0x00,
	0x33, 0xec, 0xb9, 0x36, 0xe6, 0x2c, 0x88, 0x7b, 0x70, 0xd7, 0xd3, 0x84, 0x4e, 0x56, 0xc9, 0x63,
	0xa3, 0x2b, 0x6b, 0x42, 0x5c, 0x67, 0xc2, 0x6b, 0x39, 0x5d, 0x25, 0x81, 0x9d, 0x4a, 0x08, 0x3d,
	0x07, 0x98, 0x92, 0x60, 0x44, 0x28, 0xc7, 0x0e, 0xa9, 0xad, 0x4a, 0x42, 0x02, 0x59, 0x28, 0x74,
	0xfe, 0xc1, 0x42, 0x17, 0x16, 0x0a, 0xdd, 0x81, 0xf5, 0x54, 0x26, 0xa8, 0x0c, 0x85, 0x8b, 0x6e,
	0xbf, 0xd3, 0xeb, 0x9f, 0x6c, 0x7e, 0x24, 0x84, 0x9f, 0x5b, 0xbd, 0x4b, 0x21, 0x64, 0x84, 0xd0,
	0xed, 0xb7, 0xda, 0xe7, 0xdd, 0xce, 0xe6, 0x0a, 0x5a, 0x83, 0x62, 0xa7, 0x37, 0x50, 0x52, 0xd6,
	0x88, 0x60, 0xfd, 0x4d, 0x9c, 0x5a, 0x8f, 0x8e, 0x19, 0x32, 0xa0, 0x80, 0x55, 0xd2, 0x0b, 0x83,
	0x1d, 0x2b, 0x1e, 0x33, 0x27, 0x1f, 0x03, 0x44, 0x53, 0x1b, 0x73, 0x62, 0x5b, 0x98, 0xcb, 0x31,
	0xc9, 0x99, 0x25, 0x8d, 0xb4, 0xb8, 0xe1, 0x40, 0x5e, 0x6d, 0x00, 0xfa, 0x14, 0x36, 0x66, 0x8c,
	0x13, 0x8b, 0x4f, 0x02, 0x12, 0x4e, 0x98, 0x67, 0xcb, 0x63, 0x73, 0xe6, 0xba, 0x40, 0x2f, 0x63,
	0x10, 0x7d, 0x05, 0x3b, 0x34, 0xf2, 0x2d, 0x55, 0x78, 0xd9, 0xd0, 0xc0, 0xc7, 0xdc, 0x65, 0x34,
	0xd4, 0xa7, 0x6f, 0xd3, 0xc8, 0x6f, 0x0b, 0xed, 0xeb, 0xa4, 0xd2, 0xf8, 0x0e, 0x36, 0x07, 0x84,
	0xeb, 0x6d, 0xd3, 0xc3, 0x7f, 0xb7, 0x99, 0x99, 0x07, 0x37, 0xd3, 0x40, 0xb0, 0x79, 0x72, 0xcf,
	0x81, 0xf1, 0xbd, 0xdc, 0xbd, 0x18, 0xd3, 0xc3, 0xfc, 0x9f, 0xbc, 0x6e, 0xc3, 0xd6, 0xb9, 0x1b,
	0xc6, 0x0b, 0x31, 0x77, 0x7c, 0x0a, 0xd5, 0x34, 0xac, 0x7d, 0x27, 0xaf, 0x87, 0xcc, 0xa3, 0xae,
	0x87, 0x7d, 0xa8, 0xaa, 0x39, 0x79, 0xcc, 0xe2, 0x1b, 0x3b, 0xb0, 0x7d, 0x8f, 0xad, 0xf7, 0x76,
	0x1f, 0xaa, 0x26, 0xf1, 0xd9, 0xec, 0x71, 0x6e, 0x7e, 0x82, 0x7c, 0x6b, 0x24, 0xea, 0xbe, 0x74,
	0x3b, 0xab, 0xb0, 0x3a, 0xc3, 0x5e, 0x44, 0x64, 0xc3, 0x4a, 0xa6, 0x12, 0x16, 0x66, 0x29, 0xbb,
	0x30, 0x4b, 0xc6, 0x5f, 0x19, 0xd8, 0x68, 0x4d, 0xa7, 0x03, 0xce, 0x02, 0x22, 0xbb, 0xeb, 0xa0,
	0x33, 0x10, 0xfd, 0xb6, 0xc8, 0xcc, 0xb7, 0xae, 0xc8, 0x75, 0x68, 0x71, 0x66, 0x4d, 0x83, 0x88,
	0xaa, 0x03, 0x73, 0xed, 0xa7, 0xb7, 0x37, 0xf5, 0xe5, 0x04, 0xb3, 0x42, 0x23, 0xbf, 0x3b, 0xf3,
	0xcf, 0xc8, 0x75, 0x78, 0xc9, 0x2e, 0x04, 0x84, 0x7e, 0x85, 0x2d, 0x17, 0xcf, 0x3c, 0x6b, 0xec,
	0x45, 0xe1, 0xc4, 0x72, 0x29, 0x27, 0xc1, 0x0c, 0x7b, 0x6a, 0xae, 0xda, 0xfb, 0xff, 0xdc, 0xd4,
	0x2b, 0xbd, 0xd6, 0x9b, 0xf3, 0x63, 0xa1, 0xed, 0x69, 0xe5, 0xed, 0x4d, 0x7d, 0x99, 0x8d, 0x59,
	0x11, 0x60, 0x8a, 0x69, 0x7c, 0x0d, 0xa5, 0xee, 0xcc, 0xd7, 0x71, 0x7f, 0x0e, 0x25, 0x07, 0x87,
	0x96, 0xe7, 0xfa, 0x2e, 0xd7, 0xb1, 0xae, 0xdf, 0xde, 0xd4, 0xef, 0x40, 0xb3, 0xe8, 0xe0, 0xf0,
	0x5c, 0x7c, 0x19, 0x36, 0xa0, 0x3e, 0xa3, 0x23, 0x72, 0x8a, 0xa9, 0xed, 0x91, 0x40, 0x7b, 0xe8,
	0xc3, 0x13, 0x97, 0x8e, 0x2c, 0x2a, 0x34, 0x16, 0xa3, 0xd6, 0x18, 0xbb, 0x1e, 0xb1, 0x2d, 0xfe,
	0x4e, 0xba, 0x2b, 0xb6, 0x77, 0x6f, 0x6f, 0xea, 0xef, 0x61, 0x98, 0xc8, 0xa5, 0x23, 0xe9, 0xf2,
	0x47, 0x7a, 0x2c, 0xc1, 0xcb, 0x77, 0xc6, 0x9f, 0x19, 0xc8, 0x6b, 0xd7, 0x0d, 0xc8, 0x92, 0x99,
	0xaf, 0xc7, 0xf7, 0x49, 0x6a, 0xc0, 0xe6, 0x19, 0x98, 0x82, 0x82, 0x5e, 0x42, 0x09, 0x4f, 0xa7,
	0x56, 0x28, 0x3a, 0xa2, 0x9f, 0xb7, 0x67, 0x29, 0x7e, 0xba, 0x5d, 0x66, 0x11, 0x6b, 0x19, 0x75,
	0x60, 0x5d, 0x05, 0x36, 0x51, 0x59, 0xc9, 0x7e, 0x97, 0x8f, 0xea, 0x29, 0xeb, 0xc5, 0xb4, 0xcd,
	0x35, 0x9a, 0xc0, 0x8c, 0xdf, 0xa0, 0x32, 0x20, 0x7c, 0x40, 0x38, 0x77, 0xa9, 0xf3, 0x81, 0xc7,
	0xef, 0xff, 0xcf, 0xdc, 0x33, 0x78, 0x2a, 0x36, 0xf1, 0x82, 0x50, 0xdb, 0xa5, 0x8e, 0x9a, 0xea,
	0xf9, 0x9a, 0x9e, 0xc1, 0xee, 0x32, 0xa5, 0x5e, 0xd6, 0x03, 0x28, 0x60, 0x05, 0xe9, 0x5d, 0x4d,
	0xdf, 0x04, 0x8a, 0x6e, 0xc6, 0x1c, 0xf1, 0x60, 0xbe, 0x16, 0x6a, 0x9d, 0xa8, 0x3e, 0xa2, 0x0d,
	0x5b, 0x29, 0xf4, 0xee, 0x92, 0x51, 0x6e, 0x96, 0x5e, 0x32, 0x9a, 0xac, 0x29, 0xc6, 0x37, 0xb0,
	0x33, 0x20, 0x3c, 0x75, 0xbd, 0xc7, 0xb5, 0xba, 0x5f, 0x81, 0xcc, 0x62, 0x05, 0xbe, 0x85, 0x9d,
	0x93, 0xf7, 0x58, 0x3f, 0xe2, 0x8d, 0x30, 0x2e, 0xa1, 0xb6, 0x68, 0xae, 0xb3, 0x78, 0x09, 0xa5,
	0xf9, 0x7b, 0xaa, 0x3d, 0xec, 0xa6, 0x12, 0x49, 0x9b, 0xdd, 0x91, 0xe3, 0xb6, 0xcc, 0xf5, 0x61,
	0x22, 0x2c, 0xe3, 0x17, 0xd5, 0x96, 0xfb, 0x4a, 0x7d, 0xe8, 0xab, 0xd4, 0x03, 0xaf, 0x3a, 0xf3,
	0xa1, 0x53, 0x13, 0xec, 0x61, 0x5e, 0xfe, 0x04, 0xfc, 0xf2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x8b, 0xbd, 0x83, 0x46, 0xbe, 0x0a, 0x00, 0x00,
}
