# This is a basic workflow to help you get started with Actions

name: Pull Request Build

# Controls when the action will run.
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/${{ github.repository }}

      - name: Setup env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}/go" >> $GITHUB_ENV
          echo "${{ github.workspace }}/go/bin" >> $GITHUB_PATH

      - name: Install
        run: |
          mkdir -p ${{ github.workspace }}/go/bin
          $GOPATH/src/github.com/${{ github.repository }}/.travis_before_install.sh

      - name: Build
        run: |
          cd $GOPATH/src/github.com/${{ github.repository }}
          make get-lint
          make lint || true
          make linterrors
          make
          make test
          make test-evm
