# This is a basic workflow to help you get started with Actions

name: Pull Request Build

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/${{ github.repository }}

      - name: Setup env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
          echo "::add-path::${{ github.workspace }}/go/bin"

      - name: Install
        run: ./.travis_before_install.sh

      - name: Build
        run: |
          cd $GOPATH/src/github.com/${{ github.repository }}
          make get_lint
          make deps-all
          make lint || true
          make linterrors
          make
          make test
          make test-evm
