// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/testdata/test.proto

/*
Package testdata is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/go-loom/testdata/test.proto

It has these top-level messages:
	CallArgs
	StaticCallArgs
	StaticCallResult
*/
package testdata

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CallArgs struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *CallArgs) Reset()                    { *m = CallArgs{} }
func (m *CallArgs) String() string            { return proto.CompactTextString(m) }
func (*CallArgs) ProtoMessage()               {}
func (*CallArgs) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{0} }

func (m *CallArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CallArgs) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type StaticCallArgs struct {
	Index int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *StaticCallArgs) Reset()                    { *m = StaticCallArgs{} }
func (m *StaticCallArgs) String() string            { return proto.CompactTextString(m) }
func (*StaticCallArgs) ProtoMessage()               {}
func (*StaticCallArgs) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{1} }

func (m *StaticCallArgs) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StaticCallArgs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StaticCallResult struct {
	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *StaticCallResult) Reset()                    { *m = StaticCallResult{} }
func (m *StaticCallResult) String() string            { return proto.CompactTextString(m) }
func (*StaticCallResult) ProtoMessage()               {}
func (*StaticCallResult) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{2} }

func (m *StaticCallResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *StaticCallResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*CallArgs)(nil), "testdata.CallArgs")
	proto.RegisterType((*StaticCallArgs)(nil), "testdata.StaticCallArgs")
	proto.RegisterType((*StaticCallResult)(nil), "testdata.StaticCallResult")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/testdata/test.proto", fileDescriptorTest)
}

var fileDescriptorTest = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xcd, 0x6a, 0x84, 0x30,
	0x10, 0x80, 0xb1, 0x6d, 0x44, 0xe7, 0x50, 0x24, 0x48, 0xf1, 0x28, 0x9e, 0xbc, 0x54, 0xa1, 0x85,
	0x1e, 0x7a, 0x58, 0x58, 0xf6, 0x0d, 0xb2, 0x4f, 0x10, 0x35, 0xb8, 0xc1, 0x98, 0x48, 0x9c, 0xec,
	0xcf, 0xdb, 0x2f, 0x46, 0x77, 0xf7, 0xf6, 0x7d, 0x33, 0xf3, 0x1d, 0x06, 0xfe, 0x7a, 0x89, 0x27,
	0xd7, 0x54, 0xad, 0x19, 0x6b, 0x65, 0xcc, 0xa8, 0x05, 0x5e, 0x8c, 0x1d, 0x3c, 0x7f, 0x4f, 0xca,
	0xf5, 0x52, 0xd7, 0x28, 0x66, 0xec, 0x38, 0x72, 0x0f, 0xd5, 0x64, 0x0d, 0x1a, 0x1a, 0x3d, 0x86,
	0xc5, 0x0f, 0x44, 0x07, 0xae, 0xd4, 0xde, 0xf6, 0x33, 0x4d, 0xe0, 0x7d, 0x10, 0xb7, 0x2c, 0xc8,
	0x83, 0x32, 0x66, 0x0b, 0xd2, 0x14, 0xc8, 0x99, 0x2b, 0x27, 0xb2, 0xb7, 0x3c, 0x28, 0x09, 0x5b,
	0xa5, 0xf8, 0x87, 0xcf, 0x23, 0x72, 0x94, 0xed, 0xb3, 0x4c, 0x81, 0x48, 0xdd, 0x89, 0xab, 0x6f,
	0x09, 0x5b, 0x85, 0x52, 0xf8, 0xd0, 0x7c, 0x5c, 0xe3, 0x98, 0x79, 0x2e, 0x76, 0x90, 0xbc, 0x5a,
	0x26, 0x66, 0xa7, 0x70, 0xb9, 0x6b, 0x4d, 0x27, 0xb6, 0xd8, 0x33, 0xfd, 0x82, 0xd0, 0xfa, 0xed,
	0x56, 0x6f, 0xd6, 0x84, 0xfe, 0x81, 0xdf, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0x47, 0x31,
	0x80, 0xfa, 0x00, 0x00, 0x00,
}
